<?php include '../public/core/defines.php'; ?>
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title><?= SITE_NAME ?></title>
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/assets/css/style.css">
		<link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap-extended.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/colors.min.css">
	</head>
	<body class="fix-header card-no-border">
		<section id="wrapper" class="error-page">
			<div class="error-box">
				<div class="error-body text-center">
					<h1>403</h1>
					<h3 class="text-uppercase">Acceso Prohibido</h3><br><br><br><br><br><br><br><br><br><br>
					<img class="img-fluid img" src="<?= URL_ROOT ?>/app-assets/images/logo/logo.png" alt="Logo"/><br>
					<a href="<?= URL_ROOT ?>" class="btn btn-success">Regresar al inicio</a> 
				</div>
				<footer class="footer text-center">© <?= date('Y'). ' ' . SITE_NAME ?></footer>
			</div>
		</section>
	</body>
</html>