<?php include '../public/core/defines.php'; ?>
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" type="image/png" sizes="16x16" href="<?= URL_ROOT ?>/app-assets/images/logo/favicon.ico">
		<title><?= SITE_NAME ?></title>
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/assets/css/style.css">
		<link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap-extended.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/colors.min.css">
	</head>
	<body class="fix-header card-no-border">
		<section id="wrapper" class="error-page">
			<div class="error-box">
				<div class="error-body text-center">
					<h1>404</h1>
					<h3 class="text-uppercase">Página no encontrada !</h3><br><br><br><br><br><br><br><br>
					<p class="text-muted m-t-30 m-b-30">LA PÁGINA NO FUE ENCONTRADA</p>
					<img class="img-fluid img" src="<?= URL_ROOT ?>/app-assets/images/logo/logo.png" alt="Logo"/><br>
					<a href="<?= URL_ROOT ?>" class="btn btn-success">Regresar al inicio</a> 
				</div>
				<footer class="footer text-center">© <?= date('Y'). ' ' . SITE_NAME ?></footer>
			</div>
		</section>
		<script src="<?= URL_ROOT ?>/assets/plugins/jquery/jquery.min.js"></script>
		<script src="<?= URL_ROOT ?>/assets/plugins/bootstrap/js/popper.min.js"></script>
		<script src="<?= URL_ROOT ?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?= URL_ROOT ?>/assets/js/waves.js"></script>
	</body>
</html>