<?php 
	include 'header.phtml';
?>
  <div class="app-content content ">
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card alert-success text-center">
                        <div class="card-body border-bottom">
                            <br>
                            <h1> ¡BIENVENIDO! </h1> 
                            <br><br>
                            <h3> Elige una sección en el menú izquierdo. </h3><br>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
<?php
  include 'footer.phtml';
?>
