<?php 
	include 'header.phtml';
    define('MOD_VER',	14);
    define('MOD_ADD',	15);
    define('MOD_EDIT',	16);
    define('MOD_DEL',	17);

    if(!in_array(MOD_VER, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom alignRight">
                                <div class="dt-buttons btn-group">
                                    <?php if(in_array(MOD_ADD, $permisos)) : ?>
                                        <button type="button "id="btnAdd" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-pers" tabindex="0" 
                                            aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                            data-target="#frm-pers">
                                            <i class="fas fa-plus"></i>&nbsp;&nbsp;<span>Agregar</span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <div class="card-datatable table-responsive pt-0">
                            <table id="tbl-cliente" class="table">
                                <thead class="table-light">
                                    <tr class="text-center">
                                        <th>No. Cliente</th>
                                        <th>Nombre</th>
                                        <th>Apellidos</th>
                                        <th>Correo</th>
                                        <th>Teléfono</th>
                                        <th>Descuento</th>
                                        <th>Saldo Disponible</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>

                        <div class="modal modal-slide-in fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-cliente" >
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title text-uppercase"></h4>
                                    </div>
                                    <div class="modal-body flex-grow-1 form-horizontal">
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-nombre">Nombre</label>
                                            <input type="text" class="form-control" id="cli-nombre"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-apellidos">Apellidos</label>
                                            <input type="text" id="cli-apellidos" class="form-control"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-correo">Email</label>
                                            <input type="text" id="cli-correo" class="form-control email-inputmask"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-telefono">Teléfono</label>
                                            <input type="text" id="cli-telefono" class="form-control phone-inputmask"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-descuento">Descuento</label>
                                            <div class="input-group">
                                                <input type="number" class="form-control" id="cli-descuento" placeholder="Descuento en porcentaje">
                                                <div class="input-group-text">
                                                    <span>%</span>
                                                </div>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="mt-1 text-center">
                                            <h5>Datos Fiscales</h5>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-rfc">RFC</label>
                                            <input type="text" id="cli-rfc" class="form-control"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-regimen_fiscal">Régimen Fiscal</label>
                                            <select class="form-control" id="cli-regimen_fiscal"></select>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-razon_social">Razón Social</label>
                                            <input type="text" id="cli-razon_social" class="form-control"/>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="cli-codigo_postal">Código Postal Fiscal</label>
                                            <input type="text" id="cli-codigo_postal" class="form-control"/>
                                        </div>
                                        <hr>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="buttonsEnd">
                                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-success mb-1 data-submit" id="btnSave">Guardar</button>
                                            <input type="hidden" id="cliente_id" value="0">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <!--Modal para eliminar a un usuario, solicita motivo de la baja y observaciones -->
                        <div class="modal modal-slide-in modal-danger fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-del">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title text-uppercase">eliminar cliente</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de eliminar al cliente <strong></strong>?
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="buttonsEnd">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-danger me-1" id="btnEliminar">Eliminar</button>
                                            <input  type="hidden" id="suc_id_del" value="0">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para eliminar a un usuario -->

                        <!--Modal para activar a un usuario, solicita confirmación para activar al usuario -->
                        <div class="modal modal-slide-in modal-success fade" id="frm-activar-user">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title" id="exampleModalLabel">Activar Usuario</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de cambiar el estatus de <strong></strong> a activo?
                                        </div><hr><br><br>
                                        <div class="buttonsFrmUser">
                                            <input  type="hidden" id="id_user_activar" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-success me-1" id="btnActivar">Activar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para activar a un usuario -->
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml'; ?>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
    <script src="<?= URL_ROOT ?>/app-assets/js/mask.init.js"></script>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/';

            getItems('tbl-cliente')

            <?php if(in_array(MOD_ADD, $permisos)) :  ?>
                $('#btnAdd').click(function(){
                    clear()
                    regimen()
                    $('#frm-cliente h4').html('agregar cliente')
                    $('#frm-cliente').modal('show')
                })

                $('#btnSave').click(function(){
                    id = $('#cliente_id').val();
                    data = {};
                    $.each($('#frm-cliente input'), function(index, elem) {
                        ide = $(elem).attr('id').replace('cli-','')
                        data[ide] = $.trim($(elem).val())
                    });
                    data['telefono'] = data['telefono'].replace('(','').replace(')','').replace(' ','').replace('-','')
                    data['regimen_fiscal'] = $('#cli-regimen_fiscal').val()
                    console.log(data)
                    if(data['nombre'] == ''){
                        error('cli-nombre', 'Este campo es obligatorio')
                    }else if(data['nombre'].length < 4){
                        error('cli-nombre', 'El nombre debe contener al menos 4 caracteres')
                    }else if(data['rfc'] == ''){
                        error('cli-rfc', 'Debe agregar el RFC')
                    }else if(data['rfc'].length < 12){
                        error('cli-rfc', 'El RFC debe contener al menos 12 caracteres')
                    }else if(data['regimen_fiscal'] == 0 ||  data['regimen_fiscal'] == null){
                        error('cli-regimen_fiscal', 'Debe seleccionar una opción')
                    }else if(data['razon_social'] == ''){
                        error('cli-razon_social', 'Este campo es obligatorio')
                    }else if(data['codigo_postal'] == ''){
                        error('cli-codigo_postal', 'Este campo es obligatorio')
                    }else{
                        if(id == 0){
                            $.post(apiUrl+'cliente/add/', data, function(resp){
                                if(resp.response){
                                    toastr["success"]("¡Listo!", "Se ha agregado un nuevo cliente.")
                                    getItems('tbl-cliente')
                                    $('#frm-cliente').modal('hide')
                                }else{
                                    toastr["error"]("¡Ocurrió un problema!", "No pudimos agregar al cliente.")
                                }
                            }, 'json')
                        }else{
                            $.post(apiUrl+'cliente/edit/'+id, data, function(resp){
                                if(resp.response){
                                    toastr["success"]("¡Listo!", "Se editó la información del cliente.")
                                    getItems('tbl-cliente')
                                    $('#frm-cliente').modal('hide')
                                }else if(resp.code){
                                    toastr["info"]("No hay cambios!", resp.msg); 
                                }else{
                                    toastr["error"]("¡Ocurrió un problema!", "No pudimos editar la información del cliente.")
                                }
                            }, 'json')
                        }
                    }
                })
            <?php endif; ?>

            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                $('#tbl-cliente').on('click', '#btnEdit', function(){
                    $('#frm-cliente h4').html('editar cliente')
                    id = $(this).data('id')
                    $('#cliente_id').val(id)
                    $.get(apiUrl+'cliente/get/'+id, function(data){
                        $.each(data.result, function(index, elem){
                            $('#cli-'+index).val(elem)
                        })
                    regimen(data.result.regimen_fiscal)
                    },'json')
                    $('#frm-cliente').modal('show')
                })
            <?php endif; ?>

            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                $('#tbl-cliente').on('click', '#btnDel', function(){
                    id = $(this).data('id')
                    $('#frm-cliente h5').html('<b>eliminar cliente</b>')
                    $('#frm-del strong').html($(this).data('name'))
                    $('#suc_id_del').val(id)
                    $('#frm-del').modal('show')
                })

                $('#btnEliminar').click(function(){
                    id = $('#suc_id_del').val()
                    $.post(apiUrl+'cliente/del/'+id, function(resp){
                        if(resp.response){
                            toastr["success"]("¡Listo!", "Se eliminó al cliente.")
                            getItems('tbl-cliente')
                            $('#frm-del').modal('hide')
                        }else{
                            toastr["error"]("¡Ocurrió un problema!", "No pudimos eliminar al cliente.")
                        }
                    },'json')
                })
            <?php endif; ?>

            function clear(){
                $.each($('#frm-cliente input'), function(index, elem){
                    ide = $(elem).attr('id')
                    $('#'+ide).val('')
                })
                $('#cliente_id').val(0)
            }

            function regimen(val=0){
                $('#cli-regimen_fiscal').empty()
                $.get(apiUrl+'cliente/regimen', function(resp){
                    $('#cli-regimen_fiscal').append('<option value="0" selected disabled>Seleccione una opción</option>')
                    $.each(resp, function(index, item){
                        $('#cli-regimen_fiscal').append('<option value="'+item.id+'">'+item.clave+' '+item.descripcion+'</option>')
                    })
                    $('#cli-regimen_fiscal').val(val)
                },'json')
            }

            function getItems(tbl){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable()
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(){
                if($('#tbl-cliente').length){
                    $('#tbl-cliente').DataTable({
                        ajax:{
                            url: apiUrl+'cliente/getAllDataTable',
                            type: 'GET',
                        },
                        columns: [
                            {data: 'id'},
                            {data: 'nombre'},
                            {data: 'apellidos'},
                            {data: 'correo'},
                            {data: 'telefono'},
                            {data: 'descuento'},
                            {data: 'saldo'},
                            {data: ''}
                        ],
                        columnDefs: [
                            {
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['id']
                                    mostrar = full['saldo'].replace('$ ', '') == 0.00 ? '' : 'hidden'
                                    return (
                                        '<div class="text-center">' +
                                            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                                                '<button type="button" id="btnEdit" class="btn btn-outline-new-info btn-sm btnEdit" data-id="'+id+'" data-toggle="tooltip" title="Editar" style="margin-right:4px;">'+
                                                    feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                                                '<button type="button" id="btnDel" class="btn btn-outline-danger btn-sm '+mostrar+'" data-id="'+id+'" data-name="'+full['nombre']+' '+full['apellidos']+'" data-toggle="tooltip" title="Eliminar" style="margin-right:4px;">'+
                                                    feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>' +
                                            <?php endif; ?>
                                        '</div>'
                                    );
                                }
                            },
                        ],
                        order: [[0, 'asc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'../spanish.json'
                        },
                    });
                }
            }

        });
    </script>
</html>