<?php 
	include 'header.phtml';
?>
<link rel="stylesheet" type="text/css" href="<?=URL_ROOT?>/app-assets/plugin/typeahead.js-master/dist/typehead-min.css" >
  <div class="app-content content ">
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body"> 
                <div class="container-fluid">
                    <div class="container-venta">
                        <div class="w-100 card">
                            <div class="card-header-venta fw-bolder fs-5 text-uppercase" data-bs-toggle="collapse" href="#cliente" role="button" aria-expanded="true" aria-controls="cliente" style="background-color: darkgray; color:white;"><span><i class="fas fa-caret-down ms-1 me-1"></i>&nbsp;Cliente</span></div>
                            <div class="card-body" id="cliente">
                                <div class="d-flex">
                                        <div class="col-3 text-center">
                                            <label class="col-6 form-label fw-bolder fs-5" for="buscador">Nombre del cliente</label>
                                        </div>
                                        <div class="col-6">
                                            <input type="text" id="buscador" class="form-control" placeholder="Público en General">
                                            <input type="hidden" id="cot_cliente_id" value="1">
                                        </div>
                                    <input type="hidden" id="cotizacion_id" value="0">
                                </div>
                            </div>
                        </div>
                        <div class="d-flex separar">
                            <div class="col-7 card shadow-lg">
                                <div class="card-header-venta fw-bolder fs-5 text-uppercase" style="background-color: darkgray; color:white;">productos</div>
                                <div class="card-body">
                                    <div class="form-group row d-flex">
                                        <div class="col-8 busqueda hidden">
                                            <div class="row">
                                                <label class="col-4 label-control text-end" for="bus">Buscar</label>
                                                <div class="col-8">
                                                    <input class="form-control input-sm" id="bus" placeholder="Buscar por clave o descripción"></input>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-4 busqueda hidden">
                                            <div class="row" style="justify-content: end;">
                                                <label class="col-6 label-control text-end" for="cuantos">Mostrar</label>
                                                <div class="col-6">
                                                    <select class="form-control" id="cuantos"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="w-100 d-flex">
                                        <table id="tbl-prods" class="table table-hover table-striped m-0 w-100 table-sm">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>venta</th>
                                                    <th>Stock</th>
                                                    <th>Clave</th>
                                                    <th>Descripción</th>
                                                    <th>Medida</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="col-5 card shadow-lg" style="width: calc(41.333% - 1rem);">
                                <div class="card-header-venta fw-bolder fs-5 text-uppercase" style="background-color: darkgray; color:white;">rangos de precios</div>
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div>
                                            <center><h5 class="name_prod"></h5></center><br>
                                            <table id="tbl-rangos_precios" class="table">
                                                <thead class="table-light">
                                                    <tr class="text-center">
                                                        <th>Tipo</th>
                                                        <th>Hasta</th>
                                                        <th>Precio</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>Menudeo</td>
                                                        <td><input type="text" class="form-control text-end deshabilitado" id="precio-menudeo" placeholder="0" readonly></td>
                                                        <td>
                                                            <div class="input-group">
                                                                <div class="input-group-text">
                                                                    <small>$</small>
                                                                </div>
                                                                <input type="text" class="form-control text-end deshabilitado" id="precio-precio_menudeo" placeholder="0.00" readonly>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>Medio mayoreo</td>
                                                        <td><input type="text" class="form-control text-end deshabilitado" id="precio-medio" placeholder="0" readonly></td>
                                                        <td>
                                                            <div class="input-group">
                                                                <div class="input-group-text">
                                                                    <small>$</small>
                                                                </div>
                                                                <input type="text" class="form-control text-end deshabilitado" id="precio-precio_medio" placeholder="0.00" readonly>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>Mayoreo</td>
                                                        <td><input type="text" class="form-control text-end deshabilitado" id="precio-mayoreo" placeholder="0" readonly></td>
                                                        <td>
                                                            <div class="input-group">
                                                                <div class="input-group-text">
                                                                    <small>$</small>
                                                                </div>
                                                                <input type="text" class="form-control text-end deshabilitado" id="precio-precio_mayoreo" placeholder="0.00" readonly>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>Distribuidor</td>
                                                        <td><input type="text" class="form-control text-end deshabilitado" id="precio-distribuidor" placeholder="0" readonly></td>
                                                        <td>
                                                            <div class="input-group">
                                                                <div class="input-group-text">
                                                                    <small>$</small>
                                                                </div>
                                                                <input type="text" class="form-control text-end deshabilitado" id="precio-precio_distribuidor" placeholder="0.00" readonly>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="w-100 card">
                            <div class="card-header-venta fw-bolder fs-5 text-uppercase" style="background-color: darkgray; color:white;">productos agregados</div>
                            <div class="card-body">
                                <table id="tbl-detalles" class="table table-hover table-striped m-0 w-100 mw-100 table-sm">
                                    <thead>
                                        <tr>
                                            <th class="text-start" width="10%">Cantidad</th>
                                            <th class="text-start" width="45%">Concepto</th>
                                            <th width="15%">P. Unitario</th>
                                            <th width="15%">Total</th>
                                            <th width="15%">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <tr class="nodata">
                                        <td colspan="9" class="text-center p-10 nodata">No se han agregado productos a la cotización</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="d-flex separar">
                            <div class="col-8 card">
                                <div class="form-group row m-1">
                                    <label class="form-label fw-bolder fs-5" for="cotizacion-comentarios">Comentarios</label><br>
                                    <textarea name="" id="cotizacion-comentarios" ></textarea>
                                </div>
                            </div>
                            <div class="col-4 card" style="width: calc(33.333% - 1rem);">
                                <div class="form-group row m-1">
                                    <div class="mb-1">
                                        <label class="form-label fw-bolder fs-5" for="cotizacion-total">Total</label>
                                        <div class="input-group">
                                            <div class="input-group-text">
                                                <span><i class="fas fa-dollar-sign"></i></span>
                                            </div>
                                            <input type="text" class="form-control text-end" id="cotizacion-total" placeholder="0.00" readonly>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="buttonsEnd">
                            <button type="button" class="btn btn-outline-secondary mb-1" id="btnCancel">Cancelar</button>
                            <button type="button" class="btn btn-new-info mb-1 data-submit" id="btnSave">Guardar</button>
                            <input type="hidden" id="cotizacion_id" value="0">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
  include 'footer.phtml';
?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

<script>
    $(function(){
        var apiUrl = '<?= URL_ROOT ?>/',
            aplicar = 0,
            desc_cli = 0,
            tipo = 1;

        <?php if(!$nueva) : ?> $('.title h2').html('Cotización '+'<?= $folio ?>')
        <?php else : ?> $('.title h2').html('Cotización')
        <?php endif; ?>

        let findClientes = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: `${apiUrl}/cliente/getBy/%QUERY`,
                wildcard: '%QUERY'
            }
        });

        $('#buscador').typeahead(
            {hint: true, highlight: true, minLength: 2}, 
            {display: 'cliente', source: findClientes}
        );
        
        $('#buscador').bind('typeahead:select', function(ev, suggestion) {
            let cliente_id = suggestion.id;
            if($.isNumeric(cliente_id) && cliente_id > 0){
                $('#buscador').val(suggestion.cliente);
                $('#cot_cliente_id').val(cliente_id).trigger('change');
            }
        });

        getItems('tbl-prods')

        <?php if($nueva) : ?>
            $('#cot_cliente_id').val(1)
        <?php else : ?>
            $('#buscador').val('<?= $cotizacion->cliente ?>').attr('disabled', true).prop('disabled', true).addClass('deshabilitado');
            $('#cot_cliente_id').val(<?= $cotizacion->cliente_id ?>)
            setTimeout(() => {
                $('#cot_cliente_id').trigger('change')
            }, 2000);
        <?php endif; ?>

        $('#btnCancel').click(function(e){
            e.preventDefault()
            $.blockUI()
            <?php if($nueva) : ?> 
                swal({
                    title: "SALIR",
                    text: "Se perderán todos los datos de la cotización</br>¿Qué desea hacer?",
                    type: "warning",
                    html: true,
                    showCancelButton: true,
                    cancelButtonText: "Permanecer",
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Salir",
                    closeOnConfirm: true 
                }, function(respuesta) {
                    if(respuesta) {
                        window.location.href = '<?= URL_ROOT ?>/cotizaciones'
                    }
                    $.unblockUI();
                })
            <?php else : ?>
                $.post(apiUrl+'cotizacion/desbloquear/<?= $cotizacion_id ?>', function(resp){
                    if(resp.response){
                        window.location.href = '<?= URL_ROOT ?>/cotizaciones'
                    }else{
                        toastr['danger']('¡Ocurrió algo extraño!', 'Vuelve a intentarlo más tarde.')
                    }
                },'json')
            <?php endif; ?>
        })

        $('#cot_cliente_id').on('change', function(){
            $.blockUI()
            id = $(this).val()
            cargarCot()
            $.unblockUI()
        })

        $('#tbl-prods').on('click', '.btnAdd', function(e){
            e.preventDefault()
            $.blockUI()
            agregar = true
            prod_id = $(this).data('id')
            es_kilo = $(this).data('kilo')
            tr = $(this).closest('tr')
            clave = $(tr).find('td:eq(1)').text()
            desc = $(tr).find('td:eq(2)').text()
            concepto = '('+clave+') '+desc;
            stock = $(tr).find('td:eq(0)').text()
            if($('#tbl-detalles tbody tr').length != 0) {
                $('.nodata').remove()
                $.each($('#tbl-detalles tbody tr'), function(index, tr){
                    if($(tr).data('producto_id') == prod_id){
                        toastr['info']('El producto ya está agregado en la cotización, modifique la cantidad')
                        agregar = false
                        $.unblockUI()
                    }
                })
            }else{
                $('#tbl-detalles tbody').append('<tr class="nodata"><td colspan="9" class="text-center p-10 nodata">No se han agregado productos a la cotización</td></tr>')
            }
           
            if(agregar){
                $.get(apiUrl+'producto/getRangos/'+prod_id, function(resp){
                    $('.name_prod').html('<b>'+concepto+'</b>')
                    $.each(resp, function(index, item){
                        $('#precio-'+index).val(item).attr('disabled', true).prop('disabled', 'disabled')
                    })
                    mayoreo = resp.mayoreo != null ? resp.mayoreo : 0
                    $('#precio-distribuidor').val(parseInt(mayoreo)+1)
                    data = {
                        'detalle_id': '', 
                        'producto_id': prod_id, 
                        'cantidad': '1.0', 
                        'clave': clave, 
                        'desc': desc, 
                        'concepto': concepto, 
                        'precio': resp.precio_menudeo, 
                        'total': parseFloat(1*resp.precio_menudeo).toFixed(2), 
                        'es_kilo': 1,
                        'stock': '',
                    }
                    <?php if(!$nueva) : ?>
                        data['cotizacion_id'] = '<?= $cotizacion_id ?>'
                        data['importe'] = parseFloat(1*resp.precio_menudeo).toFixed(2)
                        $.post(apiUrl+'coti_detalle/add/', data, function(res){
                            if(res.response){
                                data['detalle_id'] = res.result
                                addDetalle(data)
                            }
                        },'json')
                    <?php else : ?>        
                        addDetalle(data)
                    <?php endif; ?>
                    getTotales() 
                    $.unblockUI()
                },'json')
            }
        })

        $('#tbl-detalles').on('change', '.cant', function(){
            $.blockUI()
            elem = $(this)
            cantidad = parseFloat($(elem).val()).toFixed(1)
            tr = $(elem).closest('tr')
            prod_id = $(tr).data('producto_id')
            detalle_id = $(tr).data('detalle_id')
            clave = $(tr).data('clave')
            stock = $(tr).data('stock')
            kilo = $(tr).data('kilo')
            if(cantidad < 1){
                toastr["error"]("¡Error!", "No se puede cotizar menos de 1 pieza")
                $(elem).val(1)
                $.unblockUI()
            }
            <?php if($nueva) : ?>
                $.get(apiUrl+'producto/getPrecioByCant/'+prod_id+'/'+cantidad, function(resp){
                    let precio = resp != null ? parseFloat(resp).toFixed(2) : parseFloat(0).toFixed(2) 
                    let total = parseFloat(precio*cantidad).toFixed(2)
                    $(tr).find('.precio').html('$ '+precio)
                    $(tr).find('.total').html('$ '+total)
                    getTotales()
                },'json')
            <?php else : ?>
                if(detalle_id != ''){
                    $.get(apiUrl+'producto/getPrecioByCant/'+prod_id+'/'+cantidad, function(resp){
                        let precio = resp != null ? parseFloat(resp).toFixed(2) : parseFloat(0).toFixed(2) 
                        let total = parseFloat(precio*cantidad).toFixed(2)
                        $(tr).find('.precio').html('$ '+precio)
                        $(tr).find('.total').html('$ '+total)
                        getTotales()
                        data = {'cantidad': cantidad, 'precio': precio, 'importe': total, 'descuento': 0, 'total': total}
                        $.post(apiUrl+'coti_detalle/edit/'+detalle_id, data, function(resp){
                            if(!resp.response){
                                toastr["error"]("¡Ocurrió un error!", 'Vuelva a intentarlo más tarde')
                                $(elem).val(1).trigger('change')
                                $.unblockUI()
                            }else{
                                elem.val(parseFloat(cantidad).toFixed(1))
                            }
                        })
                    },'json')
                }
            <?php endif; ?>
        })

        $('#tbl-detalles').on('click', '.btnDelDet', function(e){
            e.preventDefault()
            tr = $(this).parents('tr')
            <?php if($nueva) : ?>
                $(tr).remove()
                getTotales()
            <?php else : ?>
                det_id = $(tr).data('detalle_id')
                $.post(apiUrl+'coti_detalle/del/'+det_id, function(resp){
                    if(resp.response){
                        $(tr).remove() 
                        toastr['success']('¡Hecho!', 'Producto eliminado de la cotización')
                        if($('#tbl-detalles tbody tr').length == 0){
                            $('#tbl-detalles tbody').append('<tr class="nodata"><td colspan="9" class="text-center p-10 nodata">No se han agregado productos a la cotización</td></tr>')
                        }
                    }else{
                        toastr['error']('¡Error!', 'No pudimos eliminar el producto de la cotización')
                    }
                    getTotales()
                },'json')
            <?php endif; ?>
        })

        $('#btnSave').click(function(e){
            e.preventDefault()
            btn = $(this)
            btn.attr('disabled', true).prop('disabled', true)
            guardar()
        })

        $('#tbl-detalles').on('click', '.btnConcepto', function(e){
            e.preventDefault()
            tr = $(this).closest('tr')
            prod_id = tr.data('producto_id')
            concepto = $(this).text()
            $.get(apiUrl+'producto/getRangos/'+prod_id, function(resp){
                $('.name_prod').html('<b>'+concepto+'</b>')
                $.each(resp, function(index, item){
                    $('#precio-'+index).val(item).attr('disabled', true).prop('disabled', 'disabled')
                })
                mayoreo = resp.mayoreo != null ? resp.mayoreo : 0
                $('#precio-distribuidor').val(parseInt(mayoreo)+1)
            },'json')
        })

        function getItems(tbl){
            cleanTable(tbl)
            $('#'+tbl+' tbody').empty()
            createTable(tbl)
        }

        function cargarCot(){
            <?php if(!$nueva) : ?> 
                <?php foreach($detalles as $detalle) : ?>
                    detalle = {
                        'detalle_id': '<?= $detalle->id ?>',
                        'producto_id': '<?= $detalle->producto_id ?>',
                        'es_kilo': '<?= $detalle->es_kilo ?>',
                        'precio': '<?= $detalle->precio ?>',
                        'cantidad': '<?= $detalle->cantidad ?>',
                        'concepto': '<?= $detalle->concepto ?>',
                        'total': '<?= $detalle->total ?>',
                        'stock': '<?= $detalle->stock ?>',
                        'clave': '<?= $detalle->clave ?>',
                    }
                    addDetalle(detalle, 1)
                <?php endforeach; ?>
                $('#cotizacion-comentarios').val('<?= $cotizacion->comentarios ?>')
            <?php endif; ?>
        }

        function addDetalle(data, tipo=0){
            precio = data.precio == null ? parseFloat(0).toFixed(2) : data.precio  
            container = $('#tbl-detalles tbody')
            $('#tbl-detalles tbody .nodata').remove();
            tr = $('<tr class="detalle" data-detalle_id="'+data.detalle_id+'" data-producto_id="'+data.producto_id+'" data-clave="'+data.clave+'" data-stock="'+data.stock+'" data-kilo="'+data.es_kilo+'"></tr>')
            tr.append('<td class="text-start cotizacion-cantidad" width="10%"><input type="text" class="form-control text-center cant" value="'+data.cantidad+'"></td>')
            tr.append('<td width="45%"><button type="button" class="btn btn-light btnConcepto">'+data.concepto+'</button></td>')
            tr.append('<td class="text-center precio" width="15%">$ '+precio+'</td>')
            tr.append('<td class="text-center total" width="15%">$ '+data.total+'</td>')
            td = $('<td class="text-center" width="15%"></td>').appendTo(tr)

            td.append('<button type="button" class="btn btn-outline-danger btn-sm btnDelDet"><i class="fas fa-trash" data-toogle="tooltip" title="Eliminar"></i></button>')
            container.append(tr)
            getTotales()
            $.unblockUI()
        }

        function getTotales(){
            $.blockUI()
            subtotal = 0;
            $.each($('#tbl-detalles tbody tr.detalle'), function(index, tr){
                val = parseFloat($(tr).find('.total').text().replace('$', ''))
                subtotal += val
            })
            $('#cotizacion-total').val(parseFloat(subtotal).toFixed(2))
            $.unblockUI()
        }

        function guardar(){
            $.blockUI()
            data = {
                cliente_id: $('#cot_cliente_id').val(),
                total: $('#cotizacion-total').val(),
                comentarios: $.trim($('#cotizacion-comentarios').val()),
            }
            data.detalles = []
            $.each($('#tbl-detalles tbody tr'), function(index, tr){
                if($(tr).is(':visible') && !$(tr).hasClass('nodata')){
                    detalle = {
                        'clave': $(tr).data('clave'), 
                        'producto_id': $(tr).data('producto_id'), 
                        'cantidad': $(tr).find('.cant').val(),
                        'precio': $(tr).find('.precio').text().replace('$', '').replace(' ', '')
                    }
                    data.detalles.push(detalle)
                }
            })
        
            if(data.detalles.length == 0){
                toastr['warning']('¡Verifique la información!', 'Debe agregar al menos un producto a la cotización')
                btn.attr('disabled', false).prop('disabled', false)
                $.unblockUI()
            }else{
                <?php if($nueva) : ?>
                    $.post(apiUrl+'cotizacion/add/', data, function(resp){
                        if(resp.response){
                            toastr['success']('¡Cotización realizada!', 'Cotización realizada con éxito')
                            ticket($.md5(resp.result.toString()))
                            window.location.href = '<?= URL_ROOT ?>/cotizaciones'
                        }else{
                            toastr['error']('¡Error!', resp.message)
                        }
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    },'json')
                <?php else : ?>
                    cotizacion_id = '<?= $cotizacion_id ?>'
                    $.post(apiUrl+'cotizacion/edit/'+cotizacion_id, data, function(resp){
                        if(resp.response){
                            ticket($.md5(cotizacion_id.toString()))
                            window.location.href = '<?= URL_ROOT ?>/cotizaciones'
                        }
                    })
                <?php endif; ?>
            }
        }

        function ticket(id){
            let contador = 0;
            while (contador < 2) {
                var mywindow = window.open('<?= URL_ROOT ?>/ticket/cotizacion/'+id);
                var is_chrome = Boolean(mywindow.chrome);
    
                if (is_chrome) {
                    setTimeout(function() {
                        mywindow.document.close();
                        mywindow.focus();
                        mywindow.print();
                        mywindow.close();
                    }, 250);
                } else {
                    mywindow.document.close();
                    mywindow.focus();
                    mywindow.print();
                    mywindow.close();
                }
                contador++;
                return true;
            }
        }

        function cleanTable(tbl){
            if($.fn.dataTable.isDataTable('#'+tbl)){
                table = $('#'+tbl).DataTable()
                table.destroy()
            }
        }

        var temporal = null;
        function evaluar(time) {
            setTimeout(() => {
                if(time == temporal) {
                    $("#tbl-prods_filter label input").val($.trim($('#bus').val())).trigger('keyup');
                }
            }, 1000);
        }

        function createTable(tbl){
            if($('#'+tbl).length){
                $('#'+tbl).DataTable({
                    ajax:{
                        url: apiUrl+'producto/getAllProdsVenta',
                        type: 'GET',
                    },
                    columns: [
                        {data: 'venta'},
                        {data: 'stock'},
                        {data: 'clave'},
                        {data: 'descripcion'},
                        {data: 'medida'},
                        {data: ''}
                    ],
                    columnDefs: [
                        {
                            targets: 1,
                            render: function (data, type, full, meta) {
                            var salida =
                                '<div class="d-flex flex-column text-center">' +
                                    full['stock'] +
                                '</div>';
                                return salida;
                            }
                        },
                        {
                            targets: -1,
                            title: 'Acciones',
                            orderable: false,
                            render: function (data, type, full, meta) {
                                id = full['data_id']
                                return (
                                    '<div class="text-center">'+
                                        '<button type="button" class="btn btn-success btn-sm btnAdd" data-id="'+id+'" data-kilo="'+full['es_kilo']+'" data-toggle="tooltip" title="Agregar" style="margin-right:4px;">'+ 
                                            feather.icons['shopping-cart'].toSvg({ class: 'font-small-4 me-20' }) +
                                        '</button>'+
                                    '</div>'
                                );
                            }
                        },
                        {
                            visible: false, targets: [0]
                        }
                    ],
                    order: [[0, 'desc']], 
                    dom:
                        '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                        '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                        '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                        '>t' +
                        '<"d-flex justify-content-between mx-2 row mb-1"' +
                        '<"col-sm-12 col-md-6"i>' +
                        '<"col-sm-12 col-md-6"p>' +
                        '>',
                    language: {
                        url:'<?= URL_ROOT ?>/spanish.json'
                    },
                    initComplete: function () {
                        $('#cuantos').on('change', function () {
                            $('#tbl-prods').DataTable().page.len( $(this).val() ).draw();
                        });
                        $('#tbl-prods_filter label:eq(0)').addClass('hidden');
                        $('#tbl-prods_length label:eq(0)').addClass('hidden');
                        $('.busqueda').removeClass('hidden');
                    }
                })

                let intervaloBusqueda = null;
                $(document).on('keyup', '#bus',  function(e){
                    temporal = moment().format('x')+"-"+Math.random();
                    evaluar(temporal);
                    clearInterval(intervaloBusqueda)
                    let valor = this.value;
                    intervaloBusqueda = setInterval(function() {
                        oTable = $('#tbl-prods').DataTable();
                        // Typing finished, now you can Do whatever after 2 sec
                        oTable.search( valor ).draw();

                        clearInterval(intervaloBusqueda)
                    }, 1000);
                });
            }
        }

    });
</script>
