<footer class="footer footer-static footer-light">
    <p class="clearfix mb-0"><span class="float-md-end d-none d-md-block">&copy; <?php echo SITE_NAME; ?> - <?php echo date('Y'); ?></span></p>
</footer>

<script src="<?= URL_ROOT ?>/app-assets/vendors/js/vendors.min.js"></script>
   
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/forms/select/select2.full.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/dataTables.bootstrap5.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/responsive.bootstrap5.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/jszip.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/pdfmake.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/vfs_fonts.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/buttons.html5.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/buttons.print.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/tables/datatable/dataTables.rowGroup.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/forms/validation/jquery.validate.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/forms/cleave/cleave.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/vendors/js/forms/cleave/addons/cleave-phone.us.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/plugin/toast/toastr.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/plugin/typeahead.js-master/dist/typeahead.bundle.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/js/lightbox.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/plugin/sweetalert/sweetalert.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/js/blockPage.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/plugin/md5/md5.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/plugin/session-timeout/jquery.sessionTimeout.min.js"></script>

<script src="<?= URL_ROOT ?>/app-assets/js/core/app-menu.min.js"></script>
<script src="<?= URL_ROOT ?>/app-assets/js/core/app.min.js"></script>

<script>
    $(window).on('load', function() {
        if (feather) {
            feather.replace({
                width: 14,
                height: 14
            });
        }
    });

    let sinDiacriticos = (function(){
    let de = 'ÁÃÀÄÂÉËÈÊÍÏÌÎÓÖÒÔÚÜÙÛÑÇáãàäâéëèêíïìîóöòôúüùûñ´ç°ª–”“†ÿŸÇ',
        a = 'AAAAAEEEEIIIIOOOOUUUUNCaaaaaeeeeiiiioooouuuun c        C',
        re = new RegExp('['+de+']' , 'ug');

    return texto =>
    texto.replace(
        re, 
        match => a.charAt(de.indexOf(match))
    );
    })();

    var apiUrl = '<?= URL_ROOT ?>/';

    toastr.options = {
        "closeButton": true,									
        "positionClass": "toast-top-right",
        "progressBar": true,
        "timeOut": "5000",
    }

    $.sessionTimeout({
        heading: 'h5',
        title: 'Sesión por expirar',
        message: 'Tu sesión está a punto de expirar. ¿Deseas seguir conectado?',
        countdownMessage: "Se cerrará en {timer} segundos.",
        warnAfter: 600000, 
        redirUrl: '<?= URL_ROOT ?>/usuario/logout', 
        redirAfter: 650000,
        keepAlive: true,
        keepAliveUrl: '<?= URL_ROOT ?>/usuario/renovarToken/', 
        logoutUrl: '<?= URL_ROOT ?>/usuario/logout', 
        keepAliveButton: 'Seguir conectado',
        logoutButton: 'Salir',
        ignoreUserActivity: false,
    });

    $('.btnSwitch').click(function(e){
        e.preventDefault();
        swal({
            title: 'Cambiar de usuario',
            text: 'Ingresa tu <strong class="font-weight-bold">Switch Code</strong><br><small>Se cerrará la sesión actual.</small>',
            type: "input",
            inputType: "password",
            inputPlaceholder: "Switch Code (4 digitos)",
            html: true,
            showCancelButton: true,   
            cancelButtonText: "Cancelar",
            confirmButtonText: "Cambiar",
            closeOnConfirm: false , 
        }, function(code) {
            if(code != ''){
                $.post(apiUrl+"usuario/switchUser", {code: code},
                    function (resp) {
                        if(resp.response){
                            swal({
                                type: "success",
                                title: "Bienvenido "+resp.username,   
                                text: resp.message,
                                showConfirmButton: false, 
                                timer: 4000
                            });
                            setTimeout(() => {
                                location.reload();
                            }, 3000);
                        }else{
                            swal({
                                type: "warning",
                                title: "Oops!",   
                                text: resp.message,   
                                timer: 4000
                            });
                        }
                    },
                    "json"
                );
            }
        });
    });

    prod_buscado = $('#producto_bus_id').val()
    prod_selected = 0

    $('.busPrecios').click(function(e){
        e.preventDefault()
        $('#tbl-precios_bus').addClass('hidden')
        var findProductos = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: apiUrl+'producto/getProdsBy?buscar=%QUERY',
                wildcard: '%QUERY'
            }
        })

        $('#producto_bus_name').typeahead(
            {hint: true, highlight: true, minLength: 2}, 
            {display: 'nombre', source: findProductos}
        )

        $('#producto_bus_name').bind('typeahead:select', function(ev, suggestion) {
            producto = suggestion.producto;
            prod_id = suggestion.id;

            if($.isNumeric(prod_id) && prod_id > 0){
                $('#producto_bus_name').val(producto);
                $('#producto_bus_id').val(prod_id);
                $('#tbl-precios_bus').removeClass('hidden')
                $.get(apiUrl+'producto/getRangos/'+prod_id, function(resp){
                    $.each(resp, function(index, item){
                        $('#bus-'+index).val(item)
                    })
                    mayoreo = resp.mayoreo != null ? resp.mayoreo : 0
                    $('#bus-distribuidor').val(parseInt(mayoreo)+1)
                })
            }
        })
        $('#producto_bus_name').focus().val('')
        $('#buscarPrecios').modal('show')
    })

    document.addEventListener ("keydown", function (e) {
        if(e.which === 27) {
            $('#buscarPrecios').modal('hide');
            $('#frm-datos').modal('hide');
            $('#frm-contrasena').modal('hide');
        }
    })

    $('#menuDatos').click(function(e){
        e.preventDefault();
        id = $.trim($('#usuario-id_actualizar').val());
        
        $.get(apiUrl+'usuario/get/'+id, function(resp){
            $.each(resp.result, function(index, val) { $('#usuario-'+index).val(val); });
        },'json')

        $('#frm-datos').modal('show');
    });

    $('#btnActualizar').on('click',function(){
        btn = $(this);
        btn.addClass('disabled');
        id = $('#usuario-id_actualizar').val()
        data = {};
        $.each($('#frm-datos input, #frm-datos select'), function(index, item){
            ide = $(item).attr('id').replace('usuario-','')
            data[ide] = $.trim($(item).val())
        })
        data['celular'] = data['celular'].replace('(','').replace(')','').replace(' ','').replace('-','')

        if(data.nombre.length == 0 || data.nombre.length < 3){
            error('usuario-nombre', 'El nombre debe contener al menos 3 caracteres')
            btn.removeClass('disabled');
        }else if(data.apellidos.length == 0 || data.apellidos.length < 3){
            error('usuario-apellidos', 'Este campo debe contener al menos 3 caracteres')
            btn.removeClass('disabled');
        }else if(data.email.length == 0 || data.email.length < 4){
            error('usuario-email', 'Debe ingresar un correo electrónico válido.')
            btn.removeClass('disabled');
        }else if(id == 0 && (data.celular.length == 0 || data.celular.length < 10)){
            error('usuario-celular', 'Debe ingresar un número de celular.')
            btn.removeClass('disabled');
        }else if(data.username.length == 0 || data.username.length < 3){
            error('usuario-username', 'Este campo debe contener al menos 3 caracteres, es el username con el que ingresará al sistema.')
            btn.removeClass('disabled');
        }else if(id == 0 && (data.contrasena.length == 0 || data.contrasena.length < 7)){
            error('usuario-contraseña', 'Debe ingresar una contraseña con más de 7 carácteres.')
            btn.removeClass('disabled');
        }else{
            $.post(apiUrl+'usuario/edit/1/'+id, data, function(resp){
                if(resp.response){
                    toastr["success"]("Listo!", 'Datos actualizados.<br>Su sesión se cerrará en 5 segundos, inicie sesión nuevamente.');
                    setTimeout(() => {
                        window.location.href = "<?= URL_ROOT ?>/usuario/logout"
                    }, 5000);
                    $('#frm-datos').modal('hide');
                }else{
                    if(resp == 'Debe seleccionar un tipo de usuario'){ toastr["warning"]("Verifique el tipo de usuario!", resp); }
                    else{ toastr["info"]("No hay cambios!", resp); }
                }
            btn.removeClass('disabled');
            },'json');
        }
    });

    $('#menuContrasena').click(function(e){
        $('#frm-contrasena').modal('show');
    });

    $('#btnChangePass').on('click',function(){
        btn = $(this);
        btn.addClass('disabled');
        id = $('#pers-id_actualizarC').val();

        data = {
            contrasena: $.trim($('#kypass1').val()),
            contrasenaNue: $.trim($('#kypass2').val()),
            contrasenaRep: $.trim($('#kypass3').val()),
        };

        if(data.contrasena.length == 0 || data.contrasena.length < 7){
            error('kypass1', 'Debe ingresar su contraseña actual, al menos 7 caracteres.')
            btn.removeClass('disabled');
        }else if(data.contrasenaNue.length == 0 || data.contrasenaNue.length < 7){
            error('kypass2', 'Debe ingresar una contraseña con al menos 7 carácteres.')
            btn.removeClass('disabled');
        }else if(data.contrasenaNue != data.contrasenaRep){
            error('kypass3', 'Debe ingresar la misma nueva contraseña.')
            btn.removeClass('disabled');
        }else{
            $.post(apiUrl+'password/cambiarContrasena/'+id, data, function(resp){
                if(resp.response){
                    toastr["success"]("Listo!", 'Contraseña actualizada.<br>Su sesión se cerrará en 5 segundos, inicie sesión nuevamente.');
                    setTimeout(() => {
                        window.location.href = "<?= URL_ROOT ?>/usuario/logout"
                    }, 5000);
                    $('#frm-contrasena').modal('hide');                   
                }else{  
                    toastr["error"]("Verifique la contraseña actual ingresada!", resp.message);
                    btn.removeClass('disabled');
                }
            },'json');
        }
    });

    function error(elem, msg){
        $error = $('<div class="invalid-feedback"></div>');
        $('#'+elem).addClass('is-invalid').focus();
        $error.html(msg)
        $('#'+elem).after($error);
        $error.show();

        setTimeout(() => {
            $('.invalid-feedback').remove();
            $('#'+elem).removeClass('is-invalid')
        }, 4000);
    }

</script>