<?php
    include 'core/defines.php';
    $id = $_SESSION['usuario_id'];
    $nombreEmp = $_SESSION['usuario']->nombre;

    define('MOD_CERRAR',    30);
    // define('MOD_BITACORA_ACCIONES',    30);

    $icono = '';
    // echo($vista);
    switch ($vista) {
        case 'Venta': $icono = 'fas fa-shopping-cart'; $vista = 'Venta'; break;
        case 'Segunda Venta': $icono = 'fas fa-cart-plus'; break;
        case 'Cotizaciones': $icono = 'fas fa-calculator'; break;
        case 'Cotización': $icono = 'fas fa-calculator'; break;
        case 'Usuarios': $icono = 'fas fa-user'; break;
        case 'Sucursales': $icono = 'fas fa-store'; break;
        case 'Productos': $icono = 'fas fa-boxes'; $vista = 'Inventario / Precios'; break;
        case 'Kardex': $icono = 'fas fa-list'; break;
        case 'Prod_entrada': $icono = 'fas fa-upload'; $vista = 'Entrada de Productos'; break;
        case 'Clientes': $icono = 'fas fa-handshake'; break;
        case 'Ventas': $icono = 'fas fa-file-invoice-dollar'; $vista = 'Ventas a Crédito'; break;
        case 'Ventas del día': $icono = 'fas fa-calendar-day'; $vista = 'Ventas del Día'; break;
        case 'Reporte de Ventas Por Periodo': $icono = 'fas fa-calendar-check'; break;
        case 'Reporte de Métodos de Pago': $icono = 'fas fa-money-check-alt'; break;
        case 'Reporte de Productos': $icono = 'fas fa-chart-pie'; break;
        case 'Inventario': $icono = 'fas fa-clipboard-list'; $vista = 'Inventario Físico'; break;
        case 'Clasificacion': $icono = 'fas fa-network-wired'; $vista = 'Clasificación'; break;
        case 'Bitácora de Acciones': $icono = 'fas fa-check-square'; break;
    }
?> 

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
        <meta name="description" content="">
        <meta name="author" content="">
        <title><?= $vista.' | '. SITE_NAME ?></title>
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/forms/select/select2.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/vendors.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/tables/datatable/dataTables.bootstrap5.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/tables/datatable/responsive.bootstrap5.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/tables/datatable/buttons.bootstrap5.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/vendors/css/tables/datatable/rowGroup.bootstrap5.min.css">

        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/bootstrap-extended.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/colors.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/components.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/themes/dark-layout.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/themes/bordered-layout.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/themes/semi-dark-layout.min.css">
     
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/core/menu/menu-types/vertical-menu.min.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/plugins/forms/form-validation.css">
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/fonts/font-awesome/css/font-awesome.css">
        <link rel="stylesheet" type="text/css" href="<?=URL_ROOT?>/app-assets/plugin/typeahead.js-master/dist/typehead-min.css" >

        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/assets/css/style.css">

        <link href="<?= URL_ROOT ?>/app-assets/plugin/toast/toastr.min.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/css/lightbox.min.css">

	    <link href="<?= URL_ROOT ?>/app-assets/plugin/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
    </head>

    <?php include 'sidebar.phtml'; ?>

    <body class="vertical-layout vertical-menu-modern  navbar-floating footer-static menu-expanded" data-open="click" data-menu="vertical-menu-modern" data-col="">

    <nav class="header-navbar navbar navbar-expand-lg align-items-center floating-nav navbar-light navbar-shadow container-fluid">
        <div class="navbar-container d-flex content">
            <div class="bookmark-wrapper d-flex align-items-center">
                <ul class="nav navbar-nav d-xl-none">
                    <li class="nav-item"><a class="nav-link menu-toggle" href="#"><i class="ficon" data-feather="menu"></i></a></li>
                </ul>
                <ul class="nav navbar-nav bookmark-icons">
                    &nbsp; <li class="nav-item d-none d-lg-block ">
                    <i class="<?= $icono?> titleIcon"></i>
                    </li> &nbsp; &nbsp; <!-- icono del módulo -->
                    <div class="user-nav d-sm-flex d-none title"> 
                    <?php if($vista == 'Venta' || $vista == 'Cotización') : ?>
                        <span class="name-vista fw-bolder"><h2></h2></span>
                    <?php else : ?>
                        <span class="name-vista fw-bolder"><h2><?= $vista ?></h2></span>
                    <?php endif; ?>
                    </div> <!-- nombre del módulo -->
                </ul>
            </div>
            <ul class="nav navbar-nav align-items-center ms-auto">
                <?php if($vista != 'Cotización') : ?>
                    <li class="me-1">
                        <a class="nav-link" href="<?= URL_ROOT ?>/cotizacion/cliente"><i class="fas fa-calculator nuevaCoti" data-toggle="tooltip" title="Cotización"></i></a>
                    </li>
                <?php endif; ?>
                <?php if($vista != 'Venta' && $vista != 'Segunda Venta') : ?>
                    <li class="me-1">
                        <a class="nav-link" href="<?= URL_ROOT ?>/venta/cliente"><i class="fas fa-shopping-cart nuevaVenta" data-toggle="tooltip" title="Nueva Venta"></i></a>
                    </li>
                <?php elseif($vista == 'Venta' && $vista != 'Segunda Venta') : ?>
                    <li class="me-1">
                        <a class="nav-link" href="<?= URL_ROOT ?>/segunda/venta" target="_blank"><i class="fas fa-cart-plus segundaVenta" data-toggle="tooltip" title="Segunda Venta"></i></a>
                    </li>
                <?php endif; ?>
                <li class="me-1">
                    <a class="nav-link"><i class="fas fa-search-dollar busPrecios" data-toggle="tooltip" title="Buscar Precios"></i></a>
                </li>
                <li class="nav-item dropdown dropdown-user">
                    <a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="user-nav d-sm-flex d-none">
                            <span class="user-name fw-bolder"><?= $nombreEmp ?></span>
                        </div>
                        <span class="avatar">
                        <?php if($_SESSION['foto']) : ?>
                            <img class="round" src="<?= URL_DATA ?>empleado/foto<?= $id ?>.jpg" alt="avatar" width="40" height="40">
                        <?php else : ?>
                            <img class="round" src="<?= URL_DATA ?>empleado/profile.png" alt="avatar" width="40" height="40">
                        <?php endif; ?>
                            <span class="avatar-status-online"></span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-user">
                        <a class="dropdown-item" id="menuDatos"><i class="me-50" data-feather="user"></i> Mis Datos</a>
                        <a class="dropdown-item" id="menuContrasena" ><i class="me-50" data-feather="key"></i> Contraseña</a>
                        <div class="dropdown-divider"></div><a class="dropdown-item" href="<?= URL_ROOT ?>/usuario/logout"><i class="me-50" data-feather="power"></i> Cerrar Sesión</a>
                        <?php if(in_array(MOD_CERRAR, $permisos)) : ?>
                            <div class="dropdown-divider"></div><a class="dropdown-item cerrarSuc" href="<?= URL_ROOT ?>/sucursal/cerrar"><i class="me-50" data-feather="slash"></i> Cerrar Sucursal</a>
                        <?php endif; ?>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <ul class="main-search-list-defaultlist-other-list d-none">
        <li class="auto-suggestion justify-content-between"><a class="d-flex align-items-center justify-content-between w-100 py-50">
        <div class="d-flex justify-content-start"><span class="me-75" data-feather="alert-circle"></span><span>No results found.</span></div></a></li>
    </ul>

    <div class="modal modal-slide-in fade" data-bs-keyboard="false" id="frm-datos" >
        <div class="modal-dialog">
            <form class="modal-content pt-0">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                <div class="modal-header mb-1">
                    <h4 class="modal-title text-uppercase">actualizar datos</h4>
                </div>
                <div class="modal-body flex-grow-1 form-horizontal">
                    <div class="mb-1 alignCenter">
                        <h5>Generales</h5>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-nombre">Nombre</label>
                        <input type="text" class="form-control" id="usuario-nombre"/>
                    </div>
                    <div class="mb-1"> 
                        <label class="form-label fw-bolder fs-5" for="usuario-apellidos">Apellidos</label>
                        <input type="text" id="usuario-apellidos" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-email">Email</label>
                        <input type="text" id="usuario-email" class="form-control email-inputmask"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-celular">Teléfono</label>
                        <input type="text" id="usuario-celular" class="form-control phone-inputmask"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-username">Username</label>
                        <input type="text" id="usuario-username" class="form-control" placeholder="Nombre de usuario con el que ingresará al sistema"/>
                    </div>
                    <hr>
                    <div class="mb-1 alignCenter">
                        <h5>Dirección</h5>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-calle">Calle</label>
                        <input type="text" id="usuario-calle" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-no_ext">No. Exterior</label>
                        <input type="text" id="usuario-no_ext" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-no_int">No. Interior</label>
                        <input type="text" id="usuario-no_int" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-colonia">Colonia</label>
                        <input type="text" id="usuario-colonia" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-municipio">Municipio</label>
                        <input type="text" id="usuario-municipio" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-estado">Estado</label>
                        <input type="text" id="usuario-estado" class="form-control"/>
                    </div>
                    <div class="mb-1">
                        <label class="form-label fw-bolder fs-5" for="usuario-codigo_postal">Código Postal</label>
                        <input type="text" id="usuario-codigo_postal" class="form-control"/>
                    </div> 
                </div>
                <div class="modal-footer">
                    <div class="buttonsEnd">
                        <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-success mb-1 data-submit" id="btnActualizar">Actualizar</button>
                        <input type="hidden" id="usuario-id_actualizar" value="<?= $id ?>">
                        <input type="hidden" id="usuario-sucursal_id">
                        <input type="hidden" id="usuario-usuario_tipo_id">
                        <input type="hidden" id="usuario-contrasena" value="">
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="modal modal-slide-in new-user-modal fade" data-bs-keyboard="false" id="frm-contrasena" >
        <div class="modal-dialog">
            <form class="add-new-user modal-content pt-0">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                <div class="modal-header mb-1">
                    <h4 class="modal-title text-uppercase">cambiar contraseña</h4>
                </div>
                <div class="modal-body flex-grow-1 form-horizontal">
                    <div class="mb-1 form-group row" id="UsuCon" > 
                        <label  for="kypass1" class="form-label fw-bold fs-5">Contraseña Actual</label>
                        <div class="mb-1 col-md-12"> 
                            <input id="kypass1" type="password" class="form-control input-sm" placeholder="Ingrese su contraseña actual" >
                        </div>
                    </div>
                    <div class="mb-1 form-group row" id="UsuConNue" > 
                        <label  for="kypass2" class="form-label fw-bold fs-5">Nueva Contraseña</label>
                        <div class="mb-1 col-md-12"> 
                            <input id="kypass2" type="password" class="form-control input-sm" minlength="7" placeholder="Ingrese su nueva contraseña">
                        </div>
                    </div>
                    <div class="mb-1 form-group row" id="UsuConNueRep" > 
                        <label  for="kypass3" class="form-label fw-bold fs-5">Repetir Contraseña</label>
                        <div class="mb-1 col-md-12"> 
                            <input id="kypass3" type="password" class="form-control input-sm" minlength="7" placeholder="Repetir nueva contraseña">
                        </div>
                    </div>
                    
                    <div class="modal-footer">
                        <div class="buttonsEnd">
                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-success mb-1 data-submit" id="btnChangePass">Actualizar</button>
                            <input type="hidden" id="pers-id_actualizarC" value="<?= $id ?>">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="buscarPrecios" >
        <div class="modal-dialog modal-lg">
            <form class="modal-content pt-0">
                <div class="modal-header mb-1">
                    <h4 class="modal-title text-uppercase">precios de producto</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body flex-grow-1 form-horizontal">    
                    <div class="form-group row mb-1">
                        <label class="col-sm-3 d-flex align-items-center justify-content-start form-label fs-5" for="producto_bus_name">Nombre del Producto</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control fs-5" id="producto_bus_name" placeholder="Buscar producto por nombre o código"></input>
                        </div>
                    </div>                                                
                    <div>
                        <table id="tbl-precios_bus" class="table">
                            <thead class="table-light">
                                <tr class="text-center">
                                    <th>Tipo</th>
                                    <th>Hasta</th>
                                    <th>Precio</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Menudeo</td>
                                    <td><input type="text" class="form-control text-end" id="bus-menudeo" placeholder="0"></td>
                                    <td>
                                        <div class="input-group">
                                            <div class="input-group-text">
                                                <small>$</small>
                                            </div>
                                            <input type="text" class="form-control text-end" id="bus-precio_menudeo" placeholder="0.00">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Medio mayoreo</td>
                                    <td><input type="text" class="form-control text-end" id="bus-medio" placeholder="0"></td>
                                    <td>
                                        <div class="input-group">
                                            <div class="input-group-text">
                                                <small>$</small>
                                            </div>
                                            <input type="text" class="form-control text-end" id="bus-precio_medio" placeholder="0.00">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Mayoreo</td>
                                    <td><input type="text" class="form-control text-end" id="bus-mayoreo" placeholder="0"></td>
                                    <td>
                                        <div class="input-group">
                                            <div class="input-group-text">
                                                <small>$</small>
                                            </div>
                                            <input type="text" class="form-control text-end" id="bus-precio_mayoreo" placeholder="0.00">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Distribuidor</td>
                                    <td><input type="text" class="form-control text-end" id="bus-distribuidor" placeholder="0"></td>
                                    <td>
                                        <div class="input-group">
                                            <div class="input-group-text">
                                                <small>$</small>
                                            </div>
                                            <input type="text" class="form-control text-end" id="bus-precio_distribuidor" placeholder="0.00">
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="buttonsEnd">
                        <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Salir</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

  </body>
</html>