<?php 
	include 'header.phtml';
    define('MOD_VER',	  20);

    if(!in_array(MOD_VER, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>
<link rel="stylesheet" type="text/css" href="<?=URL_ROOT?>/app-assets/plugin/typeahead.js-master/dist/typehead-min.css" >
<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom">
                                <div class="dt-buttons btn-group">
                                    <div class="col-sm-12 me-2">
                                        <!-- <label class="form-label fw-bolder fs-5" for="baja-fecha">Producto</label> -->
                                        <input type="text" id="busqueda" class="form-control" placeholder="Buscar producto por nombre o código">
                                    </div>
                                    <div class="col-sm me-2">
                                        <!-- <label class="form-label fw-bolder fs-5" for="desde">Desde</label> -->
                                        <input type="date" id="desde" class="form-control" data-toggle="tooltip" title="Desde" max="<?= date('Y-m-d')?>" value="<?= date('Y-m-d')?>">
                                    </div>
                                    <div class="col-sm me-2">
                                        <!-- <label class="form-label fw-bolder fs-5" for="hasta">Hasta</label> -->
                                        <input type="date" id="hasta" class="form-control" data-toggle="tooltip" title="Hasta" max="<?= date('Y-m-d')?>" value="<?= date('Y-m-d')?>">
                                    </div>
                                    <div class="col-sm-12">
                                        <button type="button" class="btn btn-s btn-success" id="btnBuscar"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                    <input type="hidden" id="producto_id" value="0">
                                </div>
                            </div>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl-kardex" class="table">
                                    <thead class="table-light">
                                        <tr class="text-center">
                                            <th>ID</th>
                                            <th>Fecha</th>
                                            <th width="25%">Folio</th>
                                            <th>Entrada</th>
                                            <th>Salida</th>
                                            <th>Existencia</th>
                                            <th width="15%">Usuario</th>
                                            <th>Notas</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml'; ?>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/';
            $('#busqueda').focus()

            var findProductos = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: apiUrl+'producto/getBy/%QUERY',
                    wildcard: '%QUERY'
                }
            })
    
            $('#busqueda').typeahead(
                {hint: true, highlight: true, minLength: 2}, 
                {display: 'nombre', source: findProductos}
            )

            $('#busqueda').bind('typeahead:select', function(ev, suggestion) {
                producto = suggestion.producto;
                prod_id = suggestion.id;

                if($.isNumeric(prod_id) && prod_id > 0){
                    $('#busqueda').val(producto);
                    $('#producto_id').val(prod_id);
                }
            })

            $('#btnBuscar').click(function(){
                id = $('#producto_id').val()
                if(id == 0){
                    error('busqueda', 'Debe buscar y seleccionar un producto')
                }else{
                    getItems('tbl-kardex')
                }
            })


            function getItems(tbl){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable()
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl){
                prod_id = $('#producto_id').val()
                desde = $('#desde').val()
                hasta = $('#hasta').val()
                if($('#tbl-kardex').length){
                    $('#tbl-kardex').DataTable({
                        ajax:{
                            url: apiUrl+'prod_stock/getAllDataTable/'+prod_id+'/'+desde+'/'+hasta,
                            type: 'GET',
                        },
                        columns: [
                            {data: 'id'},
                            {data: 'fecha'},
                            {data: 'folio'},
                            {data: 'entrada'},
                            {data: 'salida'},
                            {data: 'existencia'},
                            {data: 'usuario'},
                            {data: 'notas'}
                        ],
                        columnDefs: [
                            {
                                targets: 1,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column text-center">' +
                                            '<span >' +
                                                full['fecha'] +
                                            '</span>' +
                                            '<small class="emp_post text-muted">' +
                                            full['hora'] +
                                            '</small>' +
                                        '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 3,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column text-center">' +
                                        full['entrada'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 4,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column text-center">' +
                                        full['salida'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 5,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column text-center">' +
                                        full['existencia'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                visible: false, targets: [0]
                            }
                        ],
                        order: [[0, 'desc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'../spanish.json'
                        },
                        initComplete: function () {
                            $('#tbl-kardex_filter').addClass('hidden');
                        }
                    });
                }
            }

        });
    </script>
</html>