<?php 
	include 'header.phtml';
?>
  <div class="app-content content ">
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body"> 
                <div class="container-fluid">
                    <!-- <div class="row text-white text-center"> -->

                    <!-- <section class="row">
                        <div class="col-sm-12">
                            <div class="card-columns" id="search-container"> -->
                                <?php
                                    //foreach ($modulos as $modulo) {
                                ?>
                                        <!-- <article class="card col-2 text-center">
                                            <div class="card-header bg-dark text-white">
                                                <div class="row">
                                                    <div class="col">-->
                                                        
                                                    <!-- <div class="col-2 bg-dark border fs-3">
                                                       // <?= $modulo->nombre ?>
                                                    </div> -->
                                                    <!--</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </article> -->
                                <?php 
                                   // }
                                ?>
                        <!-- </div> -->
                            <!-- </div> -->
                        <!-- </div> -->
                    <!-- </section> -->
                </div>
            </div>
        </div>
    </div>
<?php
  include 'footer.phtml';
?>
