<?php 
	include 'header.phtml';
    define('MOD_VER',	    10);
    define('MOD_ADD',	    11);
    define('MOD_EDIT',	    12);
    define('MOD_DEL',	    13);
    define('MOD_CARGA_M',   18);
    define('MOD_MODIF_M',   19);
    define('MOD_PROD_SUC',  23);
    define('MOD_PROD_BAJA', 27);
    define('MOD_EXP_MIN',   37);

    if(!in_array(MOD_VER, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>

<link href="<?= URL_ROOT ?>/app-assets/plugin/dropzone-master/dist/dropzone.css" rel="stylesheet" type="text/css" />

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom alignRight">
                                <div class="dt-buttons btn-group">
                                    <?php if(in_array(MOD_ADD, $permisos)) :  ?>
                                        <button type="button "id="btnAdd" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-producto" tabindex="0" 
                                            aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                            data-target="#frm-producto">
                                            <i class="fas fa-plus"></i>&nbsp;&nbsp;<span>Agregar</span>
                                        </button>
                                    <?php endif; ?>
                                    <?php if(in_array(MOD_CARGA_M, $permisos)) :  ?>
                                        <button type="button "id="btnMasiva" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-masiva" tabindex="0" 
                                            aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                            data-target="#frm-masiva">
                                            <i class="fas fa-file"></i>&nbsp;&nbsp;<span>Carga Masiva</span>
                                        </button>
                                    <?php endif; ?>
                                    <?php if(in_array(MOD_MODIF_M, $permisos)) :  ?>
                                        <button type="button "id="btnModifPre" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-precios" tabindex="0" 
                                            aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                            data-target="#frm-precios">
                                            <i class="fas fa-dollar-sign"></i>&nbsp;&nbsp;<span>Modificación Precios</span>
                                        </button>
                                    <?php endif; ?>
                                    <?php if(in_array(MOD_EXP_MIN, $permisos)) : ?>
                                        <button type="button "id="btnExportar" class="btn btn-success buttonModal">
                                            <i class="fas fa-file-excel"></i>&nbsp;&nbsp;<span>Stock Mínimo</span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl-producto" class="table">
                                    <thead class="table-light">
                                        <tr class="text-center">
                                            <th>Clave</th>
                                            <th>Descripción</th>
                                            <th>Medida</th>
                                            <th>Código de barras</th>
                                            <th>Área</th>
                                            <th>Stock Mínimo</th>
                                            <th>Existencia</th>
                                            <th>En minimo</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-producto" >
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase"></h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                            <div class="mb-1 form-group row">
                                                <div class="col-sm-4 area">
                                                    <label class="form-label fw-bolder fs-5" for="prod-prod_area_id">Área</label>
                                                    <select class="form-control" id="prod-prod_area_id"></select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="categoria">Categoría *</label>
                                                    <select class="form-control" id="categoria">
                                                        <option value="0" selected disabled>Seleccione una opción</option>
                                                    </select>
                                                </div>
                                                <div class="col-sm-4 subcategoria hidden">
                                                    <label class="form-label fw-bolder fs-5" for="prod-prod_categoria_id">Subcategoria *</label>
                                                    <select class="form-control" id="prod-prod_categoria_id"></select>
                                                </div>
                                            </div>

                                            <div class="mb-1 mt-1 form-group row">
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-clave">Clave</label>
                                                    <input type="text" class="form-control" id="prod-clave">    
                                                </div>
                                                <div class="col-sm-8">
                                                    <label class="form-label fw-bolder fs-5" for="prod-descripcion">Descripción</label>
                                                    <input type="text" class="form-control" id="prod-descripcion">
                                                </div>
                                            </div>
                                            <div class="mb-1 mt-1 form-group row">
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-medida">Medida</label>
                                                    <input type="text" class="form-control" id="prod-medida">
                                                </div>
                                                <div class="col-sm-8">
                                                    <label class="form-label fw-bolder fs-5" for="codigo_barras">Código de Barras</label>
                                                    <div class="input-group">
                                                        <div class="input-group-text">
                                                            <span><i class="fas fa-barcode"></i></span>
                                                        </div>
                                                        <input type="text" class="form-control deshabilitado" id="codigo_barras" readonly>
                                                    </div>
                                                </div>                                                
                                            </div>
                                                    
                                            <div class="mb-1 mt-1 form-group row">
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-costo">Costo</label>
                                                    <div class="input-group">
                                                        <div class="input-group-text">
                                                            <span>$</span>
                                                        </div>
                                                        <input type="text" class="form-control text-end deshabilitado" id="prod-costo" placeholder="0.00" disabled>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-stock">Stock</label>
                                                    <input type="text" class="form-control text-end deshabilitado" id="prod-stock" placeholder="0" disabled>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-minimo">Stock Mínimo</label>
                                                    <input type="text" class="form-control text-end" id="prod-minimo" placeholder="0">
                                                </div>                            
                                            </div>

                                            <div class="mb-1 mt-1 form-group row">
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-prod_unidad_medida_id">Unidad de Medida</label>
                                                    <select class="form-control" id="prod-prod_unidad_medida_id"></select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-clave_sat">Clave SAT</label>
                                                    <input type="text" class="form-control" id="prod-clave_sat">
                                                </div>                            
                                            </div>
                                            <div class="mb-1 mt-1 form-group row">
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-cant_kilo">Venta por kilo <small>(Cantidad)</small></label> 
                                                    <div class="input-group mb-3">
                                                        <div class="input-group-text">
                                                            <input class="form-check-input mt-0" type="checkbox" data-toggle="tooltip" title="Si, se vende por kilo" id="kilo">
                                                        </div>
                                                        <input type="number" class="form-control deshabilitado" id="prod-cant_kilo" placeholder="Cantidad" disabled>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label class="form-label fw-bolder fs-5" for="prod-clave_kilo">Venta por kilo <small>(Clave)</small></label> 
                                                    <input type="text" class="form-control deshabilitado" id="prod-clave_kilo" placeholder="Código" disabled>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success mb-1 data-submit" id="btnSave">Guardar</button>
                                                <input type="hidden" id="prod_id" value="0">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div id="frm-barcode" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1">
                                <div class="modal-dialog">
                                    <div class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase">código de barras</h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal text-center">
                                            <img id="barcode">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-sucursales" >
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase"></h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">                                                   
                                            <div>
                                                <table id="tbl-sucursales" class="table">
                                                    <thead class="table-light">
                                                        <tr class="text-center">
                                                            <th>Sucursal</th>
                                                            <th>Stock</th>
                                                            <th>Última entrada</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody></tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Salir</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-listadoP" >
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase"></h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">                                                   
                                            <div>
                                                <table id="tbl-listadoP" class="table">
                                                    <thead class="table-light">
                                                        <tr class="text-center">
                                                            <th>Tipo</th>
                                                            <th>Hasta</th>
                                                            <th>Precio</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td>Menudeo</td>
                                                            <td><input type="text" class="form-control text-end" id="rango-menudeo" placeholder="0"></td>
                                                            <td>
                                                                <div class="input-group">
                                                                    <div class="input-group-text">
                                                                        <small>$</small>
                                                                    </div>
                                                                    <input type="text" class="form-control text-end" id="rango-precio_menudeo" placeholder="0.00">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td>Medio mayoreo</td>
                                                            <td><input type="text" class="form-control text-end" id="rango-medio" placeholder="0"></td>
                                                            <td>
                                                                <div class="input-group">
                                                                    <div class="input-group-text">
                                                                        <small>$</small>
                                                                    </div>
                                                                    <input type="text" class="form-control text-end" id="rango-precio_medio" placeholder="0.00">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td>Mayoreo</td>
                                                            <td><input type="text" class="form-control text-end" id="rango-mayoreo" placeholder="0"></td>
                                                            <td>
                                                                <div class="input-group">
                                                                    <div class="input-group-text">
                                                                        <small>$</small>
                                                                    </div>
                                                                    <input type="text" class="form-control text-end" id="rango-precio_mayoreo" placeholder="0.00">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td>Distribuidor</td>
                                                            <td><input type="text" class="form-control text-end deshabilitado" id="rango-distribuidor" placeholder="0" readonly></td>
                                                            <td>
                                                                <div class="input-group">
                                                                    <div class="input-group-text">
                                                                        <small>$</small>
                                                                    </div>
                                                                    <input type="text" class="form-control text-end" id="rango-precio_distribuidor" placeholder="0.00">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <input class="hidden" id="prod_rangos_id" value="0"></input>
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Salir</button>
                                                <button type="button" class="btn btn-success mb-1" data-bs-dismiss="modal" id="btnSaveRangos">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal fade" data-bs-backdrop="statis" data-bs-keyboard="false" id="frm-ajuste">
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase"></h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">    
                                            <div class="form-group row mb-1">
                                                <label class="col-sm-3 d-flex align-items-center justify-content-start form-label fs-5" for="nameP">Producto</label>
                                                <div class="col-sm-9">
                                                    <input type="text" class="form-control-plaintext fs-5 text-uppercase empty" id="nameP" readonly></input>
                                                </div>
                                                <label class="col-sm-3 d-flex align-items-center justify-content-start form-label fs-5" for="existencia">Existencia actual</label>
                                                <div class="col-sm-9">
                                                    <input type="text" class="form-control-plaintext fs-5 empty" id="existencia" readonly></input>
                                                </div>
                                            </div>       
                                            <div class="form-group row mt-1">
                                                <div class="col-sm-6">
                                                    <label class="form-label fs-5" for="ajuste-fecha">Fecha *</label>
                                                    <input type="date" id="ajuste-fecha" class="form-control" min="<?= date('Y-m-01') ?>" max="<?= date('Y-m-d')?>" value="<?= date('Y-m-d')?>">
                                                </div>
                                                <div class="col-sm-6">
                                                    <label class="form-label fs-5" for="ajuste-accion">Acción *</label>
                                                    <select class="form-control" id="ajuste-accion">
                                                        <option value="0" selected disabled>Seleccione una opción</option>
                                                        <option value="1">Alta</option>
                                                        <option clas="hidden" value="2">Baja</option>
                                                    </select>
                                                </div>
                                            </div>                                        
                                            <div class="form-group row mt-1">
                                                <div class="col-sm-6">
                                                    <label class="form-label fs-5" for="ajuste-motivo">Motivo *</label>
                                                    <select class="form-control deshabilitado" id="ajuste-motivo" disabled></select>
                                                </div>
                                                <div class="col-sm-6">
                                                    <label class="form-label fs-5" for="ajuste-cantidad">Cantidad *</label>
                                                    <input type="number" id="ajuste-cantidad" class="form-control" min="1">
                                                </div>
                                            </div>                                        
                                            <div class="form-group row mt-1">
                                                <div class="col-sm-12">
                                                    <label class="form-label fs-5" for="ajuste-comentarios">Comentarios *</label>
                                                    <textarea id="ajuste-comentarios" placeholder="Indique el motivo por el que se ajusta el inventario del producto." rows="10" cols="90"></textarea>
                                                </div>
                                            </div>                                        
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Salir</button>
                                                <button type="button" class="btn btn-danger me-1" id="btnAjustar">Guardar</button>
                                                <input  type="hidden" id="prod_id_ajuste" value="0">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal modal-slide-in modal-danger fade" id="frm-del">
                                <div class="modal-dialog">
                                    <form class="modal-content pt-0">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase">eliminar producto</h4>
                                        </div>
                                        <div class="modal-body flex-grow-1">
                                            <div class="mb-1 confirmacion hidden">
                                                ¿Estas seguro de eliminar el producto <strong></strong>?
                                            </div>
                                            <div class="mb-1 imposible hidden">
                                                Por el momento no se puede eliminar el producto <strong></strong> ya que hay stock disponible de éste en las siguientes sucursales: <br><br>
                                                <table id="tbl-info" class="table">
                                                    <thead class="table-light">
                                                        <tr class="text-center">
                                                            <th>Sucursal</th>
                                                            <th>Stock</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody></tbody>
                                                </table>
                                                <br>Para eliminar el producto primero debe dar de baja el inventario en cada sucursal.
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd hidden buttonsDel">
                                                <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-danger me-1" id="btnEliminar">Eliminar</button>
                                                <input  type="hidden" id="prod_id_del" value="0">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-masiva">
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase">carga masiva de inventario</h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                            <div class="card">
                                                <div class="card-header" id="cardData">
                                                    <div class="container-fluid">
                                                        <div class="row" data-bs-toggle="collapse" href="#inventario" role="button" aria-expanded="true" aria-controls="inventario">
                                                            <h5 class="fw-bolder fs-5 text-uppercase">
                                                                <i class="fas fa-caret-down m-1"></i>
                                                                <small> instrucciones </small>
                                                            </h5> 
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card-body cardBody">
                                                    <div class="" id="inventario">
                                                        <div class="alert instrucciones p-1 text" role="alert">
                                                            <p>
                                                                Este módulo es para dar de alta de forma masiva los productos contenidos en un Excel con el layout siguiente:
                                                                <br><center><b>Categoría, Subcategoría, Área, Clave, Descripción, Medida, Stock Mínimo, Unidad de Medida, Clave SAT, Venta por kilo, Venta por kilo (Cantidad), Venta por kilo (Clave).</b></center> <br>
                                                                * Columna D -> Clave, ninguna clave de producto debe estar repetida, en caso de que alguna se repita el sistema solo dará de alta los productos anteriores al de la clave repetida.<br>
                                                                * Columna H -> Unidad de Medida, debe colocar solo uno de los siguientes números: <b>1</b> indicará que el producto se vende por pieza, <b>2</b> indicará que el producto se vende por metro.<br>
                                                                * Columna J -> Venta por kilo, para indicar que el producto se vende por kilo colocar 1 en caso de que no colocar 0. <br>
                                                                * Columna K -> Venta por kilo (Cantidad), si en la columna J especificó que el producto se vende por kilo (1), en esta columna debe indicar el número de piezas que conforman un kilo del producto. <br>
                                                                * Columna L -> Venta por kilo (Código), si en la columna J especificó que el producto se vende por kilo (1), en esta columna debe indicar la clave utilizada para vender el producto por kilo.<br>
                                                                * Al indicar que el producto se vende por kilo el sistema agregará de manera automática un producto con unidad de medida <b>kilo</b>.
                                                                <br>
                                                                Antes de continuar verifique que el Excel que está seleccionando cumple con ese layout, de lo contrario no se podrán agregar los productos. <br>Si requiere descargar el formato del layout, lo puede hacer desde 
                                                                <button class="btn btn-sm btn-success" id="btnExcel">Aquí</button><br><br>
                                                                <b>Especificaciones: <br>
                                                                    * No modificar las columnas del layout.<br>
                                                                    * No agregar ni quitar columnas. <br>
                                                                    * No poner ninguna clase de estilos (fuente, bordes, colores) al layout.
                                                                </b>
                                                            </p><br>
                                                            <p>
                                                                Una vez que los datos del inventario estén completos en el layout, regrese a este modulo para continuar con el proceso.<br><br>
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div class="cargarArchivo">
                                                        <label class="col-form-label ml-0 pl-0 font-weight-bold" for="layout">Archivo Excel*</label>
                                                        <div id="layout" class="">
                                                            <div class="dz-message">Arrastre el archivo o de click para seleccionar</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success mb-1 data-submit" id="btnCargar">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-precios">
                                <div class="modal-dialog modal-lg">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase">modificación masiva de precios</h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                            <div class="card">
                                                <div class="card-header" id="cardData">
                                                    <div class="container-fluid">
                                                        <div class="row" data-bs-toggle="collapse" href="#inventario" role="button" aria-expanded="true" aria-controls="inventario">
                                                            <h5 class="fw-bolder fs-5 text-uppercase">
                                                                <i class="fas fa-caret-down m-1"></i>
                                                                <small> instrucciones </small>
                                                            </h5> 
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card-body cardBody">
                                                    <div class="" id="inventario">
                                                        <div class="alert instrucciones p-1 text" role="alert">
                                                            Seleccione área, categoría y subcategoría a las que pertenecen los productos de los cuales va a modificar el precio.
                                                            <div class="form-group row">
                                                                <div class="col-sm-4">
                                                                    <label class="form-label fw-bolder fs-5 text-white" for="precios-area">Área *</label>
                                                                    <select class="form-control" id="precios-area"></select>
                                                                </div>
                                                                <div class="col-sm-4 preciosCat hidden">
                                                                    <label class="form-label fw-bolder fs-5 text-white" for="precios-cat">Categoría *</label>
                                                                    <select class="form-control" id="precios-cat"></select>
                                                                </div>
                                                                <div class="col-sm-4 preciosSub hidden">
                                                                    <label class="form-label fw-bolder fs-5 text-white" for="precios-sub">Subcategoría *</label>
                                                                    <select class="form-control" id="precios-sub"></select>
                                                                </div>
                                                            </div><br>
                                                            <p>
                                                                Este módulo es para modificar de forma masiva el precio de los productos contenidos en un Excel con el layout siguiente:
                                                                <br><center><b>Id, Nombre, Precio Menudeo, Precio Medio-Mayoreo, Precio Mayoreo, Precio Distribuidor.</b></center><br>
                                                                <b>IMPORTANTE: Este procedimiento se debe realizar por sucursal, el archivo que aquí se cargue únicamente modificará los precios de los productos en la sucursal donde se encuentra logeado.</b><br>
                                                                Antes de continuar verifique que el Excel que está seleccionando cumple con ese layout, de lo contrario no se podrá modificar el precio de los productos. <br>Descargue el layout desde 
                                                                <button class="btn btn-sm btn-success" id="btnPrecios">Aquí</button><br><br>
                                                                <b>Especificaciones: <br>
                                                                    * No modificar las columnas A y B del layout.<br>
                                                                    * No modificar los nombres de las columnas en el layout.<br>
                                                                    * No agregar ni quitar columnas. <br>
                                                                    * No poner ninguna clase de estilos (fuente, bordes, colores) al layout.
                                                                </b>
                                                            </p><br>
                                                            <p>
                                                                Una vez que los precios de los productos sean correctos, regrese a este modulo para continuar con el proceso.<br><br>
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <div class="cargarPrecios">
                                                        <label class="col-form-label ml-0 pl-0 font-weight-bold" for="layout_precios">Archivo Excel*</label>
                                                        <div id="layout_precios" class="">
                                                            <div class="dz-message">Arrastra el archivo o da click para seleccionar</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success mb-1 data-submit" id="btnCambiarPrecios">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml'; ?>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/dropzone-master/dist/dropzone.js"></script>
	<script src="<?= URL_ROOT ?>/app-assets/plugin/jsBarcode/JsBarcode.all.min.js"></script>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                cat = 0,
                area = 0,
                subcat = 0;

            getItems('tbl-producto')

            $('#btnExportar').click(function(e){
                e.preventDefault
                window.open(apiUrl+'producto/exportar/minimos', '_blank')
            })

            $('#categoria').change(function(){
                $.blockUI()
                $('#prod-prod_categoria_id').empty();
                $('#prod-prod_categoria_id').append('<option value="0" selected disabled>Seleccione una opción</option>');
                cat = $(this).val()
                if(cat != 0){
                    $.get(apiUrl+'prod_clasificacion/getSubcategorias/'+cat, function(data){
                        $.each(data, function(index, elem){
                            $('#prod-prod_categoria_id').append('<option value="'+elem.id+'">'+elem.nombre+'</option>')
                        })
                        $('#prod-prod_categoria_id').val(subcat);
                        $.unblockUI()
                    }, 'json')
                }else{
                    $('#prod-prod_categoria_id').append('<option value="0">Todas</option>')
                }
                $('.subcategoria').removeClass('hidden')
            })

            $('#kilo').change(function(){
                $.blockUI()
                if($(this).is(':checked')){
                    $('#prod-cant_kilo').removeClass('deshabilitado').attr('disabled', false).prop('disabled', false).focus()
                    $('#prod-clave_kilo').removeClass('deshabilitado').attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else{
                    $('#prod-cant_kilo').addClass('deshabilitado').attr('disabled', true).prop('disabled', true).val('')
                    $('#prod-clave_kilo').addClass('deshabilitado').attr('disabled', true).prop('disabled', true).val('')
                    $.unblockUI()
                }
            })

            <?php if(in_array(MOD_PROD_SUC, $permisos)) : ?>
                $('#tbl-producto').on('click', '.btnVer', function(){
                    $.blockUI()
                    $('#tbl-sucursales tbody').empty()
                    prod_id = $(this).data('id')
                    producto = $(this).data('producto')
                    medida = $(this).data('medida')
                    $.get(apiUrl+'prod_stock/getStockSuc/'+prod_id, function(resp){
                        elem =  $('#tbl-sucursales tbody')
                        if(resp){
                            if(resp.length == 0){
                                tr = $('<tr></tr>')
                                tr.append('<td colspan="3" class="text-center">No se han registrado entradas del producto en otras sucursales</td>')
                                elem.append(tr)
                            }else{
                                contador = 0;
                                $.each(resp, function(index, item){
                                    if(item.id != <?= $_SESSION['sucursal_id'] ?>){
                                        if(item.stock){
                                            tr = $('<tr></tr>')
                                            tr.append('<td>'+item.nombre+'</td>')
                                            tr.append('<td class="text-center">'+item.stock+'</td>')
                                            tr.append('<td class="text-center">'+item.date+'</td>')
                                            elem.append(tr)
                                        }
                                        contador++
                                    }
                                })
                                if(contador == 0){
                                    tr = $('<tr></tr>')
                                    tr.append('<td colspan="3" class="text-center">No se han registrado entradas del producto en otras sucursales</td>')
                                    elem.append(tr)
                                }
                            }
                        }
                    },'json');
                    $('#frm-sucursales h4').html('stock de '+producto+' '+medida+' en otras sucursales')
                    $('#frm-sucursales').modal('show')
                    $.unblockUI()
                })
            <?php endif; ?>

            $('#tbl-producto').on('click', '.btnlistadoP', function(){
                $.blockUI()
                $.each($('#tbl-listadoP input'), function(index, elem){
                    $(elem).val('')
                })
                prod_id = $(this).data('id')
                producto = $(this).data('producto')
                medida = $(this).data('medida')
                $.get(apiUrl+'producto/getRangos/'+prod_id, function(resp){
                    $.each(resp, function(index, item){
                        $('#rango-'+index).val(item)
                    })
                    mayoreo = resp.mayoreo != null ? resp.mayoreo : 0
                    $('#rango-distribuidor').val(parseInt(mayoreo)+1)
                })
                $('#prod_rangos_id').val(prod_id)
                $('#frm-listadoP h4').html('rangos de precios '+producto+' '+medida+'')
                $('#btnSaveRangos').removeClass('disabled').attr('disabled', false)
                $('#frm-listadoP').modal('show')
                $.unblockUI()
            })

            $('#rango-mayoreo').change(function(){
                val = parseFloat($(this).val())
                $('#rango-distribuidor').val(parseFloat(val+1))
            })

            $('#btnSaveRangos').click(function(){
                $.blockUI()
                btn = $(this)
                btn.addClass('disabled').attr('disabled', true).prop('disabled', true)
                rangos = {}
                $.each($('#frm-listadoP input'), function(index, item){
                    ide = $(item).attr('id').replace('rango-', '')
                    rangos[ide] = $(item).val()
                })

                $.post(apiUrl+'producto/editRangos', rangos, function(resp){
                    if(resp.response){
                        toastr["success"]("¡Listo!", "Se actualizaron los precios por rango del producto.")
                        $('#frm-listadoP').modal('hide')
                        getItems('tbl-producto')
                    }else{
                        if(resp.code){
                            toastr["info"]("No hay cambios!", resp.msg)
                        }else
                        toastr["error"]("¡Ocurrió un problema!", "No pudimos actualizar los precios por rango del producto.")
                    }
                    btn.removeClass('disabled').attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                },'json')
            })

            <?php if(in_array(MOD_PROD_BAJA, $permisos)) : ?>
                $('#tbl-producto').on('click', '.btnAjuste', function(){
                    prod_id = $(this).data('id')
                    tr = $(this).closest('tr')
                    name = '('+$(tr).find('td:eq(0)').text()+') '+$(tr).find('td:eq(1)').text()
                    stock = $(tr).find('td:eq(6)').text()
                    $('#frm-ajuste h4').html('ajuste de inventario')
                    $('#nameP').val(name)
                    $('#existencia').val(stock)
                    $('#prod_id_ajuste').val(prod_id)
                    if(stock == 0){
                        $('#ajuste-accion option[value="2"]').addClass('hidden')
                    }else{
                        $('#ajuste-accion option[value="2"]').removeClass('hidden')
                        $('#ajuste-fecha').prop('disabled', false).attr('disabled', false)
                        $('#ajuste-accion').prop('disabled', false).attr('disabled', false)
                        $('#ajuste-cantidad').prop('disabled', false).attr('disabled', false)
                        $('#ajuste-comentarios').prop('disabled', false).attr('disabled', false)
                        $('#btnAjustar').prop('disabled', false).attr('disabled', false)
                    }
                    $('#frm-ajuste').modal('show')
                })

                $('#ajuste-accion').change(function(){
                    opt = $(this).val()
                    existencia = $('#existencia').val()
                    $('#ajuste-motivo').empty()
                    if(opt == 1){
                        $('#ajuste-motivo').attr('disabled', true).prop('disabled', true).append('<option value="1" selected>Inventario físico realizado</option>')
                        $('#ajuste-cantidad').val('')
                        $('#ajuste-cantidad').attr('max', 1000000)
                    }else{
                        $('#ajuste-motivo').attr('disabled', false).prop('disabled', false).removeClass('deshabilitado')
                        $('#ajuste-motivo').append('<option value="0" selected disabled>Seleccione una opción</option>')
                        $('#ajuste-motivo').append('<option value="2">Perdida</option>')
                        $('#ajuste-motivo').append('<option value="3">Merma</option>')
                        $('#ajuste-cantidad').val(existencia)
                        $('#ajuste-cantidad').attr('max', existencia)
                    }
                })

                $('#ajuste-cantidad').change(function(){
                    cant = parseFloat($(this).val())
                    accion = $('#ajuste-accion').val()
                    existencia = $('#existencia').val()
                    if(accion == 1){
                        if(cant < 1){
                            error('ajuste-cantidad', 'Ingrese un número mayor a 0')
                            $(this).val(1)
                        }
                    }else{
                        if(cant < 1){
                            error('ajuste-cantidad', 'No podemos dar de baja menos de 1 unidad del producto')
                            $(this).val(1)
                        }else if(cant > existencia){
                            error('ajuste-cantidad', 'No podemos dar de baja más unidades que la existencia actual del producto')
                            $(this).val(existencia)
                        }
                    }
                })

                $('#btnAjustar').click(function(){
                    $.blockUI()
                    btn = $(this)
                    btn.attr('disabled', true).prop('disabled', true)
                    data = {}
                    $.each($('#frm-ajuste input, #frm-ajuste textarea, #frm-ajuste select'), function(index, elem){
                        if(!$(elem).hasClass('empty')){
                            ide = $(elem).attr('id').replace('ajuste-','')
                            data[ide] = $.trim($(elem).val())
                        }
                    })
                    if(data.fecha == ''){
                        error('ajuste-fecha', 'Este campo es requerido')
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    }else if(data.accion == 0 || data.accion == null){
                        error('ajuste-accion', 'Este campo es requerido, seleccione una opción')
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    }else if(data.motivo == 0 || data.motivo == null){
                        error('ajuste-motivo', 'Este campo es requerido, seleccione una opción')
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    }else if(data.comentarios == ''){
                        error('ajuste-comentarios', 'Este campo es requerido')
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    }else{
                        $.post(apiUrl+'prod_ajuste/add/', data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se realizó el ajuste de inventario del producto.")
                                $('#frm-ajuste').modal('hide')
                                getItems('tbl-producto')
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos realizar el ajuste de inventario del producto.")
                            }
                            btn.attr('disabled', false).prop('disabled', false)
                            $.unblockUI()
                        },'json')
                    }
                })
            <?php endif; ?>

            <?php if(in_array(MOD_ADD, $permisos)) :  ?>
                $('#btnAdd').click(function(){
                    $.blockUI()
                    clear()
                    subcat = 0;
                    $.post(apiUrl+'producto/addCorto/', function(resp){
                        $('#prod-clave').val(resp.clave)
                        $('#prod_id').val(resp.clave)
                        $('#codigo_barras').val('*'+resp.clave+'*')
                    })

                    categorias('categoria'); areas('prod-prod_area_id'); unidades();
                    $('.subcategoria').addClass('hidden')
                    $('#prod-cant_kilo').attr('disabled', true).prop('disabled', true).addClass('deshabilitado')
                    $('#prod-clave_kilo').attr('disabled', true).prop('disabled', true).addClass('deshabilitado')
                    $('#frm-producto h4').html('agregar producto')
                    $('#frm-producto').modal('show')
                    $.unblockUI()
                })
            <?php endif; ?>

            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                $('#tbl-producto').on('click', '.btnEdit', function(){
                    $.blockUI()
                    $('#kilo').prop('checked', false)
                    categorias('categoria'); areas('prod-prod_area_id'); clear(); 
                    $('#frm-producto h4').html('editar producto')
                    id = $(this).data('id')
                    $('#prod_id').val(id)
                    $.get(apiUrl+'producto/get/'+id, function(data){
                        $.each(data, function(index, elem){
                            $('#prod-'+index).val(elem)
                        })
                        $('#codigo_barras').val('*'+data.clave+'*')

                        if(data.venta_kilo == 1){
                            $('#kilo').prop('checked', true)
                            $('#prod-cant_kilo').val(data.kilo.cantidad).attr('disabled', false).prop('disabled', false).removeClass('deshabilitado')
                            $('#prod-clave_kilo').val(data.kilo.clave).attr('disabled', false).prop('disabled', false).removeClass('deshabilitado')
                        }
                        unidades(data.prod_unidad_medida_id);
                        $('#categoria').val(data.categoria).trigger('change');
                        subcat = data.prod_categoria_id;
                        $('#frm-producto').modal('show')
                        $.unblockUI()
                    },'json')
                })
            <?php endif; ?>

            $('#prod-clave').focusout(function(){
                val = $(this).val();
                $('#codigo_barras').val('*'+val+'*')
            })

            $('#btnSave').click(function(){                    
                $.blockUI()
                btn = $(this)
                btn.attr('disabled', true).prop('disabled', true)
                id = $('#prod_id').val()
                data = {}
                $.each($('#frm-producto input, #frm-producto select'), function(index, elem) {
                    if($(elem).attr('id').includes('prod')){
                        ide = $(elem).attr('id').replace('prod-','')
                        data[ide] = $.trim($(elem).val())
                    }
                });
                data['venta_kilo'] = $('#kilo').is(':checked') ? 1 : 0

                if($('#categoria').val() == 0 || $('#categoria').val() == null){
                    error('categoria', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['prod_categoria_id'] == ''){
                    error('prod-prod_categoria_id', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['descripcion'] == ''){
                    error('prod-descripcion', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['descripcion'].length < 3){
                    error('prod-descripcion', 'La descripción debe contener al menos 3 caracteres')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['venta_kilo'] == 1 && data['cant_kilo'] == ''){
                    error('prod-cant_kilo', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['venta_kilo'] == 1 && data['clave_kilo'] == ''){
                    error('prod-clave_kilo', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else if(data['minimo'] == ''){
                    error('prod-minimo', 'Este campo es obligatorio')
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                }else{
                    if(id == 0){
                        $.post(apiUrl+'producto/add/', data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se ha agregado el producto.")
                                $('#frm-producto').modal('hide')
                                getItems('tbl-producto')
                            }else if(resp.error == 23000){
                                toastr["warning"]("¡Verifique la información!", resp.message)
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos agregar el producto.")
                            }
                            btn.attr('disabled', false).prop('disabled', false)
                            $.unblockUI()
                        }, 'json')
                    }else{
                        $.post(apiUrl+'producto/edit/'+id, data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se editó la información del producto.")
                                getItems('tbl-producto')
                                $('#frm-producto').modal('hide')
                                btn.attr('disabled', false).prop('disabled', false)
                                $.unblockUI()
                            }else if(resp.code){
                                toastr["info"]("No hay cambios!", resp.msg); 
                                btn.attr('disabled', false).prop('disabled', false)
                                $.unblockUI()
                            }else if(resp.error){
                                toastr["warning"]("¡Verifique la información!", resp.message)
                                btn.attr('disabled', false).prop('disabled', false)
                                $.unblockUI()
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos editar la información del producto.")
                                btn.attr('disabled', false).prop('disabled', false)
                                $.unblockUI()
                            }
                        }, 'json')
                    }
                }
            })

            $('#tbl-producto').on('click', '.btnCodigo', function(){
                tr = $(this).closest('tr')
                codigo = '*'+$(tr).find('td:eq(0)').text()+'*'
                $("#barcode").JsBarcode(codigo, {
					width: 2,
					height: 90,
					displayValue:true,
					textAlign:"center",
					textPosition:"bottom",
					textMargin: 2,
					fontSize: 20,
					background:"#ffffff",
					lineColor:"#000000",
					margin: 10,
				})
				$('#frm-barcode').modal('show')
            })

            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                $('#tbl-producto').on('click', '.btnDel', function(){
                    btn = $(this)
                    btn.attr('disabled', false).prop('disabled', false)
                    $.unblockUI()
                    $('#tbl-info tbody').empty()
                    prod_id = $(this).data('id')
                    tr = $(this).closest('tr')
                    name = $(tr).find('td:eq(1)').text()
                    $.get(apiUrl+'prod_stock/getStockSuc/'+prod_id, function(resp){
                        if(resp.length != 0){
                            elem =  $('#tbl-info tbody')
                            $.each(resp, function(index, item){
                                if(item.stock){
                                    tr = $('<tr></tr>')
                                    tr.append('<td>'+item.nombre+'</td>')
                                    tr.append('<td class="text-center">'+item.stock+'</td>')
                                    elem.append(tr)
                                }
                            })
                            $('.buttonsDel').addClass('hidden')
                            $('.confirmacion').addClass('hidden')
                            $('.imposible strong').html(name)
                            $('.imposible').removeClass('hidden')
                            $.unblockUI()
                        }else{
                            $('.confirmacion').removeClass('hidden')
                            $('.confirmacion strong').html(name)
                            $('.imposible').addClass('hidden')
                            $('.buttonsDel').removeClass('hidden')
                            $.unblockUI()
                        }
                    },'json');
                    $('#prod_id_del').val(prod_id)
                    $('#frm-del').modal('show')
                })

                $('#btnEliminar').click(function(){
                    $.unblockUI()
                    id = $('#prod_id_del').val()
                    $.post(apiUrl+'producto/del/'+id, function(resp){
                        if(resp.response){
                            toastr["success"]("¡Listo!", "Se eliminó el producto.")
                            getItems('tbl-producto')
                            $('#frm-del').modal('hide')                        
                            $.unblockUI()
                        }else{
                            toastr["error"]("¡Ocurrió un problema!", "No pudimos eliminar el producto.")
                            $.unblockUI()
                        }
                    },'json')
                })
            <?php endif; ?>

            <?php if(in_array(MOD_CARGA_M, $permisos)) : ?>
                $('#btnMasiva').click(function(){
                    $('#btnCargar').attr('disabled', false).prop('disabled', false)
                    $('#frm-masiva').modal('show')
                })

                $('#btnExcel').click(function(e){
                    e.preventDefault();
                    window.open(apiUrl+'producto/excel/')
                })

                $('#layout').dropzone({
                    paramName: 'file', 
                    maxFiles: 1,
                    url: apiUrl+'producto/cargarInv/', 
                    acceptedFiles: '.xlsx', 
                    dictRemoveFile: 'Quitar archivo',
                    autoProcessQueue: false, 
                    parallelUploads: 1,
                }).addClass('dropzone');

                Dropzone.forElement("#layout").on("maxfilesexceeded", function(file) { this.removeFile(file); });

                Dropzone.forElement("#layout").on('addedfile', function(file){
                    var btnDelFile = Dropzone.createElement('<a href="#" class="btnDelFile text-danger"><small><i class="fas fa-trash"></i> Quitar archivo</small></a>');
                    dz = Dropzone.forElement("#layout");

                    btnDelFile.addEventListener('click', function(e){
                        e.preventDefault();
                        e.stopPropagation();
                        dz.removeFile(file);
                    });
                    file.previewElement.appendChild(btnDelFile);
                });

                Dropzone.forElement("#layout").on("success", function(file, resp, formData) {
                    if(resp.response){
                        toastr["success"]("¡Listo!", "Se realizó la carga del inventario.")
                        $('#frm-masiva').modal('hide')
                        getItems('tbl-producto')
                    }else{
                        if(resp.error == 23000) toastr["error"]("¡Código repetido!", resp.message)
                        else toastr["error"]("¡Ocurrió un error inesperado!", 'No se pudo completar la carga de productos.')
                        $('#frm-masiva').modal('hide')
                        getItems('tbl-producto')
                    }
                });

                $('#btnCargar').on('click', function(e){
                    e.preventDefault();
                    $.blockUI()
                    btn = $(this)
                    btn.attr('disabled', 'disabled').prop('disabled', 'disabled')
                    if(Dropzone.forElement("#layout").files.length == 0){
                        error('layout', 'Debe agregar un archivo con el inventario.');
                        btn.attr('disabled', false).prop('disabled', false)
                        $.unblockUI()
                    }else{
                        $.blockUI()
                        Dropzone.forElement("#layout").processQueue();
                        setTimeout(() => {
                        }, 15000);
                        $.unblockUI()
                    }
                });
            <?php endif; ?>

            <?php if(in_array(MOD_MODIF_M, $permisos)): ?>
                $('#precios-area').change(function(){
                    $.blockUI()
                    $('#precios-cat').empty()
                    area = $(this).val()
                    $('#precios-cat').append('<option value="" selected disabled>Seleccione una opción</option>')
                    if(area != 0){
                        $.get(apiUrl+'prod_clasificacion/getCatByArea/'+area, function(data){
                            if(data.response){
                                $('#precios-cat').append('<option value="0">Todas</option>')
                                $.each(data.result, function(index, elem){
                                    $('#precios-cat').append('<option value="'+elem.categoria_id+'">'+elem.cat_nombre+'</option>')
                                })
                            }else{
                                $('#precios-cat').append('<option value="">No se encontraron categorías en el área seleccionada</option>')
                            }
                        }, 'json')
                    }else{
                        $('#precios-cat').append('<option value="0">Todas</option>')
                    }
                    $('.preciosCat').removeClass('hidden')
                    // $('#precios-sub').empty()
                    $.unblockUI()
                })

                $('#precios-cat').change(function(){
                    $.blockUI()
                    $('#precios-sub').empty()
                    cat = $(this).val()
                    $('#precios-sub').append('<option value="" selected disabled>Seleccione una opción</option>')
                    $('#precios-sub').append('<option value="0">Todas</option>')
                    $.get(apiUrl+'prod_clasificacion/getSubcategorias/'+cat, function(data){
                        $.each(data, function(index, elem){
                            $('#precios-sub').append('<option value="'+elem.id+'">'+elem.nombre+'</option>')
                        })
                    }, 'json')
                    $('.preciosSub').removeClass('hidden')
                    $.unblockUI()
                })

                $('#btnModifPre').click(function(){
                    categorias('precios-cat'); areas('precios-area');
                    $('#frm-precios').modal('show')
                })

                $('#btnPrecios').click(function(e){
                    e.preventDefault();
                    cat = $('#precios-cat').val()
                    sub = $('#precios-sub').val()
                    area = $('#precios-area').val()
                    
                    if(area == null){
                        error('precios-area', 'Debe seleccionar una opción')
                    }else if(cat == null){
                        error('precios-cat', 'Debe seleccionar una opción')
                    }else if(sub == null){
                        error('precios-sub', 'Debe seleccionar una opción')
                    }else{
                        window.open(apiUrl+'producto/precios/'+cat+'/'+sub+'/'+area)
                    }
                })

                $('#layout_precios').dropzone({
                    paramName: 'file', 
                    maxFiles: 1,
                    url: apiUrl+'producto/cambiarP/', 
                    acceptedFiles: '.xlsx', 
                    dictRemoveFile: 'Quitar archivo',
                    autoProcessQueue: false, 
                    parallelUploads: 1,
                }).addClass('dropzone');

                Dropzone.forElement("#layout_precios").on("maxfilesexceeded", function(file) { this.removeFile(file); });

                Dropzone.forElement("#layout_precios").on('addedfile', function(file){
                    var btnDelFile = Dropzone.createElement('<a href="#" class="btnDelFile text-danger"><small><i class="fas fa-trash"></i> Quitar archivo</small></a>');
                    dz = Dropzone.forElement("#layout_precios");

                    btnDelFile.addEventListener('click', function(e){
                        e.preventDefault();
                        e.stopPropagation();
                        dz.removeFile(file);
                    });
                    file.previewElement.appendChild(btnDelFile);
                });

                Dropzone.forElement("#layout_precios").on("success", function(file, resp, formData) {
                    if(resp.response){
                        toastr["success"]("¡Listo!", "Se actualizaron los precios de los productos.")
                        $('#frm-precios').modal('hide')
                    }else{
                        toastr["error"]("¡Ocurrió un error inesperado!", 'No se pudo completar la actualización de precios.')
                    }
                });

                $('#btnCambiarPrecios').on('click', function(e){
                    e.preventDefault();
                    if(Dropzone.forElement("#layout_precios").files.length == 0){
                        error('layout_precios', 'Debe agregar un archivo con precios de los productos.');
                    }else{
                        Dropzone.forElement("#layout_precios").processQueue();
                        setTimeout(() => {
                        }, 15000);
                    }
                });
            <?php endif; ?>

            document.addEventListener ("keydown", function (e) {
                if(e.which === 27) {
                    $('#frm-sucursales').modal('hide');
                    $('#frm-listadoP').modal('hide');
                    $('#frm-ajuste').modal('hide');
                    $('#frm-producto').modal('hide');
                    $('#frm-barcode').modal('hide');
                    $('#frm-del').modal('hide');
                    $('#frm-masiva').modal('hide');
                    $('#frm-precios').modal('hide');
                }
            })

            function categorias(elem){
                $.unblockUI()
                $('#'+elem).empty();
                if(elem == 'precios-cat'){
                    $('#'+elem).append('<option value="" selected disabled>Seleccione una opción</option>')
                    $('#'+elem).append('<option value="0">Todas</option>')
                    $.unblockUI()
                }else{
                    $('#'+elem).append('<option value="0" selected disabled>Seleccione una opción</option>')
                    $.unblockUI()
                }
                $.get(apiUrl+'prod_clasificacion/getCategorias', function(data){
                    $.each(data, function(index, item){
                        $('#'+elem).append('<option value="'+item.id+'">'+item.nombre+'</option>')
                    })
                    if(elem == 'precios-cat') $('#'+elem).trigger('change')
                    $.unblockUI()
                }, 'json')
            }

            function areas(elem){
                $.blockUI()
                $('#'+elem).empty();
                if(elem == 'precios-area'){
                    $('#'+elem).append('<option value="" disabled>Seleccione una opción</option>')
                    $('#'+elem).append('<option value="0">Todas</option>')
                    $.unblockUI()
                }else{
                    $('#'+elem).append('<option value="0" selected disabled>Seleccione una opción</option>')
                    $.unblockUI()
                }
                $.get(apiUrl+'prod_clasificacion/getAreas', function(resp) {
                    if(resp.length > 0) {
                        $.each(resp, function(index, item) {
                            $('#'+elem).append('<option value="'+item.id+'">'+item.nombre+'</option>')
                        });
                        if(elem == 'precios-area') $('#'+elem).trigger('change')
                        $.unblockUI()
                    }
                }, 'json');
            }

            function clear(){
                $.each($('#frm-producto input'), function(index, elem){
                    ide = $(elem).attr('id')
                    $('#'+ide).val('')
                })
                $('#prod_id').val(0)
                $('#prod-menudeo_d').val(1)
                $('#prod-prod_categoria_id').empty();
                $('#categoria').empty();
                $('#kilo').prop('checked', false)
            }

            function unidades(value=0){
                $('#prod-prod_unidad_medida_id').empty()
                $.get(apiUrl+'producto/getUnidades', function(resp){
                    $('#prod-prod_unidad_medida_id').append('<option value="0" selected disabled>Seleccione una opción</option>')
                    $.each(resp, function(index, item){
                        $('#prod-prod_unidad_medida_id').append('<option value="'+item.id+'">'+item.clave+' - '+item.descripcion+'</option>')
                    })
                    $('#prod-prod_unidad_medida_id').val(value)
                },'json')
            }

            function getItems(tbl){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable()
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl){
                if($('#tbl-producto').length){
                    $('#tbl-producto').DataTable({
                        ajax:{
                            url: apiUrl+'producto/getAllDataTable',
                            type: 'GET',
                        },
                        columns: [
                            {data: 'clave'},
                            {data: 'descripcion'},
                            {data: 'medida'},
                            {data: 'codigo_barras'},
                            // {data: 'categoria'},
                            // {data: 'subcategoria'},
                            {data: 'area'},
                            {data: 'minimo'},
                            {data: 'stock'},
                            {data: 'enMinimo'},
                            {data: ''}
                        ],
                        columnDefs: [
                            {
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['data_id']
                                    if(full['minimo'] != 'N/A' && full['stock'] != 'N/A' && full['enMinimo'] != 'N/A'){
                                        acciones = '<div class="text-center">'+
                                            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-new-info btn-sm btnEdit" data-id="'+id+'" data-toggle="tooltip" title="Editar" style="margin-right:4px;">'+
                                                    feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-danger btn-sm btnDel" data-id="'+id+'" data-name="'+full['descripcion']+'" data-toggle="tooltip" title="Eliminar" style="margin-right:4px;">'+
                                                    feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>' +
                                            <?php endif; ?>
                                            '<div class="btn-group">' +
                                                '<a class="btn btn-sm btn-outline-dark dropdown-toggle hide-arrow" data-bs-toggle="dropdown">' +
                                                    feather.icons['more-vertical'].toSvg({ class: 'font-small-4' }) +
                                                '</a>' +
                                                '<div class="dropdown-menu dropdown-menu-end" style="min-width: 5rem; text-align:center; ">' +
                                                    '<button type="button" class="btn btn-outline-new-info btn-sm btnCodigo" data-id="'+id+'" data-toggle="tooltip" title="Código de Barras" style="margin-right:4px;">'+
                                                       '<i class="fas fa-barcode"></i>'+
                                                    '</button>'+
                                                    <?php if(in_array(MOD_PROD_SUC, $permisos)) : ?>
                                                        "<button type='button' class='btn btn-outline-warning btn-sm btnVer' data-id='"+id+"' data-producto='"+full['descripcion']+"' data-medida='"+full['medida']+"' data-toggle='tooltip' title='Ver en Sucursales' style='margin-right:4px;'>"+ 
                                                            feather.icons['eye'].toSvg({ class: 'font-small-4 me-20' })+
                                                        "</button>"+
                                                    <?php endif; ?>
                                                    "<button type='button' class='btn btn-outline-success btn-sm btnlistadoP' data-id='"+id+"' data-producto='"+full['descripcion']+"' data-medida='"+full['medida']+"' data-toggle='tooltip' title='Precios' style='margin-right:4px;'>"+ 
                                                        feather.icons['dollar-sign'].toSvg({ class: 'font-small-4 me-20' }) +
                                                    "</button>"+
                                                    <?php if(in_array(MOD_PROD_BAJA, $permisos)) : ?>
                                                        '<button type="button" class="btn btn-outline-dark btn-sm btnAjuste" data-id="'+id+'" data-toggle="tooltip" title="Ajuste Inventario" style="margin-right:4px;">'+
                                                            feather.icons['clipboard'].toSvg({ class: 'font-small-4 me-20' })+
                                                        '</button>'+
                                                    <?php endif; ?>
                                                '</div>' +
                                            '</div>'+
                                        '</div>'
                                    }else if(full['minimo'] == 'N/A' && full['stock'] == 'N/A' && full['enMinimo'] == 'N/A'){
                                        acciones = '<div class="text-center">'+
                                            '<button type="button" class="btn btn-outline-success btn-sm btnlistadoP" data-id="'+id+'" data-producto="'+full['descripcion']+'" data-toggle="tooltip" title="Precios" style="margin-right:4px;">'+ 
                                                feather.icons['dollar-sign'].toSvg({ class: 'font-small-4 me-20' }) +
                                            '</button>'+
                                        '</div>'
                                    }
                                    return (
                                        acciones
                                    );
                                }
                            },
                            {
                                targets: 1,
                                width: '20%',
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column">' +
                                        full['descripcion'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 5,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column text-center">' +
                                        full['minimo'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 6,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column text-center">' +
                                        full['stock'] +
                                    '</div>';
                                    return salida;
                                }
                            },
                            {
                                visible: false, targets: [7]
                            }
                        ],
                        createdRow: function(row, data, dataIndex) {
                            if(parseInt(data.stock) <= parseInt(data.minimo)){                        
                                $(row).addClass('stockMinimo');                                
                            }
                        },
                        order: [[0, 'asc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'<?= URL_ROOT ?>/spanish.json'
                        },
                        initComplete: function () {
                            var label = $('<label for="cuantos">Mostrar</label>').appendTo('#tbl-producto_length');
                            var selectCount = $('<select id="cuantos" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>')
                                .appendTo('#tbl-producto_length').on('change', function () {
                                    stock = $('#enStock').val();
                                    $('#tbl-producto').DataTable().page.len( $(this).val() ).draw();
                                    $('#enStock').val(stock).trigger('change');
                                });

                            this.api()
                                .columns(7)
                                .every(function () {
                                var column = this;
                                
                                var select = $(
                                    '<select id="enStock" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"><option value=""> Todos </option></select>'
                                    )
                                    .prependTo('#tbl-producto_length')
                                    .on('change', function () {
                                        $('#tbl-producto').DataTable().column(7).search(
                                            $('#enStock').val()
                                        ).draw();
                                    });
                                var label = $('<label class="labelTypeU" class="form-label" for="enStock">Stock</label>').prependTo('#tbl-producto_length');
                                            
                                column
                                    .data()
                                    .unique()
                                    .sort()
                                    .each(function (d, j) {
                                        select.append('<option value="' + d + '" class="text-capitalize">' + d + '</option>');
                                    });
                                });

                            $('#tbl-producto_length label:eq(1)').addClass('hidden');
                        }
                    });
                }
            }

        });
    </script>
</html>