<?php 
	include 'header.phtml';
    define('MOD_VER_RPT',  41);

    if(!in_array(MOD_VER_RPT, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 

    $meses = ['ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE'];
    $num = 1;
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom filtroFechas">
                                <div class="col-sm-4 col-md-6 col-12">
                                    <div class="input-group input-daterange">
                                        <select class="form-control text-center" id="mes">
                                            <?php foreach($meses as $mes) : ?>
                                                <option value="<?= $num ?>" <?= $num == $mes_select ? ' selected="selected"': '' ?> > <?= $mes ?> </option>
                                            <?php $num++; endforeach; ?>
                                        </select>
                                        <span class="input-group-text">del</span>
                                        <select class="form-control text-center" id="anio">
											<?php for($i=2023; $i<=date('Y'); $i++): ?>
												<option value="<?= $i ?>" <?= $anio == $i ? ' selected="selected"': '' ?>><?= $i ?></option>
											<?php endfor; ?>
										</select>
                                        <button type="button" class="btn btn-new-info" id="btnGrafica"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 mt-1">
                                    <center><h4 class="txtTitle"></h4></center>
                                </div>
                                <div class="col-sm-6">
                                    <canvas class="doughnut-chart-ex chartjs" id="grafica" style="width: 100%; height: 300px; overflow: visible;"></canvas>
                                </div>
                                <div class="col-sm-6">
                                    <table class="table table-bordered mt-2" id="table-desc">
                                        <thead>
                                            <tr>
                                                <th>Forma de Pago</th>
                                                <th>Monto</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom filtroFechas">
                                <div class="col-sm-4 col-md-6 col-12">
                                    <div class="input-group input-daterange">
                                        <span class="input-group-text">Del</span>
                                        <input type="date" id="desde" class="form-control" value="<?= date('Y-m-01') ?>"/>
                                        <span class="input-group-text">al</span>
                                        <input type="date" id="hasta" class="form-control" value="<?= date('Y-m-d') ?>" max="<?= date('Y-m-d') ?>"/>
                                        <button type="button" class="btn btn-new-info" id="btnBuscar"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl_pagos" class="table">
                                    <thead class="table-light">
                                        <tr class="text-center">
                                            <th>Fecha</th>
                                            <th>Método pago</th>
                                            <th>Monto</th>
                                            <th>Folio Venta</th>
                                            <th>Usuario</th>
                                            <th>Cliente</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script src="<?= URL_ROOT ?>/app-assets/vendors/js/vendors.min.js"></script>
    <script src="<?= URL_ROOT ?>/app-assets/vendors/js/charts/chart.min.js"></script>

    <?php include 'footer.phtml'; ?>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                id_cliente = 0,
                desde = $('#desde').val()
                hasta = $('#hasta').val()
                primaryColorShade = '#836AF9',
                yellowColor = '#ffe800',
                successColorShade = '#28dac6',
                tooltipShadow = 'rgba(0, 0, 0, 0.25)',
                black = 'rgb(0, 0, 0)',
                white = 'rgb(255, 255, 255)',
                grafica = document.getElementById('grafica');

            getItems('tbl_pagos', desde, hasta)

            meses = ['', 'ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE']
            mes = $('#mes').val()
            anio = $('#anio').val()
		    txtTitle = 'MÉTODOS DE PAGO UTILIZADOS DURANTE ' + meses[mes] + ' DEL ' + anio
            $('.txtTitle').html(txtTitle)
            labels = []
            data = []
            colors = []
            <?php 
                $colors = ['#0089ff', '#00b7ff', '#00d472', '#cd97b1', '#ffb9a6', '#423156', '#683b62', '#9e4e72', '#e36f82', '#ffa48e', '#ee2ee4', '#ff5e87', '#4b7045'];
                $monto_metodo = 0;
                foreach($metodos as $metodo):
                    $color = $colors[intval(rand(0, count($colors)-1))];
                    $monto_metodo = $metodo->monto;
            ?>
                    labels.push('<?= $metodo->metodo ?>');
                    data.push(<?= $monto_metodo ?>);
                    colors.push('<?= $color ?>');

                    container = $('#table-desc')
                    tr = $('<tr></tr>')
                    tr.append('<td class="fw-bolder"><span class="badge bg-label rounded-pill" style="background-color: <?= $color ?>";><?= $metodo->metodo ?></span></td>')
                    tr.append('<td>$ <?= $monto_metodo ?></td>')
                    container.append(tr)
                <?php endforeach; ?>

            var doughnutExample = new Chart(grafica, {
                type: 'doughnut',
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    responsiveAnimationDuration: 500,
                    cutoutPercentage: 60,
                    legend: { display: false },
                    tooltips: {
                    callbacks: {
                        label: function (tooltipItem, data) {
                            var label = data.datasets[0].labels[tooltipItem.index] || '',
                                value = data.datasets[0].data[tooltipItem.index];
                            var output = ' ' + label + ' : $' + parseFloat(value).toFixed(2) + '';
                            return output;
                        }
                    },
                    // Updated default tooltip UI
                    shadowOffsetX: 1,
                    shadowOffsetY: 1,
                    shadowBlur: 8,
                    shadowColor: tooltipShadow,
                        backgroundColor: white,
                        titleFontColor: black,
                        bodyFontColor: black
                    }
                },
                data: {
                    datasets: [
                        {
                            labels: labels,
                            data: data,
                            backgroundColor: colors,
                            borderWidth: 0,
                            pointStyle: 'rectRounded'
                        }
                    ]
                }
            });

            $('#btnBuscar').click(function(e){
                e.preventDefault()
                desde = $('#desde').val()
                hasta = $('#hasta').val()
                getItems('tbl_pagos', desde, hasta)
            })

            $('#btnGrafica').click(function(e){
                e.preventDefault()
                mes = $('#mes').val()
                anio = $('#anio').val()
                if(!'<?= $_SERVER['REQUEST_URI'] ?>'.endsWith('/reporte/periodo/'+mes+'/'+anio)) {
                    window.location.href = '<?= URL_ROOT ?>/reporte/metodo/'+mes+'/'+anio;
                }
            })

            function getItems(tbl, desde, hasta){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable(tbl, desde, hasta)
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl, desde, hasta){
                if($('#'+tbl).length){
                    $('#'+tbl).DataTable({
                        ajax:{
                            url: apiUrl+'venta_pago/getAll/'+desde+'/'+hasta,
                            type: 'GET',
                        },
                        columns: [
                            {data: 'fecha'},
                            {data: 'metodo'},
                            {data: 'monto'},
                            {data: 'folio'},
                            {data: 'usuario'},
                            {data: 'cliente'}
                        ],
                        columnDefs: [ 
                            {
                                targets: 0,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column">' +
                                            '<span >' +
                                                full['fecha'] +
                                            '</span>' +
                                            '<small class="emp_post text-muted">' +
                                            full['hora'] +
                                            '</small>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                            {
                                targets: 2,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column text-end">' +
                                            '<span> $' +
                                                full['monto'] +
                                            '</span>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                        ],
                        order: [[0, 'desc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'<?= URL_ROOT ?>/spanish.json'
                        },
                        initComplete: function () {
                            var label = $('<label for="cuantos">Mostrar</label>').appendTo('#tbl_pagos_length');
                            var selectCount = $('<select id="cuantos" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>')
                                .appendTo('#tbl_pagos_length').on('change', function () {
                                    tipo = $('#tipo').val();
                                    $('#tbl_pagos').DataTable().page.len( $(this).val() ).draw();
                                    $('#tipo').val(tipo).trigger('change');
                                });

                            this.api()
                                .columns(1)
                                .every(function () {
                                var column = this;
                                
                                var select = $(
                                    '<select id="metodo" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"><option value=""> Todos </option></select>'
                                    )
                                    .prependTo('#tbl_pagos_length')
                                    .on('change', function () {
                                        $('#tbl_pagos').DataTable().column(1).search(
                                            $('#metodo').val()
                                        ).draw();
                                    });
                                var label = $('<label for="metodo">Método</label>').prependTo('#tbl_pagos_length');
                                            
                                column
                                    .data()
                                    .unique()
                                    .sort()
                                    .each(function (d, j) {
                                        select.append('<option value="' + d + '" class="text-capitalize">' + d + '</option>');
                                    });
                                });

                            $('#tbl_pagos_length label:eq(1)').addClass('hidden');
                        }
                    });
                }
            }

        });
    </script>
</html>
