<?php 
	include 'header.phtml';
    define('MOD_VER_RPT',  39);

    if(!in_array(MOD_VER_RPT, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 

    $meses = ['ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE'];
    $num = 1;
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom filtroFechas">
                                <div class="col-md-4 col-12">
                                    <div class="input-group input-daterange">
                                        <select class="form-control text-center" id="mes">
                                            <?php foreach($meses as $mes) : ?>
                                                <option value="<?= $num ?>" <?= $num == $mes_select ? ' selected="selected"': '' ?> > <?= $mes ?> </option>
                                            <?php $num++; endforeach; ?>
                                        </select>
                                        <span class="input-group-text">del</span>
                                        <select class="form-control text-center" id="anio">
											<?php for($i=2023; $i<=date('Y'); $i++): ?>
												<option value="<?= $i ?>" <?= $anio == $i ? ' selected="selected"': '' ?>><?= $i ?></option>
											<?php endfor; ?>
										</select>
                                        <button type="button" class="btn btn-new-info" id="btnGrafica"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <canvas id="grafica" style="width: 100%; height: 400px; overflow: visible;"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="card">
                        <div class="card-body border-bottom text-center">
                            <span class="text-success totVentas fs-4 m-1"></span>
                            <span class="numVentas fs-4 m-1"></span>
                            <span class="ventasContado fs-4 m-1"></span>
                            <span class="ventasCredito fs-4 m-1"></span>
                            <span class="ventasGeneral fs-4 m-1"></span>
                            <span class="ventasFrecuente fs-4 m-1"></span>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom filtroFechas">
                                <div class="col-md-4 col-12">
                                    <div class="input-group input-daterange">
                                        <span class="input-group-text">Del</span>
                                        <input type="date" id="desde" class="form-control" value="<?= date('Y-m-01') ?>"/>
                                        <span class="input-group-text">al</span>
                                        <input type="date" id="hasta" class="form-control" value="<?= date('Y-m-d') ?>" max="<?= date('Y-m-d') ?>"/>
                                        <button type="button" class="btn btn-new-info" id="btnBuscar"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl_ventas" class="table">
                                    <thead class="table-light">
                                        <tr class="text-center">
                                            <th>Fecha Inicia</th>
                                            <th>Fecha Finaliza</th>
                                            <th>Usuario</th>
                                            <th>Cliente</th>
                                            <th>Folio</th>
                                            <th>Tipo</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/Chart.js/Chart.min.js"></script>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/Chart.js/chartjs-plugin-datalabels.min.js"></script>
    <?php include 'footer.phtml'; ?>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                id_cliente = 0,
                desde = $('#desde').val()
                hasta = $('#hasta').val();

            getItems('tbl_ventas', desde, hasta)

            meses = ['', 'ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE']
            mes = $('#mes').val()
            anio = $('#anio').val()
		    txtTitle = 'VENTAS DURANTE ' + meses[mes] + ' DEL ' + anio + ' POR DÍA'
            labels = []
            data = []
            colors = []
            totalVentas = 0
            <?php 
                $colors = ['#836AF9', '#f1a929', '#1ed3be', '#ed7f37', '#58da3e', '#299AFF', '#5276a7', '#8976dc', '#08659f', '#f0b3ec', '#98356b', '#ff4961'];
                $ultimoDia = intval(date('d', strtotime("$anio-$mes-01 + 1 month - 1 day")));
                for($dia = 1; $dia <= $ultimoDia; $dia++):
                    $objDia = array_filter($ventas, function($venta) use ($dia) {
                        return intval(date('d', strtotime($venta->fecha))) == $dia;
                    });

                    $color = $colors[intval(rand(0, count($colors)-1))];
                    $venta_dia = 0;
                    foreach($objDia as $obj):
                        $venta_dia = $obj->total;
                    endforeach;
            ?>
                    labels.push(<?= $dia ?>);
                    data.push(<?= $venta_dia ?>);
                    totalVentas += <?= $venta_dia ?>;
                    colors.push('<?= $color ?>')
                <?php endfor; ?>
            console.log(labels)
            var ctx = document.getElementById('grafica');
            var chart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: 'INGRESO',
                        backgroundColor: colors,
                        data: data,
                        datalabels: {
                            anchor: 'middle'
                        }
                    }]
                },
                plugins: [ChartDataLabels],
                options: {
                    responsive: true,
                    legend: {
                        position: 'bottom',
                        display: false,
                        onHover: function(event, item) {
                            this.chart.data.datasets[0].backgroundColor.forEach((color, index, colors) => {
                                colors[index] = index === item.index || color.length === 9 ? color : color + '4D';
                            });
                            this.chart.update();
                        },
                        onLeave: function() {
                            this.chart.data.datasets[0].backgroundColor.forEach((color, index, colors) => {
                                colors[index] = color.length === 9 ? color.slice(0, -2) : color;
                            });
                            this.chart.update();
                        }
                    },
                    title: {
                        display: true,
                        text: txtTitle,
                        fontSize: 16,
                        padding: 20
                    },
                    tooltips: {
                        callbacks: {
                            label: function(item, data) {
                                dataset = data.datasets[item.datasetIndex];
                                var label = dataset.label || '';
                                if(label) { label += ': '; }

                                return label += new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(dataset.data[item.index]);;
                            }
                        }
                    },
                    plugins: {
                        datalabels: {
                            backgroundColor: function(context) {
                                return context.dataset.backgroundColor;
                            },
                            borderColor: 'white',
                            borderRadius: 25,
                            borderWidth: 1,
                            color: 'white',
                            display: function(context) {
                                var dataset = context.dataset;
                                var count = dataset.data.length;
                                var value = dataset.data[context.dataIndex];
                                total = context.dataset.data.reduce((a, b) => a+b);

                                return Math.round(value / total * 100);
                            },
                            font: {
                                weight: 'bold'
                            },
                            padding: 6,
                            formatter: function(value, context) {
                                total = context.chart.data.datasets[0].data.reduce((a, b) => a+b);
                                return parseFloat(value / total * 100).toFixed(1) + '%';
                            },
                        },
                    }
                },
            });

            $('.totVentas').html('Total: $'+parseFloat(totalVentas).toFixed(2))
            $('.numVentas').html('No. ventas: <?= $numVentas ?>')
            $('.ventasContado').html('Ventas Contado: <?= $contado ?>')
            $('.ventasCredito').html('Ventas a Crédito: <?= $credito ?>')
            $('.ventasGeneral').html('Ventas Público General: <?= $general ?>')
            $('.ventasFrecuente').html('Ventas Cliente Frecuente: <?= $frecuente ?>')

            $('#btnBuscar').click(function(e){
                e.preventDefault()
                desde = $('#desde').val()
                hasta = $('#hasta').val()
                getItems('tbl_ventas', desde, hasta)
            })

            $('#btnGrafica').click(function(e){
                e.preventDefault()
                mes = $('#mes').val()
                anio = $('#anio').val()
                if(!'<?= $_SERVER['REQUEST_URI'] ?>'.endsWith('/reporte/periodo/'+mes+'/'+anio)) {
                    window.location.href = '<?= URL_ROOT ?>/reporte/periodo/'+mes+'/'+anio;
                }
            })

            function getItems(tbl, desde, hasta){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable(tbl, desde, hasta)
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl, desde, hasta){
                if($('#'+tbl).length){
                    $('#'+tbl).DataTable({
                        ajax:{
                            url: apiUrl+'venta/getAll/'+desde+'/'+hasta,
                            type: 'GET',
                        },
                        columns: [
                            {data: 'fecha_inicia'},
                            {data: 'fecha_fin'},
                            {data: 'usuario'},
                            {data: 'cliente'},
                            {data: 'folio'},
                            {data: 'tipo'},
                            {data: 'total'}
                        ],
                        columnDefs: [ 
                            {
                                targets: 0,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column">' +
                                            '<span >' +
                                                full['fecha_inicia'] +
                                            '</span>' +
                                            '<small class="emp_post text-muted">' +
                                            full['hora'] +
                                            '</small>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                            {
                                targets: 6,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column text-end">' +
                                            '<span > $' +
                                                full['total'] +
                                            '</span>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                        ],
                        order: [[0, 'desc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'<?= URL_ROOT ?>/spanish.json'
                        },
                        initComplete: function () {
                            var label = $('<label for="cuantos">Mostrar</label>').appendTo('#tbl_ventas_length');
                            var selectCount = $('<select id="cuantos" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>')
                                .appendTo('#tbl_ventas_length').on('change', function () {
                                    tipo = $('#tipo').val();
                                    $('#tbl_ventas').DataTable().page.len( $(this).val() ).draw();
                                    $('#tipo').val(tipo).trigger('change');
                                });

                            this.api()
                                .columns(5)
                                .every(function () {
                                var column = this;
                                
                                var select = $(
                                    '<select id="tipo" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"><option value=""> Todos </option></select>'
                                    )
                                    .prependTo('#tbl_ventas_length')
                                    .on('change', function () {
                                        $('#tbl_ventas').DataTable().column(5).search(
                                            $('#tipo').val()
                                        ).draw();
                                    });
                                var label = $('<label for="tipo">Tipo</label>').prependTo('#tbl_ventas_length');
                                            
                                column
                                    .data()
                                    .unique()
                                    .sort()
                                    .each(function (d, j) {
                                        select.append('<option value="' + d + '" class="text-capitalize">' + d + '</option>');
                                    });
                                });

                            $('#tbl_ventas_length label:eq(1)').addClass('hidden');
                        }
                    });
                }
            }

        });
    </script>
</html>
