<?php 
	include 'header.phtml';
    define('MOD_BITACORA_ACCIONES', 42);

    if(!in_array(MOD_BITACORA_ACCIONES, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	}
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom filtroFechas">
                                <div class="col-sm-4 col-md-6 col-12">
                                    <div class="input-group input-daterange">
                                        <span class="input-group-text">Del</span>
                                        <input type="date" id="desde" class="form-control" value="<?= date('Y-m-d') ?>"/>
                                        <span class="input-group-text">al</span>
                                        <input type="date" id="hasta" class="form-control" value="<?= date('Y-m-d') ?>" max="<?= date('Y-m-d') ?>"/>
                                        <button type="button" class="btn btn-new-info" id="btnBuscar"><i class="fas fa-search"></i> Buscar</button>
                                    </div>
                                </div>
                            </div>

                            <br>
                            <div class="card-datatable table-responsive pt-0 " >
                                <table id="tbl-log" class="table">
                                    <thead class="table-light">
                                        <tr>
                                            <th>Fecha</th>
                                            <th>Usuario</th>
                                            <th>Descripción</th>
                                            <th>Adicional</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <?php include 'footer.phtml';?>

    <script>

    var apiUrl = '<?= URL_ROOT ?>/',
        desde = $('#desde').val(),
        hasta = $('#hasta').val();

        getItems('tbl-log', desde, hasta);

        $('#btnBuscar').on('click', function(){
            desde = $('#desde').val()
            hasta = $('#hasta').val()
            getItems('tbl-log', desde, hasta);
        });

        function getItems(tbl, desde, hasta){
            cleanTable(tbl);
            $('#'+tbl+' tbody').empty();
            createTable(tbl, desde, hasta);
        }

        function cleanTable(tbl){
            if($.fn.dataTable.isDataTable('#'+tbl)){
                table = $('#'+tbl).DataTable();
                table.destroy();
            }
        }

        function createTable(tbl, desde, hasta){
            if($('#'+tbl).length){
                $('#'+tbl).DataTable({
                    ajax:{
                        url: apiUrl+'seg_log/get/'+desde+'/'+hasta,
                        type: 'GET',
                    },
                    columns: [
                        {data: 'fecha'},
                        {data: 'usuario'},
                        {data: 'descripcion'},
                        {data: 'adicional'}
                    ], 
                    columnDefs: [ 
                        {
                            targets: 0,
                            render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column">' +
                                        '<span >' +
                                            full['fecha'] +
                                        '</span>' +
                                        '<small class="emp_post text-muted">' +
                                        full['hora'] +
                                        '</small>' +
                                    '</div>';
                                return salida;
                            }
                        },                          
                    ],
                    order: [[0, 'desc']], 
                    dom:
                        '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                        '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                        '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                        '>t' +
                        '<"d-flex justify-content-between mx-2 row mb-1"' +
                        '<"col-sm-12 col-md-6"i>' +
                        '<"col-sm-12 col-md-6"p>' +
                        '>'
                        ,
                    language: {
                        url:'<?= URL_ROOT ?>/spanish.json'
                    },
                });
            }
        }


    </script>

</html>