<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item me-auto"><a class="navbar-brand" href="<?= URL_ROOT ?>/temp/index.html">
                <span class="brand-logo">
                <a href="usuarios"><img src="<?= URL_ROOT ?>/app-assets/images/logo/logo-light.png" alt="" height="30"></a>
                </span>
                <span class="brand-text"><strong>Inventario</strong></span></a></li>
            <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pe-0" data-bs-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
        </ul>
    </div>
    <div class="shadow-bottom"></div>
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <?php
                    $modulos = $_SESSION['permisos'];
                    foreach ($modulos as $modulo) {
                        $urlModulo = '#';
                        if($modulo->accionesUrl == 0){
                            $urlModulo = URL_ROOT.$modulo->url;
                            if($modulo->url != ''){
                                // echo '<li class=" nav-item"><a class="d-flex align-items-center" href="'.$urlModulo.'"><i data-feather="'.$modulo->icono_nuevo.'"></i><span class="menu-title text-truncate" data-i18n="Kanban">'.$modulo->nombre.'</span></a></li>';
                                echo '<li class=" nav-item"><a class="d-flex align-items-center" href="'.$urlModulo.'"><i class="fas fa-'.$modulo->icono_nuevo.'"></i><span class="menu-title text-truncate" data-i18n="Kanban">'.$modulo->nombre.'</span></a></li>';
                            }
                        }else{
                ?>
                            <li class=" nav-item">
                                <a class="d-flex align-items-center" href="<?= $urlModulo ?>">
                                    <i class="fas fa-<?php echo $modulo->icono?>"></i>
                                    <span class="menu-title text-truncate" data-i18n="Kanban"><?php echo $modulo->nombre ?></span>
                                </a>
							    <ul class="menu-content">
                                    <?php
                                        $acciones = $modulo->acciones;
                                        foreach ($acciones as $accion) {
                                            $nombre = str_replace("Ver ", "", $accion->nombre);
                                            if($accion->url != ""){
                                    ?>          
                                                <li>
                                                    <a href="<?= URL_ROOT.$accion->url ?>">
                                                        <i class="fas fa-<?=$accion->iconoA?>"></i>
                                                        <?= $nombre?>
                                                    </a>
                                                </li>
                                    <?php
                                            }
                                        }
                                    ?>
                                </ul>
                            </li>
                            <?php
                        }
                    }
                ?>
            </ul>
        </div>
    </div>
</div>
<!-- END: Main Menu-->