<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow menu-expanded" data-scroll-to-active="true">
    <div class="navbar-header text-center">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mx-auto"><a class="navbar-brand" href="<?= URL_ROOT ?>/venta/cliente">
                <?php $nombre = explode(' ', $_SESSION['sucursal_nombre']); ?>
                <span class="brand-text"><strong><?= $nombre[0].' '.$nombre[1]?><br><?= isset($nombre[2]) ? $nombre[2] : '' ?></strong></span></a>
            </li>
         </ul>
        <div class="user-profile">
            <div class="profile-img">
                <?php if($_SESSION['foto']) : ?>
                    <img class="round" src="<?= URL_DATA ?>empleado/foto<?= $id ?>.jpg" alt="avatar" width="40" height="70">
                <?php else: ?>
                    <img class="round" src="<?= URL_DATA ?>empleado/profile.png" alt="avatar" width="40" height="70">
                <?php endif; ?>
			</div>
			<div class="profile-text">
				<h5><b><?= $_SESSION['usuario']->nombre ?></b></h5>
				<a href="#" class="btnSwitch" data-toggle="tooltip" title="Cambiar Usuario" style="color:rgba(8, 150, 245, 0.7);"><i class="fas fa-exchange-alt"></i></a>
				<a href="<?= URL_ROOT ?>/usuario/logout" class="" data-toggle="tooltip" title="Cerrar Sesión" style="color: rgba(252, 5, 5, 0.7);"><i class="me-50" data-feather="power"></i></a>
			</div>
		</div>
    </div>
    <!-- <br><br><br><br><br><br><br><br><hr> -->
    <!-- <div class="shadow-bottom"></div> -->
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <?php
                $modulos = $_SESSION['permisos'];
                foreach ($modulos as $modulo) {
                    $urlModulo = '#';
                    if($modulo->accionesUrl == 0){
                        $urlModulo = URL_ROOT.$modulo->url;
                        if($modulo->url != ''){
                            echo '<li class=" nav-item"><a class="d-flex align-items-center" href="'.$urlModulo.'"><i class="'.$modulo->icono.'"></i><span class="menu-title text-truncate" data-i18n="Kanban">'.$modulo->nombre.'</span></a></li>';
                        }
                    }else{
            ?>
                        <li class=" nav-item">
                            <a class="d-flex align-items-center" href="<?= $urlModulo ?>">
                                <i class="<?php echo $modulo->icono?>"></i>
                                <span class="menu-title text-truncate" data-i18n="Kanban"><?php echo $modulo->nombre ?></span>
                            </a>
                            <ul class="menu-content">
                                <?php
                                    $acciones = $modulo->acciones;
                                    foreach ($acciones as $accion) {
                                        $nombre = str_replace("Ver ", "", $accion->nombre);
                                        if($accion->url != ""){
                                ?>          
                                            <li>
                                                <a href="<?= URL_ROOT.$accion->url ?>">
                                                    <i class="fas fa-<?=$accion->iconoA?>"></i>
                                                    <?= $nombre?>
                                                </a>
                                            </li>
                                <?php
                                        }
                                    }
                                ?>
                            </ul>
                        </li>
                        <?php
                    }
                }
            ?>
        </ul>
    </div>
</div>