<?php 
	include 'header.phtml';
    define('MOD_VER',	6);
    define('MOD_ADD',	7);
    define('MOD_EDIT',	8);
    define('MOD_DEL',	9);

    if(!in_array(MOD_VER, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom alignRight">
                                <div class="dt-buttons btn-group">
                                    <?php if(in_array(MOD_ADD, $permisos)) : ?>
                                        <button type="button "id="btnAdd" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-pers" tabindex="0" 
                                            aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                            data-target="#frm-pers">
                                            <i class="fas fa-plus"></i>&nbsp;&nbsp;<span>Agregar</span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <div class="card-datatable table-responsive pt-0">
                            <table id="tbl-sucursal" class="table">
                                <thead class="table-light">
                                    <tr class="text-center">
                                        <th>No. Sucursal</th>
                                        <th>Nombre</th>
                                        <th>Dirección</th>
                                        <th>Teléfono</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>

                        <div class="modal modal-slide-in fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-sucursal" >
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title text-uppercase"></h4>
                                    </div>
                                    <div class="modal-body flex-grow-1 form-horizontal">
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-nombre">Nombre de Sucursal</label>
                                            <input type="text" class="form-control" id="suc-nombre" minlength="4" />
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-telefono">Teléfono</label>
                                            <input type="text" id="suc-telefono" class="form-control" minlength="4" />
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-calle">Calle</label>
                                            <input type="text" id="suc-calle" class="form-control" minlength="4" />
                                        </div>
                                        <div class="mb-1 form-group row">
                                            <label class="col-sm-3 form-label input-sm fw-bolder fs-5" for="suc-no_ext">No. Exterior</label>
                                            <div class="col-sm-3">
                                                <input type="text" id="suc-no_ext" class="form-control" minlength="4" />
                                            </div>
                                            <label class="col-sm-3 form-label input-sm fw-bolder fs-5" for="suc-no_int">No. Interior</label>
                                            <div class="col-sm-3">
                                                <input type="text" id="suc-no_int" class="form-control" minlength="4" />
                                            </div>
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-colonia">Colonia</label>
                                            <input type="text" id="suc-colonia" class="form-control" minlength="4" />
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-municipio">Municipio</label>
                                            <input type="text" id="suc-municipio" class="form-control" minlength="4" />
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-estado">Estado</label>
                                            <input type="text" id="suc-estado" class="form-control" minlength="4" />
                                        </div>
                                        <div class="mb-1">
                                            <label class="form-label fw-bolder fs-5" for="suc-codigo_postal">Código Postal</label>
                                            <input type="text" id="suc-codigo_postal" class="form-control" minlength="4" />
                                        </div>
                                        <hr>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="buttonsEnd">
                                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-success mb-1 data-submit" id="btnSave">Guardar</button>
                                            <input type="hidden" id="suc-id" value="0">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <!--Modal para eliminar a un usuario, solicita motivo de la baja y observaciones -->
                        <div class="modal modal-slide-in modal-danger fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-del">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title text-uppercase">eliminar sucursal</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de eliminar la sucursal <strong></strong>?
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="buttonsEnd">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-danger me-1" id="btnEliminar">Eliminar</button>
                                            <input  type="hidden" id="suc_id_del" value="0">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para eliminar a un usuario -->

                        <!--Modal para activar a un usuario, solicita confirmación para activar al usuario -->
                        <div class="modal modal-slide-in modal-success fade" id="frm-activar-user">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title" id="exampleModalLabel">Activar Usuario</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de cambiar el estatus de <strong></strong> a activo?
                                        </div><hr><br><br>
                                        <div class="buttonsFrmUser">
                                            <input  type="hidden" id="id_user_activar" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-success me-1" id="btnActivar">Activar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para activar a un usuario -->
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml'; ?>
    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/';

            getItems('tbl-sucursal')

            <?php if(in_array(MOD_ADD, $permisos)) :  ?>
                $('#btnAdd').click(function(){
                    clear()
                    // $('#frm-sucursal').removeClass('modal-info')
                    // $('#frm-sucursal').addClass('modal-success')
                    $('#frm-sucursal h4').html('agregar sucursal')
                    $('#frm-sucursal').modal('show')
                })

                $('#btnSave').click(function(){
                    data = {};
                    $.each($('#frm-sucursal input'), function(index, elem) {
                        ide = $(elem).attr('id').replace('suc-','')
                        data[ide] = $.trim($(elem).val())
                    });
                    if($('#suc-id').val() == 0){
                        $.post(apiUrl+'sucursal/add/', data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se ha agregado una nueva sucursal.")
                                getItems('tbl-sucursal')
                                $('#frm-sucursal').modal('hide')
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos agregar la sucursal.")
                            }
                        }, 'json')
                    }else{
                        $.post(apiUrl+'sucursal/edit/'+id, data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se editó la información de la sucursal.")
                                getItems('tbl-sucursal')
                                $('#frm-sucursal').modal('hide')
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos editar la información de la sucursal.")
                            }
                        }, 'json')
                    }
                })
            <?php endif; ?>

            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                $('#tbl-sucursal').on('click', '#btnEdit', function(){
                    // $('#frm-sucursal').removeClass('modal-success')
                    // $('#frm-sucursal').addClass('modal-info')
                    $('#frm-sucursal h4').html('editar sucursal')
                    id = $(this).data('id')
                    $('#suc-id').val(id)
                    console.log(id)
                    $.get(apiUrl+'sucursal/get/'+id, function(data){
                        $.each(data.result, function(index, elem){
                            $('#suc-'+index).val(elem)
                        })
                    },'json')
                    $('#frm-sucursal').modal('show')
                })
            <?php endif; ?>

            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                $('#tbl-sucursal').on('click', '#btnDel', function(){
                    id = $(this).data('id')
                    $('#frm-sucursal h5').html('<b>eliminar sucursal</b>')
                    $('#frm-del strong').html($(this).data('name'))
                    $('#suc_id_del').val(id)
                    $('#frm-del').modal('show')
                })

                $('#btnEliminar').click(function(){
                    id = $('#suc_id_del').val()
                    $.post(apiUrl+'sucursal/del/'+id, function(resp){
                        if(resp.response){
                            toastr["success"]("¡Listo!", "Se eliminó la sucursal.")
                            getItems('tbl-sucursal')
                            $('#frm-del').modal('hide')
                        }else{
                            toastr["error"]("¡Ocurrió un problema!", "No pudimos eliminar la sucursal.")
                        }
                    },'json')
                })
            <?php endif; ?>

            function clear(){
                $.each($('#frm-sucursal input'), function(index, elem){
                    ide = $(elem).attr('id')
                    $('#'+ide).val('')
                })
                $('#suc-id').val(0)
            }

            function getItems(tbl){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable()
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl){
                if($('#tbl-sucursal').length){
                    $('#tbl-sucursal').DataTable({
                        ajax:{
                            url: apiUrl+'sucursal/getAllDataTable',
                            type: 'GET',
                        },
                        columns: [
                            {data: 'id'},
                            {data: 'nombre'},
                            {data: 'direccion'},
                            {data: 'telefono'},
                            {data: ''}
                        ],
                        columnDefs: [
                            {
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['id']
                                    mostrar = id != <?= $_SESSION['sucursal_id']?> ? '' : 'hidden';
                                    return (
                                        '<div class="text-center">' +
                                            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                                                '<button type="button" id="btnEdit" class="btn btn-outline-new-info btn-sm btnEdit" data-id="'+id+'" data-toggle="tooltip" title="Editar" style="margin-right:4px;">'+
                                                    feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            <?php if(in_array(MOD_DEL, $permisos)) : ?>
                                                '<button type="button" id="btnDel" class="btn btn-outline-danger btn-sm '+mostrar+'" data-id="'+id+'" data-name="'+full['nombre']+'" data-toggle="tooltip" title="Eliminar" style="margin-right:4px;">'+
                                                    feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                        '</div>'
                                    );
                                }
                            },
                        ],
                        order: [[0, 'asc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'../spanish.json'
                        },
                    });
                }
            }

        });
    </script>
</html>