<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title><?= 'Ticket | ' . SITE_NAME ?></title>
		<style>
			*{
				margin: 0px;
				padding: 0px;
				box-sizing: border-box;

			}
			.ticket{
				max-width: 256px;
				padding: 1rem;
			}
			body{
				display: grid;
				place-items: center;
			}
		</style>
		<style type="text/css" media="print">
			@media print {
				@page {
					margin: 0;
				}
				body {
					margin: 0;
					color: #000;
					background-color: #fff;
					display: grid;
					place-items: center;
					box-sizing: border-box;
					
				}
				header, footer, aside, nav, form, iframe, .menu, .hero, .adslot {
					display: none;
				}
				#kt_footer, #kt_aside, #kt_aside_footer, #buscador-registro, #card-header, #kt_scrolltop, #kt_header, #kt_toolbar {
					display: none;
				}
				* {
					background-image: none !important;
				}
				svg {
					display: none !important;
				}
				img {
					height: 110px;
					margin-bottom: 5px;
				}
				.name-register{
					font-size: 1.9em;
					font-weight: bold;
					line-height: .5em;
				}
				.last-name-register{
					font-size: 1.7em;
					font-weight: bold;
					line-height: .8em;
				}
				.company-register{
					font-size: 1.3em;
					line-height: .5em;
				}
				.tipo-register{
					font-size: 1.3em;
					line-height: .5em;
					font-weight: bold;
				}
				#alerta-duplicado{
					display: none;
				}			
				.duplicado{
					display: none;
				}
				.id-register-number{
					font-size: 1.0em;
					line-height: .5em;
					margin-top: 4px;
				}
				.ticket{
					max-width: 256px;
					padding: 1rem;
				}
				
			}
		</style>
	</head>
	<body>
		<div class="ticket">
			<div class="row" style="text-align: center;">
				<img src="<?= URL_ROOT ?>/app-assets/images/logo/logo.png" class="img-ticket" alt="Logo" style="width: 90%;height: auto;">
			</div>
			<div class="row">
				<p>
					<?= $sucursal->calle.' '.$sucursal->no_ext ?><br>
					<?= $sucursal->colonia ?><br>
					<?= $sucursal->municipio.' '.$sucursal->estado ?><br>
					<?= $sucursal->codigo_postal ?><br>
					Tels: <?= $sucursal->telefono ?><br>
					<?= $venta->date ?><br>
					<?= $venta->hora ?><br><br>
					<b><?= $folio ?></b>
				</p>
				<small><?= $cliente->razon_social ?><br><?= $cliente->rfc ?></small>
			</div>
			<div class="row">
				<table class="table">
					<thead>
						<tr>
							<th>Cant</th>
							<th width="45%">Descripción</th>
							<th width="15%" style="text-align: end;">P.U</th>
							<th style="text-align: end;">SubT</th>
						</tr>
					</thead>
					<body>
						<?php foreach($detalles as $detalle) : ?>
							<tr>
								<td><small><?= $detalle->cantidad ?></small></td>
								<td width="45%"><small><?= $detalle->producto ?></small></td>
								<td width="15%" style="text-align: end;"><small><?= $detalle->precio ?></small></td>
								<td style="text-align: end;"><small><?= $detalle->total ?></small></td>
							</tr>
						<?php endforeach; ?>
					</body>
				</table>
			</div>
			<br>
			<div class="row">
				<table>
					<thead>
						<th width="85%"></th>
						<th></th>
					</thead>
					<tbody>
						<tr>
							<td style="font-style:italic;">Subtotal</td>
							<td style="text-align: end;">$<?= $venta->subtotal ?></td>
						</tr>
						<?php if($venta->descuento != 0) : ?>
							<tr>
								<td style="font-style:italic;">Descuento</td>
								<td style="text-align: end;"><?= $venta->descuento ?>%</td>
							</tr>
						<?php endif; ?>
						<tr>
							<td>Total</td>
							<td style="text-align: end;">$<?= $venta->total ?></td>
						</tr>
						<?php if($venta->tipo == 1) : ?>
							<?php if($venta->metodo == 1) : ?>
								<tr>
									<td>Pago</td>
									<td style="text-align: end;">$<?= $venta->recibido ?></td>
								</tr>
								<tr>
									<td>Cambio</td>
									<td style="text-align: end;">$<?= $venta->cambio ?></td>
								</tr>
								<tr>
									<td>Método pago: Efectivo</td>
								</tr>
							<?php elseif($venta->metodo == 3) : ?>
								<tr>
									<td>Método pago: Tarjeta</td>
								</tr>
							<?php elseif($venta->metodo == 4) : ?>
								<tr>
									<td>Método pago: Transferencia</td>
								</tr>
							<?php endif; ?>
						<?php else : ?>
							<?php if(isset($pagos)) : ?>
								<?php if(COUNT($pagos) != 0 ) : ?>
									<tr><td>Pagos realizados</td></tr>
									<?php 
										$pagado = 0;
										foreach($pagos as $pago) :
											$metodo = $pago->forma_pago == 1 ? 'Efectivo' : ($pago->forma_pago == 3 ? 'Tarjeta' : ($pago->forma_pago == 4 ? 'Transf' : ''));
											$pagado += $pago->monto;
									?>
										<tr>
											<td><?= $metodo?></td>
											<td style="text-align: end;">$<?= $pago->monto ?></td>
										</tr>
									<?php endforeach; ?>
									<tr>
										<td>Resta</td>
										<td style="text-align: end;">$<?= number_format(floatval($venta->total-$pagado), 2) ?></td>
									</tr>
								<?php endif; ?>
							<?php endif; ?>
							<tr>
								<td>Venta a crédito</td>
							</tr>
						<?php endif; ?>
					</tbody>
				</table>
			</div>
			<div class="row">
				<br>
				<p>
					Le atendió: <?= $atendio ?>
					
				</p>
				<br>
				<h3>** Conserve su ticket **</h3><br>
				<p style="text-align:justify;">
					<small>** En cambios y devoluciones únicamente con ticket, en la sucursal donde fue la compra y el producto en perfecto estado.<br>
					** Devoluciones únicamente válidas el mismo día y en cobro con tarjeta es menos comisión.</small>
				</p>
			</div>
			<div>
				<br>
				<p>
					** EN HERRAMIENTAS Y MATERIAL DE CORTE, NO HAY CAMBIOS NI DEVOLUCIONES.
				</p>
			</div>
		</div>
	</body>
</html>