<?php 
	include 'header.phtml';
    
    $lblUsu = $_SESSION['usuario']->nombre;
    $lockdown = $_SESSION['lockdown'];

    if(!in_array(MOD_USUARIOS, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom alignRight">
                                <div class="dt-buttons btn-group">
                                    <?php if(in_array(MOD_USUARIOS_ADD, $permisos)) :  ?>
                                        <button type="button "id="btnAdd" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-pers" tabindex="0" 
                                        aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                        data-target="#frm-pers">
                                        <i data-feather="user-plus"></i>&nbsp;&nbsp;<span>Agregar Usuario</span></button>

                                        &nbsp;&nbsp;<button type="button "id="btnTypeUser" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-type-user" tabindex="0" 
                                        aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                        data-target="#frm-tipos_usuarios">
                                        <i data-feather="user"></i>&nbsp;&nbsp;<span>Tipos de Usuario</span></button>
                                    <?php endif; ?>
                                    <!-- <?php if($_SESSION['user'] == 1 || $_SESSION['user'] == 2 || $_SESSION['user'] == 51) : ?>
                                        <?php if($lockdown == 0) : ?>
                                            &nbsp;&nbsp;<button id="btnLockdown" type="button" class="btn waves-effect waves-foat waves-light btn-success buttonModal"><i data-feather="check"></i> Desbloquear Sistema</button>
                                        <?php else: ?>
                                            &nbsp;&nbsp;<button id="btnLockdown" type="button" class="btn waves-effect waves-foat waves-light btn-danger buttonModal"><i data-feather="slash"></i> Bloquear Sistema</button>
                                        <?php endif; ?>
                                    <?php endif; ?> -->
                                </div>
                            </div>
                        <div class="card-datatable table-responsive pt-0">
                            <table id="tbl-usuarios" class="table">
                                <thead class="table-light">
                                    <tr>
                                    <th>No. Empleado</th>
                                    <th>Nombre</th>
                                    <th>Apellidos</th>
                                    <th>Tipo Usuario</th>
                                    <th>Tipo</th>
                                    <th>Estatus</th>
                                    <th style="text-align: center;">Acciones</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- Modal to add new user starts-->
                        <div class="modal modal-slide-in new-user-modal fade" data-bs-keyboard="false" id="frm-pers" >
                            <div class="modal-dialog modalMediano">
                                <form class="add-new-user modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                                    <div class="modal-header mb-1">
                                        <h5 class="modal-title"></h5>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                        <div class="mb-1"> <!-- Tipo Usuario -->
                                            <label class="form-label" for="cboTUsr">Tipo Usuario</label>
                                            <select id="cboTUsr" class="form-select" data-bs-toggle="tooltip" title="Tipo Usuario" ></select>
                                        </div>
                                        <div class="mb-1"> <!-- Nombre -->
                                            <label class="form-label" for="pers-nom">Nombre:</label>
                                            <input type="text" class="form-control dt-full-name" id="pers-nom" placeholder="Nombre" name="user-fullname"minlength="4" data-bs-toggle="tooltip" title="Nombre del Usuario" />
                                        </div>
                                        <div class="mb-1"> <!-- Apellidos -->
                                            <label class="form-label" for="pers-ape">Apellidos:</label>
                                            <input type="text" id="pers-ape" class="form-control dt-uname" placeholder="Apellidos" name="user-name" minlength="4" data-bs-toggle="tooltip" title="Apellidos del Usuario"/>
                                        </div>
                                        <div class="mb-1"> <!-- Email -->
                                            <label class="form-label" for="email">Email:</label>
                                            <input type="email" id="email" class="form-control dt-contact" placeholder="Correo Electrónico" name="user-company" aria-describedby="emailHelp" data-bs-toggle="tooltip" title="Correo del Usuario"/>
                                        </div>

                                        <div class="mb-1 form-group row" id="UsuarioPass" > <!-- Usuario - Contraseña-->
                                            <label for="user" class="form-label" id="labLogBlink">Usuario:</label>
                                            <div class="mb-1 col-md-12">
                                                <input  id="user" type="text" class="form-control input-sm" minlength="4" placeholder="Nombre del usuario para entrar al sistema" data-bs-toggle="tooltip" title="Usuario">
                                            </div>
                                            <label  for="kypass" class="form-label">Contraseña:</label>
                                            <div class="input-group">
                                                <div class="input-group input-group-merge form-password-toggle">
                                                    <input type="password" class="form-control form-control-merge" id="kypass" name="login-password" tabindex="2" placeholder="Contraseña" aria-describedby="login-password"/>
                                                    <span class="input-group-text cursor-pointer" ><i data-feather="eye"></i></span>
                                                </div>
                                            </div>
                                            <hr>
                                            <label  for="kypassConf" class="form-label mb-1">Confirmar Contraseña:</label>
                                            <div class="mb-1 col-md-12"> 
                                                <div class="input-group">
                                                    <div class="input-group input-group-merge form-password-toggle">
                                                        <input type="password" class="form-control form-control-merge" id="kypassConf"  tabindex="2" placeholder="Confirmar Contraseña" aria-describedby="login-password"/>
                                                        <span class="input-group-text cursor-pointer" ><i data-feather="eye"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <hr>
                                        <div class="mb-1"> <!-- Calle -->
                                            <label for="calle" class="col-sm-3 form-label input-sm">Calle:</label>
                                            <input type="text" id="calle" class="form-control input-sm" placeholder="Calle" data-bs-toggle="tooltip" title="Calle">
                                        </div>
                                        
                                        <div class="mb-1">
                                            <label for="colon" class="col-sm-3 form-label input-sm">Colonia:</label>
                                            <input type="text" id="colon" class="form-control input-sm" placeholder="Colonia" data-bs-toggle="tooltip" title="Colonia">
                                        </div>

                                        <div class="mb-1 form-group row"> <!-- Número Exterior - Número Interior -->
                                            <label for="dr-num" class="col-sm-2 form-label input-sm">No. Exterior:</label>
                                            <div class="col-sm-4">
                                            <input type="text" id="dr-num" class="form-control input-sm" placeholder="Numero Exterior" data-bs-toggle="tooltip" title="Número Exterior">
                                            </div>
                            
                                            <label for="dr-num-int" class="col-sm-2 form-label input-sm">No. Interior:</label>
                                            <div class="col-sm-4">
                                            <input type="text" id="dr-num-int" class="form-control input-sm" placeholder="Numero Interior" data-bs-toggle="tooltip" title="Número Interior">
                                            </div>
                                        </div>

                                        <div class="mb-1"> <!-- Municipio - Estado -->
                                            <label for="municipio" class="col-sm-3 form-label input-sm">Municipio:</label>
                                            <!-- <div class="col-sm-3"> -->
                                            <input type="text" id="municipio" class="form-control input-sm" placeholder="Municipio" data-bs-toggle="tooltip" title="Municipio">
                                        </div>

                                        <div class="mb-1">
                                            <label for="estado" class="col-sm-3 form-label input-sm">Estado:</label>
                                            <input type="text" id="estado" class="form-control input-sm" placeholder="Estado" data-bs-toggle="tooltip" title="Estado">
                                        </div>
                                        <!-- </div> -->

                                        <div class="mb-1 form-group row"> <!-- Teléfono - Celular -->
                                            <label for="pers-tel" class="col-sm-2 form-label input-sm">Teléfono:</label>
                                            
                                            <div class="col-sm-4">
                                            <!-- <div class="input-group-prepend">
                                                <span class="input-group-text"> MX (+52)</span>
                                            </div> -->
                                            <input type="tel" id="pers-tel" class="form-control input-sm numeric" pattern="[0-9]{10}" placeholder="Telefono" data-bs-toggle="tooltip" title="Teléfono">
                                            </div>
                                        
                                            <label for="pers-cel" class="col-sm-2 form-label input-sm">Celular:</label>
                                            <div class="col-sm-4">
                                            <input type="tel" id="pers-cel" class="form-control input-sm numeric" pattern="[0-9]{10}" placeholder="Celular" data-bs-toggle="tooltip" title="Celular">
                                            </div>
                                        </div>
                                        
                                        <div class="mb-1 form-group row"> <!-- Teléfono Adicional - Número de empleado. -->
                                            <label for="pers-tel-add" class="col-sm-2 form-label input-sm">Teléfono Adicional:</label>
                                            <div class="col-sm-4">
                                            <input type="tel" id="pers-tel-add" class="form-control input-sm numeric" pattern="[0-9]{10}" placeholder="Telefono Adicional" data-bs-toggle="tooltip" title="Télefono adicional">
                                            </div>

                                            <label for="pers-emple" class="col-sm-3 form-label input-sm">No. Empleado:</label>
                                            <div class="col-sm-3">
                                            <input type="text" id="pers-emple" class="form-control input-sm numeric" maxlength="10" placeholder="Número Empleado" data-bs-toggle="tooltip" title="Número Empleado">
                                            </div>
                                        </div>

                                        <div class="mb-1 form-group"> <!-- Observaciones -->
                                            <label for="observ" class="col-sm-4 form-label input-sm">Observaciones:</label>
                                            <div class="col-sm-15">
                                                <textarea id="observ" class="form-control" rows="3" placeholder="Observaciones" data-bs-toggle="tooltip" title="Observaciones"></textarea>
                                            </div>
                                        </div>        

                                        <div class="buttonsFrmUser">
                                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-warning mb-1 data-submit" id="btnSave">Guardar</button>
                                            <input type="hidden" id="pers-id" value="0">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- Modal to add new user Ends-->

                        <!-- Modal para tipos de usuario -->
                        <div class="modal fade" id="frm-type-user">
                            <div class="modal-dialog modalMediano">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4>Tipos de usuarios registrados</h4>
                                    </div>
                                    <!-- <div class="modal-body"> -->
                                    <div class="form-horizontal">
                                        <div class="modal-body">
                                            <div class="alignRight">
                                                <button id="btnNewTypeUser" type="button" class="btn btn-outline-secondary waves-effect waves-foat waves-light open-modal "><i data-feather="plus"></i>&nbsp;&nbsp;Agregar tipo de usuario</button>
                                            </div>
                                            <table id="tbl-TypeUser" class="table table-condensed table-hover table-striped table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>Tipo de usuario</th>
                                                        <th style="text-align: center;">Acciones</th>
                                                    </tr>
                                                </thead>
                                                <tbody></tbody>
                                            </table>
                                        </div>
                                    </div>
                                        <!-- </div> -->
                                    <div class="modal-footer">
                                        <div class="buttonsFrmUser">
                                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                            <button id="btnClose" type="button" class="btn btn-danger mb-1">Salir</button>
                                            <input type="hidden" id="pers-id" value="0">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Termina modal tipos de usuario -->

                        <!--Modal para agregar/editar tipo de usuario -->
                        <div class="modal fade" id="frm-type-user-acciones">
                            <div class="modal-dialog modalMediano">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4></h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <label for="descripcion-nuevo-perfil" class="col-sm-3 control-label input-sm"><h5>Tipo de usuario</h5></label>
                                                <input type="text" id="descripcion-nuevo-perfil" class="form-control input-sm" placeholder="Agregue el nombre del nuevo tipo de usuario">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="buttonsFrmUser">
                                            <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                            <button id="btnSaveNewPerfil" type="button" class="btn btn-warning mb-1">Registrar</button>
                                            <button id="btnUpdatePerfil" type="button" class="btn btn-warning mb-1">Actualizar</button>
                                            <button id="btnDelPerfil" type="button" class="btn btn-danger mb-1">Inactivar</button>
                                            <input type="hidden" id="id_type_user" value="0">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Termina modal para agregar/editar tipo de usuario -->

                        <!--Modal para eliminar a un usuario, solicita motivo de la baja y observaciones -->
                        <div class="modal modal-slide-in modal-danger fade" id="frm-del-user">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title" id="exampleModalLabel">Inactivar Usuario</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de inactivar a <strong></strong>?
                                        </div><br>
                                        <div class="mb-2">
                                            <label for="motivo_baja" class="form-label"><h5>Motivo Separación</h5></label>
                                            <select name="motivo_baja" id="motivo_baja" class="select2 form-select">
                                            <option value="0" selected disabled>Seleccione</option>
                                            <option value="1">Renuncia Voluntaria</option>
                                            <option value="2">Rescisión Laboral</option>
                                            <option value="3">Término de Contrato</option>
                                            <option value="4">Defunción</option>
                                            <option value="5">Jubilación</option>
                                            <option value="6">Pensión</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label for="observaciones_baja" class="form-label"><h5>Observaciones</h5></label>
                                            <textarea id="observaciones_baja" name="observaciones_baja" rows="5" cols="50" placeholder="Observaciones de la baja del usuario"></textarea>
                                        </div><br><br>
                                        <div class="buttonsFrmUser">
                                            <input  type="hidden" id="id_user_del" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-danger me-1" id="btnInactivar">Inactivar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para eliminar a un usuario -->

                        <!--Modal para activar a un usuario, solicita confirmación para activar al usuario -->
                        <div class="modal modal-slide-in modal-success fade" id="frm-activar-user">
                            <div class="modal-dialog">
                                <form class="modal-content pt-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    <div class="modal-header mb-1">
                                        <h4 class="modal-title" id="exampleModalLabel">Activar Usuario</h4>
                                    </div>
                                    <div class="modal-body flex-grow-1">
                                        <div class="mb-1">
                                            ¿Estas seguro de cambiar el estatus de <strong></strong> a activo?
                                        </div><hr><br><br>
                                        <div class="buttonsFrmUser">
                                            <input  type="hidden" id="id_user_activar" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                            <button type="button" class="btn btn-success me-1" id="btnActivar">Activar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!--Termina modal para activar a un usuario -->

                        <!-- Modal permisos -->
                        <div id="frm-permisos" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h3 class="modal-title"><i class="feather-16" style="color: black;" data-feather="lock"></i><span>Permisos de Usuario</span></h3>
                                        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
                                    </div>
                                    <div class="modal-body">
                                        <div class="card-columns" style="column-count:2">
                                        <?php 
                                            $modulos = $todo->model->seg_modulo->getAll()->result; 
                                            foreach ($modulos as $modulo) :  ?>
                                                <?php if($modulo->nombre != 'Recibos Nomina') :?>
                                                    <div>
                                                        <div class="card">
                                                            <div class="card-header nombreModulo">
                                                                <h5 class="card-title"><?= $modulo->nombre ?></h5>
                                                                <div class="heading-elements">
                                                                    <ul class="list-inline mb-0">
                                                                        <li><a data-action="collapse"><i data-feather="chevron-down"></i></a></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                            <div class="card-content collapse show">
                                                                <div class="card-body cardBody">
                                                                    <?php 
                                                                        $acciones = $todo->model->seg_accion->getByModulo($modulo->id_modulo)->result; 
                                                                        foreach ($acciones as $accion) : ?>
                                                                            <input type="checkbox" id="chkperm-<?= $accion->id_accion ?>" value="<?= $accion->id_accion ?>" class="filled-in checkPermiso">	
                                                                            <label for="chkperm-<?= $accion->id_accion ?>"><?= $accion->nombre ?></label><br>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endforeach;
                                        ?>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <input type="hidden" id="perm_user_id" value="0">
                                        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Termina modal permisos -->

                        <!-- Modal permisos para tipo de usuario-->
                        <div id="frm-permisos-type-user" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h3 class="modal-title"><i class="feather-16" style="color: black;" data-feather="lock"></i><span></span></h3>
                                        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
                                    </div>
                                    <div class="modal-body">
                                        <div class="card-columns" style="column-count:2">
                                        <?php 
                                            $modulos = $todo->model->seg_modulo->getAll()->result; 
                                            foreach ($modulos as $modulo) :  ?>
                                                <?php if($modulo->nombre != 'Recibos Nomina') :?>
                                                    <div>
                                                        <div class="card">
                                                            <div class="card-header nombreModulo">
                                                                <h5 class="card-title"><?= $modulo->nombre ?></h5>
                                                                <div class="heading-elements">
                                                                    <ul class="list-inline mb-0">
                                                                        <li><a data-action="collapse"><i data-feather="chevron-down"></i></a></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                            <div class="card-content collapse show">
                                                                <div class="card-body cardBody">
                                                                    <?php 
                                                                        $acciones = $todo->model->seg_accion->getByModulo($modulo->id_modulo)->result; 
                                                                        foreach ($acciones as $accion) : ?>
                                                                            <input type="checkbox" id="chkpermTypeUser-<?= $accion->id_accion ?>" value="<?= $accion->id_accion ?>" class="filled-in checkPermTypeUser">	
                                                                            <label for="chkpermTypeUser-<?= $accion->id_accion ?>"><?= $accion->nombre ?></label><br>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endif; ?>

                                            <?php endforeach;?>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <input type="hidden" id="perm_user_id" value="0">
                                        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Termina modal permisos -->

                        <!-- Modal foto usuario -->
                        <div class="modal fade" id="frm-user-foto">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4></h4>
                                    </div>
                                    <div class="modal-body text-center">
                                        <input type="file" id="imagen" name="imagen" accept="image/jpeg" class="classHide">
                                        <img id="emp-foto" src="<?= URL_DATA ?>empleado/profile.png" alt="" class="thumbnail">
                                    </div>
                                    <div class="modal-footer">
                                        <?php if(in_array(MOD_USUARIOS_ADD, $permisos) || in_array(MOD_USUARIOS_EDIT, $permisos) ) :  ?>
                                            <button id="btnFoto" type="button" class="btn btn-blink-info"><i data-feather='camera'></i> Cambiar Foto</button>
                                        <?php endif; ?>
                                        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        <input type="hidden" id="user-id-img" value="0">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Termina modal foto usuario -->
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml';?>
    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                apiUrlRh = '<?= URL_ROOT ?>/rh/',
                dtUserTable = $('#tbl-usuarios'),
                newUserSidebar = $('.new-user-modal'),
                newUserForm = $('.add-new-user'),
                select = $('.select2'),
                dtContact = $('.dt-contact');

            getItems('tbl-usuarios');

            // Abre modal para agregar un nuevo usuario
            <?php if(in_array(MOD_USUARIOS_ADD, $permisos)) :  ?>
                $('#btnAdd').click(function(){
                    getTypeUser();
                    clearFields();
                    $('#frm-pers h5').html('Agregar Usuario');
                    $('#kypass').attr("placeholder", "Contraseña");
                    $("#fgKm").hide();
                    str = $(this).parents('tr').text();
                    $('#frm-pers').modal('show');
                });

                // Muestra dos campos unicamente para tipo de usuario mensajero y comisionista
                $('#cboTUsr').change(function (e){
                    id_u = $('#cboTUsr').val();
                    if(id_u == '1' || id_u == '2' || id_u == '5' || id_u == '8' || id_u == '9' || id_u == '11'){
                        $('#fgKm').show();
                    } else{
                        $('#fgKm').hide();
                    }
                });

                // Agrega un usuario nuevo a la base de datos
                $('#btnSave').on('click', function(){
                    $('.alert').remove();
                    err = $('<div class="alert alert-blink-danger"></div>');
                    data = {
                        fk_id_tipo_usuario: $.trim($('#cboTUsr').val()),
                        nombre: sinDiacriticos( $.trim($('#pers-nom').val())),
                        apellidos: sinDiacriticos( $.trim($('#pers-ape').val())), 
                        email: $.trim($('#email').val()),
                        calle: sinDiacriticos( $.trim($('#calle').val())),
                        numero: sinDiacriticos( $.trim($('#dr-num').val())),
                        colonia: sinDiacriticos( $.trim($('#colon').val())),
                        ciudad: sinDiacriticos( $.trim($('#estado').val())),
                        tel_casa: $.trim($('#pers-tel').val()), 
                        tel_cel: $.trim($('#pers-cel').val()),
                        login: sinDiacriticos( $.trim($('#user').val())),
                        contrasena: $.trim($('#kypass').val()),
                        com_ent: '',
                        del_muni: sinDiacriticos( $.trim($('#municipio').val())),
                        num_int: $.trim($('#dr-num-int').val()),
                        tel_adi: sinDiacriticos( $.trim($('#pers-tel-add').val())),
                        observaciones: sinDiacriticos( $.trim($('#observ').val())),
                        id_fact: $.trim($('#pers-emple').val()),
                    };  
                    confContrasena = $.trim($('#kypassConf').val());
                    id = parseInt($('#pers-id').val(),10);
                    btn = $(this);
                    btn.addClass('disabled');
                    
                    if(data.fk_id_tipo_usuario == 0){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe seleccionar un Tipo de Usuario.');
                        $('#cboTUsr').parent().append(err);
                        $('#cboTUsr').focus();
                        btn.removeClass('disabled');
                    }else if(data.nombre.length == 0 || data.nombre.length < 4){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un nombre valido.');
                        $('#pers-nom').parent().append(err);
                        $('#pers-nom').focus();
                        btn.removeClass('disabled');
                    }else if(data.apellidos.length == 0 || data.apellidos.length < 4){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un apellido valido.');
                        $('#pers-ape').parent().append(err);
                        $('#pers-ape').focus();
                        btn.removeClass('disabled');
                    }else if(data.email.length == 0 || data.email.length < 4){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un correo electrónico valido.');
                        $('#email').parent().append(err);
                        $('#email').focus();
                        btn.removeClass('disabled');
                    }else if(data.login.length == 0 || data.login.length < 3){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un usuario valido.');
                        $('#user').parent().append(err);
                        $('#user').focus();
                        btn.removeClass('disabled');
                    }else if(id == 0 && (data.contrasena.length == 0 || data.contrasena.length < 7)){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar una contraseña con más de 7 carácteres.');
                        $('#kypass').parent().append(err);
                        $('#kypass').focus();
                        btn.removeClass('disabled');
                    }else if(id == 0 && (data.tel_casa.length == 0 || data.tel_casa.length < 10)){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un número de teléfono valido.');
                        $('#pers-tel').parent().append(err);
                        $('#pers-tel').focus();
                        btn.removeClass('disabled');
                    }else if(id == 0 && (data.tel_cel.length == 0 || data.tel_cel.length < 10)){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un número de celular.');
                        $('#pers-cel').parent().append(err);
                        $('#pers-cel').focus();
                        btn.removeClass('disabled');
                    }else if(id == 0 && (data.tel_adi.length > 0 && data.tel_adi.length < 10)) {
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('Debe ingresar un número de adicional valido.');
                        $('#pers-tel-add').parent().append(err);
                        $('#pers-tel-add').focus();
                        btn.removeClass('disabled');
                    }else if(confContrasena != data.contrasena){
                        $(err).removeClass('alert-blink-warning');
                        $(err).addClass('alert-blink-danger');
                        $(err).append('La contraseña no corresponde.');
                        $('#kypassConf').parent().append(err);
                        $('#kypassConf').focus();
                        btn.removeClass('disabled');
                    }
                    else{
                        btn.addClass('disabled');
                        AddEditUser(data,id);
                        btn.removeClass('disabled');
                        $('.alert').remove();
                    }
                    $('#fgKm').hide();
                });

                // Muestra los tipos de usuario existentes en la base de datos y agrega acciones a algunos
                $('#btnTypeUser').click(function() {   
                    $('#frm-type-user .tooltip-error').remove();
                    $.ajax({
                        url: apiUrl+'usuario/getTypeUser',
                        type: 'get',
                        dataType: "json",
                        success: function (resp) {
                        $('#tbl-TypeUser tbody').empty();
                            if ( $.fn.dataTable.isDataTable( '#tbl-TypeUser' ) ) {
                                table = $('#tbl-TypeUser').DataTable();
                                table.clear();
                                table.destroy();
                            }
                            if(resp.result.length > 0){
                                $.each(resp.result, function(index, item){
                                    addTypeUserRow(item);
                                });
                                $('#tbl-TypeUser').dataTable( { 
                                    scrollY: '600px',
                                    scrollX: true,
                                    paging:  false,
                                    dom:     'Rlfrtip',
                                    ordering: true,
                                    "columnDefs": [{"width": "60%", "orderable": true, "targets": [0] }],
                                    "oColReorder": { "iFixedColumns": 1 },
                                    "scrollCollapse": true,
                                });
                                $("#tbl-TypeUser_info").hide();
                                $("#tbl-TypeUser_filter label").hide();
                            }else{
                                $('#tbl-TypeUser').append('<tr id="nodata"><td colspan="5">No se encontraron registros.</td></tr>');
                            }
                        },
                    });
                    $('#frm-type-user').modal('show');
                }); 

                // Abre modal para agregar un nuevo tipo de usuario
                $('#btnNewTypeUser').on('click', function() {
                    $('#frm-type-user-acciones h4').html('Agregar Tipo de Usuario')
                    $('#descripcion-nuevo-perfil').val('');
                    $('#id_type_user').val(0);
                    $('#frm-type-user-acciones').modal('show');
                    $("#btnSaveNewPerfil").show();   
                    $("#btnUpdatePerfil").hide();   
                    $("#btnDelPerfil").hide();   
                });

                // Guarda en la base de datos el nuevo tipo de usuario
                $('#btnSaveNewPerfil').click(function(){
                    $('.alert').remove();
                    err = $('<div class="alert alert-blink-danger"></div>');
                    data = { descripcion: sinDiacriticos($.trim($('#descripcion-nuevo-perfil').val())) };
                    btn = $(this);
                    btn.addClass('disabled');
                    if(data.descripcion.length < 3){
                        $(err).append('Debe ingresar un nombre de mas de tres caracteres.');
                        $('#descripcion-nuevo-perfil').parent().append(err);
                        $('#descripcion-nuevo-perfil').focus();
                        btn.removeClass('disabled');
                    }else{
                        btn.removeClass('disabled');
                        $.ajax({
                            url: apiUrl+'usuario/createProfile',
                            type: 'post',
                            data: data,
                            dataType: "json",
                            success: function(resp){
                                if(resp.response){
                                    step1('#tbl-TypeUser');
                                    addTypeUserRow(data, resp.result);
                                    step2('#tbl-TypeUser');
                                    btn.removeClass('disabled');
                                    $('#frm-type-user-acciones').modal('hide');

                                }else{
                                    toastr["error"]("Ocurrió un error!", resp.message);
                                    btn.removeClass('disabled');
                                }
                            },
                        });
                        $('#descripcion-nuevo-perfil').val('');
                        $("#frm-pers-new-type-user").modal('show');
                    }
                });

                // Abre modal para editar un tipo de usuario 
                $('#tbl-TypeUser').on('click', '.btnEditTypeUser', function() {
                    tr = $(this).parents("tr");
                    id = $(this).parents("td").data('id');
                    $('#id_type_user').val(id);
                    $('#frm-type-user-acciones h4').html('Editar Tipo de Usuario');
                    nom = tr.find('td:eq(0)').text();
                    $('#frm-type-user-acciones').modal('show');
                    $("#btnUpdatePerfil").show();   
                    $("#btnSaveNewPerfil").hide();   
                    $("#btnDelPerfil").hide();   
                    $('#descripcion-nuevo-perfil').val(nom);   
                });

                // Actualiza el nombre del tipo de usuario
                $('#btnUpdatePerfil').click(function() {
                    $('.alert').remove();
                    err = $('<div class="alert alert-blink-danger"></div>');
                    id = $('#id_type_user').val();
                    data = { descripcion: sinDiacriticos($('#descripcion-nuevo-perfil').val()) };
                    btn = $(this);
                    btn.addClass('disabled');
                    data = { descripcion: sinDiacriticos($.trim($('#descripcion-nuevo-perfil').val())) };
                    if(data.descripcion.length < 3){
                        setError('descripcion-nuevo-perfil','Debe ingresar un nombre de mas de tres caracteres');
                        btn.removeClass('disabled');
                    }else{
                        $.ajax({
                            url: apiUrl+'usuario/updateTypeUser/'+id,
                            type: 'put',
                            data: data,
                            dataType: "json",
                            success: function (resp) {
                                if (resp.response) {
                                    row = $("[data-id='"+id+"']").parent();
                                    row.remove();  
                                    $('#frm-type-user-acciones').modal('hide');
                                    table = $('#tbl-TypeUser').DataTable();
                                    table.row( row ).remove().draw();
                                    step1('#tbl-TypeUser');
                                    addTypeUserRow(data, resp.result);
                                    step2('#tbl-TypeUser');
                                    btn.removeClass('disabled');
                                } else {
                                    toastr["error"]("Ocurrió un error!", resp.message);
                                    btn.removeClass('disabled');
                                }
                            },
                        }); 
                    }
                });

                // Abre el modal que muestra todos los permisos existentes para que se asignen a un tipo de perfil
                $('#tbl-TypeUser').on('click', '.btnPermTypeUser', function(){
                    tr = $(this).parents("tr");
                    id = $(this).parents("td").data('id');
                    nom = tr.find('td:eq(0)').text();
                    $('#perm_user_id').val(id);
                    $('.checkPermTypeUser').removeAttr('checked');
                    $.ajax({
                        url: apiUrl+'usuario/getPermisosPerfil/'+id,
                        type: 'get',
                        dataType: "json",
                        success: function (resp) {
                            if (resp.response) {
                                $.each(resp.result, function (index1, valTU1) {
                                    $.each(valTU1, function (index, valTU) {
                                        if (index == 'fk_accion') {
                                            $('#chkpermTypeUser-' + valTU).attr('checked', 'checked');
                                        }
                                    });
                                });
                            } 
                            $('#frm-permisos-type-user span').html(' Permisos Para Tipo Usuario '+nom);
                            $('#frm-permisos-type-user').modal('show');
                        },
                    });
                });

                // Guarda en base de datos los permisos asignados al tipo de usuario
                $('.checkPermTypeUser').click(function() {
                    accion = $(this).val();
                    user = $('#perm_user_id').val();
                    agrega = $(this).is(':checked');
                    data = {
                        fk_perfil : user,
                        fk_accion : accion,
                        agrega    : agrega
                    };
                    $.ajax({
                        url: apiUrl+'usuario/updatePermitTypeUser',
                        type: 'post',
                        data: data,
                        dataType: "json",
                        success: function (resp) {
                        },
                    });
                });

                // Muestra el modal para solicitar confirmación de baja del tipo de usuario
                $('#frm-type-user').on('click', '.btnDelTypeUser', function(){
                    tr = $(this).parents("tr");
                    id = $(this).parents("td").data('id');
                    nom = tr.find('td:eq(0)').text();
                    $('#id_type_user').val(id);
                    $('#frm-type-user-acciones h4').html('Inactivar Tipo de Usuario');
                    $('#frm-type-user-acciones input').hide();
                    $('#frm-type-user-acciones label').removeClass('col-sm-3');
                    $('#frm-type-user-acciones h5').html('¿Estas seguro de inactivar el tipo de usuario <strong>'+nom+'</strong>?');
                    $('#frm-type-user-acciones').modal('show');
                    $("#btnDelPerfil").show();
                    $("#btnSaveNewPerfil").hide();   
                    $("#btnUpdatePerfil").hide();   
                });

                // Da de baja el tipo de usuario
                $('#btnDelPerfil').click(function(){
                    btn = $(this);
                    btn.addClass('disabled');
                    id = $('#id_type_user').val();
                    data = { status : 0}
                    $.ajax({
                        url: apiUrl+'usuario/delTypeUser/'+id,
                        type: 'put',
                        data: data,
                        dataType: "json",
                        success: function (resp) {
                            if (resp.response) {
                                row = $("[data-id='"+id+"']").parent();
                                row.remove();  
                                $('#frm-type-user-acciones').modal('hide');
                                table = $('#tbl-TypeUser').DataTable();
                                table.row( row ).remove().draw();
                                btn.removeClass('disabled');
                            } else {
                                toastr["error"]("Ocurrió un error!", 'No se ha inactivado el tipo de usuario, intenta mas tarde!');
                                btn.removeClass('disabled');
                            }
                        },
                    });     
                });
            <?php endif; ?>
            
            $('#btnClose').click(function() {
                $('#frm-type-user').modal('hide');
            });

            // <?php if($_SESSION['user'] == 1 || $_SESSION['user'] == 2 ||$_SESSION['user'] == 51) : ?>
            //     // Bloquea/desbloquea el sistema general
            //     $('#btnLockdown').click(function(e){
            //     e.preventDefault();
            //         <?php if($lockdown == 0) : ?>
            //             data = {lockdown: 1};
            //         <?php else: ?>
            //             data = {lockdown: 0};
            //         <?php endif; ?>
            //         $.ajax({
            //             url: apiUrl+'usuario/lockdown',
            //             type: 'PUT',
            //             dataType: "json",
            //             data: data,    
            //             success: function( resp ) {
            //                 if(resp.response){
            //                     window.location.reload();
            //                 }
            //             }
            //         });
            //     });
            // <?php endif; ?>
            
            <?php if(in_array(MOD_USUARIOS_EDIT, $permisos)) :  ?>
                $('#tbl-usuarios').on('click', '.btnEdit', function(e){
                    getTypeUser();                       

                    e.preventDefault();
                    id = $(this).data('id');
                    $.ajax({
                        url: apiUrl+'usuario/get/'+id,
                        type: 'GET',
                        dataType: "json",
                        success: function(resp) {
                            infoUser = resp.result;
                            $('#kypass').attr("placeholder", "Dejar en blanco para no modificar");
                            
                            if(infoUser['fk_id_tipo_usuario'] == 1 || infoUser['fk_id_tipo_usuario'] == 2 || infoUser['fk_id_tipo_usuario'] == 5 || infoUser['fk_id_tipo_usuario'] == 8 || infoUser['fk_id_tipo_usuario'] == 9 || infoUser['fk_id_tipo_usuario'] == 11){
                                $("#fgKm").show();
                            }else{
                                $("#fgKm").hide();
                            }

                            <?php if(in_array(MOD_EDIT_USER_PASS, $permisos)) : ?>
                                $("#UsuarioPass").show();
                            <?php else : ?>
                                $("#UsuarioPass").hide();
                            <?php endif; ?>

                            $('#cboTUsr option[value="'+infoUser['fk_id_tipo_usuario']+'"]').attr("selected", true)
                            $('#pers-nom').val(infoUser['nombre']);
                            $('#pers-ape').val(infoUser['apellidos']);
                            $('#calle').val(infoUser['calle']);
                            $('#dr-num').val(infoUser['numero']);
                            $('#colon').val(infoUser['colonia']);
                            $('#pers-tel').val(infoUser['tel_casa']);
                            $('#pers-cel').val(infoUser['tel_cel']);
                            $('#dr-num-int').val(infoUser['num_int']);
                            $('#pers-tel-add').val(infoUser['tel_adi']);
                            $('#municipio').val(infoUser['del_muni']);
                            $('#estado').val(infoUser['ciudad']);
                            $('#observ').val(infoUser['observaciones']);
                            $('#email').val(infoUser['email']);
                            $('#user').val(infoUser['login']);
                            $('#pers-emple').val(infoUser['id_fact']);
                        }  
                    });
                    $('#frm-pers h5').html('Editar Usuario');
                    $('#pers-id').val(id);
                    $('#frm-pers').modal('show');
                });
            <?php endif; ?>

            // <?php if($_SESSION['user'] == 1 || $_SESSION['user'] == 2 ||$_SESSION['user'] == 51) : ?>
            //     $('#tbl-usuarios').on('click', '.btnBloquear', function(e) {
            //         e.preventDefault();
            //         id = $(this).data('id');
            //         data = { iniciar: 0 }
            //         trp = $(this).parents('tr');
            //         $.ajax({
            //             url: apiUrl+'usuario/lockdownIndividual/'+id,
            //             type: 'PUT',
            //             dataType: "json",
            //             data: data,    
            //             success: function( resp ) {
            //                 getItems('tbl-usuarios');
            //             }
            //         });
            //     });

            //     $('#tbl-usuarios').on('click', '.btnDesbloquear', function(e) {
            //         e.preventDefault();
            //         id = $(this).data('id');
            //         data = { iniciar: 1 }
            //         $.ajax({
            //             url: apiUrl+'usuario/lockdownIndividual/'+id,
            //             type: 'PUT',
            //             dataType: "json",
            //             data: data,    
            //             success: function( resp ) {
            //                 getItems('tbl-usuarios');
            //             }
            //         });
            //     });
            // <?php endif; ?>
            
            <?php if(in_array(MOD_USUARIOS_BAJA, $permisos)) :  ?>
                // Abre el modal que solicita los datos de la baja del usuario
                $('#tbl-usuarios').on('click', '.btnDesactivar', function(e){
                    e.preventDefault();
                    id = $(this).data('id');
                    name = $(this).data('name')

                    $('#frm-del-user strong').html(name);
                    $('#id_user_del').val(id);
                    $('#motivo_baja').val('0');
                    $('#observaciones_baja').val('');
                    $('#frm-del-user').modal('show');
                });
                
                // Da de baja del sistema al usuario, cambia de estatus 1 a estatus 0
                $('#btnInactivar').on('click', function(){
                    btn = $(this);
                    btn.addClass('disabled');
                    $('.alert').remove();
                    err = $('<div class="alert alert-blink-danger"></div>');
                    date = new Date();
                    y = date.getFullYear();
                    m = $.trim(date.getMonth() + 1).length == 1 ? '0'+(date.getMonth() + 1) : date.getMonth() + 1;
                    d = $.trim(date.getDate()).length == 1 ? '0'+date.getDate() : date.getDate();
                    baja = y+'-'+m+'-'+d;
                    if($('#motivo_baja').val() == null){
                        $(err).append('Seleccione el motivo de baja del usuario.');
                        $('#motivo_baja').parent().append(err);
                        btn.removeClass('disabled');
                    }else if($('#observaciones_baja').val()==''){
                        $(err).append('Agregue las observaciones de la baja del usuario.');
                        $('#observaciones_baja').parent().append(err);
                        btn.removeClass('disabled');
                    }else{
                        id = $('#id_user_del').val();
                        data = { 
                            baja: baja,
                            edo_usuario: 0,
                            motivo: $('#motivo_baja').val(),
                            observaciones: sinDiacriticos($('#observaciones_baja').val())
                        }

                        $.ajax({
                            url: apiUrl+'usuario/estatusUser/'+id,
                            type: 'PUT',
                            dataType: "json",
                            data: data,  
                            success: function( resp ) {
                                if(resp.response){
                                    toastr["success"]("Listo!", 'Usuario dado de baja');
                                    btn.removeClass('disabled');
                                    $('#frm-del-user').modal('hide');
                                    getItems('tbl-usuarios');
                                }else{
                                    toastr["error"]("Ocurrió un error!", 'No se dio de baja al usuario');
                                    btn.removeClass('disabled');
                                }
                            }  
                        });
                    }
                });

                // Activa al usuario, cambia de status 0 a status 1
                $('#tbl-usuarios').on('click', '.btnActivar', function(e){
                    e.preventDefault();
                    id = $(this).data('id');
                    name = $(this).data('name')

                    $('#frm-activar-user strong').html(name);
                    $('#id_user_activar').val(id);
                    $('#frm-activar-user').modal('show');
                });

                $('#btnActivar').on('click', function(){
                    btn = $(this);
                    btn.addClass('disabled');

                    id = $('#id_user_activar').val();
                    data = { edo_usuario: 1}
                
                    $.ajax({
                        url: apiUrl+'usuario/estatusUser/'+id,
                        type: 'PUT',
                        dataType: "json",
                        data: data,  
                        success: function( resp ) {
                            if(resp.response){
                                toastr["success"]("Listo!", 'Usuario activado');
                                btn.removeClass('disabled');
                                $('#frm-activar-user').modal('hide');
                                getItems('tbl-usuarios');
                            }else{
                                toastr["error"]("Ocurrió un error!", 'No se pudo activar al usuario');
                                btn.removeClass('disabled');
                            }
                        }  
                    });
                });
            <?php endif; ?>

            <?php if(in_array(MOD_USUARIOS_PERM, $permisos)) :  ?>
                $('#tbl-usuarios').on('click', '.btnPermisos', function(){
                    id = $(this).data('id');
                    $('#perm_user_id').val(id);
                    $('.checkPermiso').removeAttr('checked');
                    $.ajax({
                        url: apiUrl+'usuario/getUserPermisos/'+id,
                        type: 'GET',
                        dataType: "json",
                        success: function(resp) {
                            $.each(resp, function(index, val) {
                                $('#chkperm-'+val['fk_accion']).attr('checked', 'checked');
                            });
                        }  
                    });
                    $('#frm-permisos').modal('show');
                });

                $('#frm-permisos input:checkbox').change(function() {
                    user = $('#perm_user_id').val();
                    accion = $(this).val();
                    chk = $(this);
                    if($(this).is(':checked')) {
                        $.post(apiUrl+'seg_permiso/add/', {fk_usuario: user, fk_accion: accion}, function(resp) {
                            if(!resp.response) {
                                chk.prop('checked', false)
                            }
                        },'json');
                    }else{
                        $.ajax({
                            url: apiUrl+'seg_permiso/del/'+user+'/'+accion,
                            type: 'DELETE',
                            dataType: 'json',
                            success: function(resp) {
                                if(!resp.response) {
                                    chk.prop('checked', true)
                                }
                            }
                        });
                    }
                });
            <?php endif; ?>
            
            <?php if(in_array(MOD_USUARIOS_ADD, $permisos) || in_array(MOD_USUARIOS_EDIT, $permisos) ) :  ?>
                // $('#tbl-usuarios').on('click', '.btnFoto', function(){
                //     id = $(this).data('id');
                //     name = $(this).data('name');
                //     $('#frm-user-foto h4').html(name);
                //     $('#user-id-img').val(id);
                //     $('#emp-foto').prop('src', '<?= URL_DATA ?>empleado/profile.png');
                //     $.get(apiUrl+'rh/getFoto/'+id, function(data) {
                //         if(data){
                //             urlf = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                //             $('#emp-foto').prop('src', urlf);
                //         }
                //     });
                //     $('#frm-user-foto').modal('show');
                // });

                // $('#btnFoto').click(function(event) { $('#imagen').trigger('click'); });
                $('#imagen').change(function(event) {
                var fd = new FormData();
                var files = $('#imagen')[0].files[0];
                var id = $('#user-id-img').val();
                var urlf = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                fd.append('imagen',files);
                fd.append('fk_empleado',id);
                $('#resUP').addClass('hide').text('');
                if(files.type != 'image/jpeg'){
                    $('#resUP').removeClass('alert-info').removeClass('alert-success')
                                .addClass('alert-danger').removeClass('hide').text('Solo se permiten imagenes JPG');
                }else{
                    $.ajax({
                        url: apiUrl+'rh/addFoto',
                        type: 'post',
                        data: fd,
                        contentType: false,
                        processData: false,
                        success: function(resp){
                            if(resp.response){
                                $('#emp-foto').prop('src', urlf);
                            }else{
                                $('#resUP').removeClass('alert-info').removeClass('alert-success')
                                .addClass('alert-danger').text('No se pudo subir la foto. Intente nuevamente más tarde.');
                            }
                            $('#resUP').addClass('hide').text('');
                            $('#imagen').val(null);
                            getItems('tbl-usuarios');
                        },
                    });
                }
            });
            <?php endif; ?>

            // FUNCIONES
            function getItems(tbl){
                cleanTable(tbl);
                $('#'+tbl+' tbody').empty();
                createTable(tbl);
                info();
            }
            
            function cleanTable(tbl) {
                if($.fn.dataTable.isDataTable('#'+tbl)) {
                    table = $('#'+tbl).DataTable();
                    table.destroy();
                }
            }
        
            function AddEditUser(data, id){
                if(id == 0){
                    $.post(apiUrl+'usuario/addPersona',data, function(resp){
                        if(resp.response){
                            clearFields();
                            getItems('tbl-usuarios');
                            toastr["success"]('Usuario agregado.', "Listo!");
                            $('#frm-pers').modal('hide');                            
                        }else{  
                            toastr["error"]("Ocurrió un error!", resp.message);
                        }
                    },'json');
                }else{
                    data['id_usuario'] = id;
                    $.post(apiUrl+'usuario/editPersona/'+id, data, function(resp){
                        if(resp.response){
                            toastr["success"]("Listo!", 'Datos de usuario actualizados.');
                            $('#frm-pers').modal('hide');
                            getItems('tbl-usuarios');
                        }else{
                            if(resp == 'Debe seleccionar un tipo de usuario'){ toastr["warning"]("Verifique el tipo de usuario!", resp); }
                            else{ toastr["warning"]("No hay cambios!", resp); }
                        }
                    },'json');
                }
            }

            function info(){
                $.ajax({
                    url: apiUrl+'usuario/tiposUsuarios',
                    type: 'get',
                    dataType: "json",
                    success: 
                    function (resp) {
                        $('#totalAdmin').html('<center><b><h3>'+resp.admin+'</h3></b></center>Administrador');
                        $('#totalMen').html('<center><b><h3>'+resp.mensajeros+'</h3></b></center> Mensajero');
                        $('#totalClientes').html('<center><b><h3>'+resp.clientes+'</h3></b></center> Cliente');
                        $('#totalDirectivos').html('<center><b><h3>'+resp.directivos+'</h3></b></center> Directivo');
                        $('#totalComisionista').html('<center><b><h3>'+resp.comisionistas+'</h3></b></center> Comisionista');
                        $('#totalMecanico').html('<center><b><h3>'+resp.mecanicos+'</h3></b></center> Mecánico');
                        $('#totalRescatista').html('<center><b><h3>'+resp.rescatistas+'</h3></b></center> Rescatista');
                        $('#totalOperadores').html('<center><b><h3>'+resp.operadores+'</h3></b></center> Operador');
                        $('#totalCoordinadores').html('<center><b><h3>'+resp.coordinadores+'</h3></b></center> Coordinador');
                        $('#totalBicicletas').html('<center><b><h3>'+resp.bicicleta+'</h3></b></center> Bicicleta');
                    },
                }); 
            }

            function clearFields(){
                $('#cboTUsr').val(0);
                $('#pers-id').val(0);
                $('#frm-pers .tooltip-error').remove();
                $('#pers-nom').val('');
                $('#pers-ape').val('');
                $('#pers-tel').val('');
                $('#calle').val('');
                $('#dr-num').val('');
                $('#colon').val('');
                $('#pers-tel').val('');
                $('#pers-cel').val('');

                $('#dr-num-int').val('');
                $('#pers-tel-add').val('');
                $('#municipio').val('');
                $('#estado').val('');
                $('#observ').val('');

                $('#email').val('');
                $('#user').val('');
                $('#kypass').val('');
                $('#pers-emple').val('');
            }

            function addTypeUserRow(info) {
                tr = $('<tr></tr>');
                tda = $('<td data-id="'+info.id_tipo_usuario+'" data-fe="' + info.descripcion + '"></td>');
                if(info.id_tipo_usuario > 5) {
                    tda.append('<button type="button" class="btn btn-outline-blink-info btn-sm btnEditTypeUser" data-toggle="tooltip" title="Editar">'+feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+'</button> ');
                    tda.append('<button type="button" class="btn btn-outline-dark btn-sm btnPermTypeUser" data-toggle="tooltip" title="Permisos">'+feather.icons['lock'].toSvg({ class: 'font-small-4 me-20' })+'</button> ');
                    tda.append('<button type="button" class="btn btn-outline-danger btn-sm btnDelTypeUser" data-toggle="tooltip" title="Desactivar">'+feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+'</button>');
                }
                tr.append('<td>' + info.descripcion + '</td>');
                tr.append(tda); 
                $('#tbl-TypeUser').append(tr);
            }

            function getTypeUser(){
                // INICIO OBTENER EL TIPO DE USUARIO DE LA BASE DE DATOS
                $('#cboTUsr').attr('disabled','disabled').empty();
                $.ajax({
                    url: apiUrl+'usuario/getTypeUser',
                    type: 'get',
                    dataType: "json",
                    async: false,
                    success: function (resp) {
                        $('#cboTUsr').append('<option value="0" selected disabled>Seleccione una opción</option>');
                        $.each(resp.result, function(index, item) {
                            $('#cboTUsr').append('<option value="'+item.id_tipo_usuario+'">'+item.descripcion+'</option>');
                        });
                        $('#cboTUsr').removeAttr('disabled'); 
                        },
                    });
                // FIN OBTENER EL TIPO DE USUARIO DE LA BASE DE DATOS  
            }
            
            function createTable(){
                if (dtUserTable.length) {
                    dtUserTable.DataTable({
                        ajax: {
                            url: apiUrl+'usuario/getAllDataTable',
                            type: 'GET',
                        },
                        columns: [
                        // columns according to JSON
                        { data: 'id_fact' },
                        { data: 'nombre' },
                        { data: 'apellidos' },
                        { data: 'type_user' },
                        { data: 'type_user' },
                        { data: 'status' },
                        { data: '' }
                        ],
                        columnDefs: [
                            {
                                targets: 1,
                                responsivePriority: 4,
                                render: function (data, type, full, meta) {
                                    var nombre = full['nombre'],
                                    apellidos = full['apellidos'],
                                    id = full['data_id'];
                                    if(full['foto']){
                                        image = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                                    }else{
                                        image = '';
                                    }
                                    if (image != '') {
                                        var output =
                                            '<img src="' + image + '" alt="Avatar" height="40" width="35">';
                                    } else {
                                        var stateNum = Math.floor(Math.random() * 6) + 1;
                                        var states = ['success', 'danger', 'warning', 'info', 'dark', 'primary', 'secondary'];
                                        iniNom = full['nombre'].charAt(0);
                                        iniApe = full['apellidos'].charAt(0);
                                        var state = states[stateNum];
                                        initials = (iniNom + iniApe).toUpperCase();
                                        output = '<span class="avatar-content">' + initials + '</span>';
                                    }
                                    var colorClass = image === '' ? ' bg-light-' + state + ' ' : '';
                                    var salida =
                                        // '<div class="d-flex justify-content-left align-items-center '+colorIniciar+'">' +
                                        '<div class="d-flex justify-content-left align-items-center">' +
                                            '<div class="avatar-wrapper">' +
                                                '<button class="avatar btnFoto' +
                                                    colorClass +
                                                    ' me-1" data-id="'+id+'" data-name="'+nombre+' '+apellidos+'">' +
                                                    output +
                                                '</button>' +
                                            '</div>' +
                                            '<div class="d-flex flex-column">' +
                                                nombre +
                                            '</div>' +
                                        '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 3,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column">' +
                                        '<span >' +
                                            full['type_user'] +
                                        '</span>' +
                                        '<small class="emp_post text-muted">' +
                                        full['email'] +
                                        '</small>' +
                                    '</div>';
                                return salida;
                                }
                            },
                            {
                                // acciones
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['data_id'];
                                    name = full['nombre']+' '+full['apellidos'];
                                    type_user = full['id_type_user'];
                                    iniciar = full['iniciar'];
                                    colorIniciar = iniciar == 1 ? 'danger' : 'success';
                                    claseIniciar = iniciar == 1 ? 'btnBloquear' : 'btnDesbloquear';
                                    // textIniciar = iniciar == 1 ? 'Bloquear sistema' : 'Desbloquear sistema';
                                    status = full['status'];
                                    colorStatus = status == 'Activo' ? 'danger' : 'success';
                                    claseStatus = status == 'Activo' ? 'btnDesactivar' : 'btnActivar';
                                    classHide = status == 'Inactivo' ? ' classHide' : '';
                                    textStatus = status == 'Activo' ? 'Desactivar' : 'Activar';
                                    return (
                                        '<div class="btn-group">' +
                                            '<a class="btn btn-sm dropdown-toggle hide-arrow" data-bs-toggle="dropdown">' +
                                                feather.icons['more-vertical'].toSvg({ class: 'font-small-4' }) +
                                            '</a>' +
                                            '<div class="dropdown-menu dropdown-menu-end" style="width:max-content;">' +
                                                <?php if($_SESSION['user'] == 1 || $_SESSION['user'] == 2 || $_SESSION['user'] == 51) : ?>
                                                    // '<button type="button" id="btnLock" class="btn btn-outline-'+colorIniciar+' btn-sm '+claseIniciar+classHide+'" data-id="'+id+'" data-toggle="tooltip" title="'+textIniciar+'" style="margin-left:4px; margin-right:4px;">'+
                                                    //     feather.icons['slash'].toSvg({ class: 'font-small-4 me-20' })+
                                                    // '</button>'+
                                                <?php endif; ?>
                                                <?php if(in_array(MOD_USUARIOS_EDIT, $permisos)) : ?>
                                                    '<button type="button" class="btn btn-outline-blink-info btn-sm btnEdit" data-id="'+id+'" data-toggle="tooltip" title="Editar" style="margin-right:4px;">'+
                                                        feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+
                                                    '</button>'+
                                                <?php endif; ?>
                                                <?php if(in_array(MOD_USUARIOS_PERM, $permisos)) : ?>
                                                    '<button type="button" class="btn btn-outline-dark btn-sm btnPermisos" data-id="'+id+'" data-toggle="tooltip" title="Permisos" style="margin-right:4px;">'+
                                                        feather.icons['lock'].toSvg({ class: 'font-small-4 me-20' })+
                                                    '</button>'+
                                                <?php endif; ?>
                                                <?php if(in_array(MOD_USUARIOS_BAJA, $permisos)) : ?>
                                                    '<button type="button" class="btn btn-outline-'+colorStatus+' btn-sm '+claseStatus+'" data-id="'+id+'" data-name="'+name+'" data-type="'+type_user+'" data-toggle="tooltip" title="'+textStatus+'" style="margin-right:4px;">'+
                                                        feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+
                                                    '</button>'+
                                                <?php endif; ?>
                                            '</div>' +
                                        '</div>'
                                    );
                                }
                            },
                            {
                                visible: false, targets: [4]
                            }
                        ],
                        createdRow: function(row, data, dataIndex) {
                            if(data.iniciar == 0){                        
                                $(row).addClass('sistemaBloqueado');                                
                            }
                        },
                        order: [[3, 'asc'],[1, 'asc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'../spanish.json'
                        },
                        initComplete: function () {
                            var label = $('<label for="cuantos">Mostrar</label>').appendTo('#tbl-usuarios_length');
                            var selectCount = $('<select id="cuantos" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>')
                                .appendTo('#tbl-usuarios_length').on('change', function () {
                                    tipo = $('#tipoU').val();
                                    status = $('#statusU').val();
                                    dtUserTable.DataTable().page.len( $(this).val() ).draw();
                                    $('#statusU').val(status).trigger('change');
                                    $('#tipoU').val(tipo).trigger('change');
                                });

                            this.api()
                                .columns(4)
                                .every(function () {
                                var column = this;
                                
                                var select = $(
                                    '<select id="tipoU" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"><option value=""> Todos </option></select>'
                                    )
                                    .prependTo('#tbl-usuarios_length')
                                    .on('change', function () {
                                        dtUserTable.DataTable().column(4).search(
                                            $('#tipoU').val()
                                            ).draw();
                                            /** por si se quiere hacer una busqueda en toda la tabla */
                                            // $("#tbl-usuarios").DataTable().search(
                                                //     $('#tipoU').val(),
                                                // ).draw();
                                            });
                                var label = $('<label class="labelTypeU" class="form-label" for="tipoU">Tipo Usuario</label>').prependTo('#tbl-usuarios_length');
                                            
                                column
                                    .data()
                                    .unique()
                                    .sort()
                                    .each(function (d, j) {
                                        select.append('<option value="' + d + '" class="text-capitalize">' + d + '</option>');
                                    });
                                });

                            this.api()
                                .columns(5)
                                .every(function () {
                                    var column = this;
                                    if($('#statusU').length == 0){
                                        var select = $(
                                            '<select id="statusU" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"></select>'
                                            )
                                            .prependTo('#tbl-usuarios_length').on('change', function () {
                                                var val = $.fn.dataTable.util.escapeRegex($(this).val());
                                                column.search(val ? '^' + val + '$' : '', true, false).draw();                                 
                                            })
                                        var label = $('<label for="statusU">Status</label>').prependTo('#tbl-usuarios_length');
                                        
                                        column
                                            .data()
                                            .unique()
                                            .sort()
                                            .each(function (d, j) {
                                                $("#statusU").append('<option value="' + d + '" class="text-capitalize">' + d + '</option>'); 
                                        });
                                    }
                                });
                            
                            $("#statusU option[value='Activo']").attr("selected", true);
                            $("#statusU").change();

                            $('#tbl-usuarios_length label:eq(2)').addClass('hidden');
                        }
                    });
                }
            }

            function step1($tableS1){
                if ( $.fn.dataTable.isDataTable( $tableS1 ) ) {
                    table = $($tableS1).DataTable();
                    table.destroy();
                }
                $("#nodata").remove();
            }

            function step2($tableS2){
                $($tableS2).dataTable( {    
                    scrollY: '600px',
                    scrollX: true,
                    paging:  false,
                    dom:     'Rlfrtip',
                    "columnDefs": [{"width": "350px", "orderable": false, "targets": [0] }],
                    "oColReorder": { "iFixedColumns": 1 },
                    "scrollCollapse": true
                });
                $($tableS2+"_filter label").hide();
            }

        });
    </script>
</html>