<?php 
	include 'header.phtml';
    
    define('MOD_VER',	  1);
    define('MOD_ADD',	  2);
    define('MOD_AD',	  3);
    define('MOD_EDIT',	  4);
    define('MOD_ASIGP',	  5);

    if(!in_array(MOD_VER, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <?php if(in_array(MOD_ADD, $permisos)) : ?>
                                <div class="card-body border-bottom alignRight">
                                    <div class="dt-buttons btn-group">
                                        <button type="button "id="btnAdd" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-usuario" tabindex="0" 
                                        aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                        data-target="#frm-usuario">
                                        <i data-feather="plus"></i>&nbsp;&nbsp;<span>Agregar</span></button>

                                        &nbsp;&nbsp;<button type="button "id="btnTypeUser" class="btn waves-effect waves-foat waves-light open-modal buttonModal" data-open="frm-type-user" tabindex="0" 
                                        aria-controls="DataTables_table_0" type="button" data-toggle="modal"
                                        data-target="#frm-tipos_usuarios">
                                        <i data-feather="user"></i>&nbsp;&nbsp;<span>Tipos de Usuario</span></button>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl-usuarios" class="table">
                                    <thead class="table-light">
                                        <tr>
                                            <th>No. Empleado</th>
                                            <th>Nombre</th>
                                            <th>Apellidos</th>
                                            <th>Tipo Usuario</th>
                                            <th>Tipo</th>
                                            <th>Celular</th>
                                            <th>Estatus</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>

                            <div class="modal modal-slide-in fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-usuario" >
                                <div class="modal-dialog ">
                                    <form class="modal-content pt-0">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase"></h4>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-usuario_tipo_id">Tipo de Usuario</label>
                                                <select id="user-usuario_tipo_id" class="form-select"></select>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-nombre">Nombre</label>
                                                <input type="text" class="form-control" id="user-nombre"/>
                                            </div>
                                            <div class="mb-1"> 
                                                <label class="form-label fw-bolder fs-5" for="user-apellidos">Apellidos</label>
                                                <input type="text" id="user-apellidos" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-email">Email</label>
                                                <input type="text" id="user-email" class="form-control email-inputmask"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-celular">Teléfono</label>
                                                <input type="text" id="user-celular" class="form-control phone-inputmask"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-username">Username</label>
                                                <input type="text" id="user-username" class="form-control" placeholder="Nombre de usuario con el que ingresará al sistema"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-contrasena">Contraseña</label>
                                                <div class="input-group">
                                                    <div class="input-group input-group-merge form-password-toggle">
                                                        <input type="password" class="form-control form-control-merge" id="user-contrasena"/>
                                                        <span class="input-group-text cursor-pointer" ><i data-feather="eye"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-calle">Calle</label>
                                                <input type="text" id="user-calle" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-no_ext">No. Exterior</label>
                                                <input type="text" id="user-no_ext" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-no_int">No. Interior</label>
                                                <input type="text" id="user-no_int" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-colonia">Colonia</label>
                                                <input type="text" id="user-colonia" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-municipio">Municipio</label>
                                                <input type="text" id="user-municipio" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-estado">Estado</label>
                                                <input type="text" id="user-estado" class="form-control"/>
                                            </div>
                                            <div class="mb-1">
                                                <label class="form-label fw-bolder fs-5" for="user-codigo_postal">Código Postal</label>
                                                <input type="text" id="user-codigo_postal" class="form-control"/>
                                            </div> 
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success mb-1 data-submit" id="btnSave">Guardar</button>
                                                <input type="hidden" id="user_id" value="0">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal fade" id="frm-type-user">
                                <div class="modal-dialog modalMediano">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title text-uppercase">tipos de usuario</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-horizontal">
                                                <div class="modal-body">
                                                    <div class="alignRight">
                                                        <button id="btnNewTypeUser" type="button" class="btn btn-outline-secondary waves-effect waves-foat waves-light open-modal "><i class="fas fa-plus"></i>&nbsp;&nbsp;Agregar</button>
                                                    </div>
                                                    <table id="tbl-TypeUser" class="table table-condensed table-hover table-striped table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>Tipo de usuario</th>
                                                                <th style="text-align: center;">Acciones</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button id="btnClose" type="button" class="btn btn-danger mb-1">Salir</button>
                                                <input type="hidden" id="user-id" value="0">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="modal fade" id="frm-type-user-acciones">
                                <div class="modal-dialog modalMediano">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="text-uppercase"></h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <div class="col-sm-12">
                                                    <label for="descripcion-nuevo-perfil" class="col-sm-3 control-label input-sm"><h5></h5></label>
                                                    <input type="text" id="descripcion-nuevo-perfil" class="form-control input-sm" placeholder="Agregue el nombre del nuevo tipo de usuario">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button id="btnSaveNewPerfil" type="button" class="btn btn-success mb-1">Registrar</button>
                                                <button id="btnUpdatePerfil" type="button" class="btn btn-success mb-1">Actualizar</button>
                                                <button id="btnDelPerfil" type="button" class="btn btn-danger mb-1">Inactivar</button>
                                                <input type="hidden" id="id_type_user" value="0">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal modal-slide-in modal-danger fade" id="frm-del-user">
                                <div class="modal-dialog">
                                    <form class="modal-content pt-0">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase" id="exampleModalLabel">inactivar usuario</h4>
                                        </div>
                                        <div class="modal-body flex-grow-1">
                                            <div class="mb-1">
                                                ¿Estas seguro de inactivar a <strong></strong>?
                                            </div><br>
                                            <div>
                                                <label for="observaciones_baja" class="form-label"><h5>Observaciones</h5></label>
                                                <textarea id="observaciones_baja" name="observaciones_baja" rows="5" cols="40" placeholder="Observaciones de la baja del usuario"></textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <input  type="hidden" id="id_user_del" value="0">
                                                <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-danger me-1" id="btnInactivar">Inactivar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="modal modal-slide-in modal-success fade" id="frm-activar-user">
                                <div class="modal-dialog">
                                    <form class="modal-content pt-0">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase" id="exampleModalLabel">activar usuario</h4>
                                        </div>
                                        <div class="modal-body flex-grow-1">
                                            <div class="mb-1">
                                                ¿Estas seguro de cambiar el estatus de <strong></strong> a activo?
                                            </div><hr>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <input  type="hidden" id="id_user_activar" value="0">
                                                <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success me-1" id="btnActivar">Activar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div id="frm-permisos" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title text-uppercase"><i class="fas fa-lock"></i><span> permisos de usuario</span></h3>
                                        </div>
                                        <div class="modal-body">
                                            <div class="card-columns" style="column-count:2">
                                            <?php 
                                                $modulos = $todo->model->seg_modulo->getAll()->result; 
                                                foreach ($modulos as $modulo) :  ?>
                                                    <div>
                                                        <div class="card">
                                                            <div class="card-header nombreModulo">
                                                                <div class="card-title">
                                                                    <h4 class="tituloP"><?= $modulo->nombre ?></h4>
                                                                </div>
                                                                <div class="heading-elements me-1   ">
                                                                    <ul class="list-inline mb-0">
                                                                        <li><a data-action="collapse"><i data-feather="chevron-down"></i></a></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                            <div class="card-content collapse show">
                                                                <div class="card-body cardBody">
                                                                    <?php 
                                                                        $acciones = $todo->model->seg_accion->getByModulo($modulo->id)->result; 
                                                                        foreach ($acciones as $accion) : ?>
                                                                            <input type="checkbox" id="chkperm-<?= $accion->id ?>" value="<?= $accion->id ?>" class="filled-in checkPermiso">	
                                                                            <label for="chkperm-<?= $accion->id ?>"><?= $accion->nombre ?></label><br>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach;
                                            ?>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <input type="hidden" id="perm_user_id" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="frm-permisos-type-user" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title text-uppercase"><i class="fas fa-lock"></i><span></span></h3>
                                        </div>
                                        <div class="modal-body">
                                            <div class="card-columns" style="column-count:2">
                                            <?php 
                                                $modulos = $todo->model->seg_modulo->getAll()->result; 
                                                foreach ($modulos as $modulo) :  ?>
                                                    <?php if($modulo->nombre != 'Recibos Nomina') :?>
                                                        <div>
                                                            <div class="card">
                                                                <div class="card-header nombreModulo">
                                                                    <h5 class="card-title"><?= $modulo->nombre ?></h5>
                                                                    <div class="heading-elements">
                                                                        <ul class="list-inline mb-0">
                                                                            <li><a data-action="collapse"><i data-feather="chevron-down"></i></a></li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                                <div class="card-content collapse show">
                                                                    <div class="card-body cardBody">
                                                                        <?php 
                                                                            $acciones = $todo->model->seg_accion->getByModulo($modulo->id)->result; 
                                                                            foreach ($acciones as $accion) : ?>
                                                                                <input type="checkbox" id="chkpermTypeUser-<?= $accion->id ?>" value="<?= $accion->id ?>" class="filled-in checkPermTypeUser">	
                                                                                <label for="chkpermTypeUser-<?= $accion->id ?>"><?= $accion->nombre ?></label><br>
                                                                        <?php endforeach; ?>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php endif; ?>

                                                <?php endforeach;?>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <input type="hidden" id="perm_user_id" value="0">
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal fade" id="frm-user-foto">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4></h4>
                                        </div>
                                        <div class="modal-body text-center">
                                            <input type="file" id="imagen" name="imagen" accept="image/jpeg" class="classHide">
                                            <img id="usuario-foto" src="<?= URL_DATA ?>empleado/profile.png" alt="" class="thumbnail">
                                        </div>
                                        <div class="modal-footer">
                                            <?php if(in_array(MOD_ADD, $permisos) || in_array(MOD_EDIT, $permisos) ) :  ?>
                                                <button id="btnFoto" type="button" class="btn btn-new-info"><i data-feather='camera'></i> Cambiar Foto</button>
                                            <?php endif; ?>
                                            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button>
                                            <input type="hidden" id="user-id-img" value="0">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <?php include 'footer.phtml';?>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
    <script src="<?= URL_ROOT ?>/app-assets/js/mask.init.js"></script>
    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                dtUserTable = $('#tbl-usuarios'),
                newUserSidebar = $('.new-user-modal'),
                newUserForm = $('.add-new-user'),
                select = $('.select2'),
                dtContact = $('.dt-contact');

            getItems('tbl-usuarios')

            <?php if(in_array(MOD_ADD, $permisos)) : ?>
                $('#btnAdd').click(function(){
                    getTypeUser()
                    clear()
                    $('#frm-usuario h4').html('agregar usuario')
                    $('#frm-usuario').modal('show');
                });

                $('#btnTypeUser').click(function() {   
                    $.ajax({
                        url: apiUrl+'usuario/getTypeUser',
                        type: 'get',
                        dataType: "json",
                        success: function (resp) {
                        $('#tbl-TypeUser tbody').empty();
                            if ( $.fn.dataTable.isDataTable( '#tbl-TypeUser' ) ) {
                                table = $('#tbl-TypeUser').DataTable();
                                table.clear();
                                table.destroy();
                            }
                            if(resp.result.length > 0){
                                $.each(resp.result, function(index, item){
                                    addTypeUserRow(item);
                                });
                                $('#tbl-TypeUser').dataTable( { 
                                    scrollY: '600px',
                                    scrollX: true,
                                    paging:  false,
                                    dom:     'Rlfrtip',
                                    ordering: true,
                                    "columnDefs": [{"width": "60%", "orderable": true, "targets": [0] }],
                                    "oColReorder": { "iFixedColumns": 1 },
                                    "scrollCollapse": true,
                                });
                                $("#tbl-TypeUser_info").hide();
                                $("#tbl-TypeUser_filter label").hide();
                            }else{
                                $('#tbl-TypeUser').append('<tr id="nodata"><td colspan="5">No se encontraron registros.</td></tr>');
                            }
                        },
                    });
                    $('#frm-type-user').modal('show');
                }); 

                $('#btnNewTypeUser').on('click', function() {
                    $('#frm-type-user-acciones h4').html('agregar tipo de usuario')
                    $('#descripcion-nuevo-perfil').val('');
                    $('#id_type_user').val(0);
                    $('#frm-type-user-acciones').modal('show');
                    $("#btnSaveNewPerfil").show();   
                    $("#btnUpdatePerfil").hide();   
                    $("#btnDelPerfil").hide();   
                });

                $('#btnSaveNewPerfil').click(function(){
                    $('.alert').remove();
                    err = $('<div class="alert alert-blink-danger"></div>');
                    data = { nombre: sinDiacriticos($.trim($('#descripcion-nuevo-perfil').val())) };
                    btn = $(this);
                    btn.addClass('disabled');
                    if(data.nombre.length < 3){
                        $(err).append('Debe ingresar un nombre de al menos 3 caracteres.');
                        $('#descripcion-nuevo-perfil').parent().append(err);
                        $('#descripcion-nuevo-perfil').focus();
                        btn.removeClass('disabled');
                    }else{
                        btn.removeClass('disabled');
                        $.ajax({
                            url: apiUrl+'usuario/createProfile',
                            type: 'post',
                            data: data,
                            dataType: "json",
                            success: function(resp){
                                if(resp.response){
                                    data['id'] = resp.result
                                    step1('#tbl-TypeUser');
                                    addTypeUserRow(data, resp.result);
                                    step2('#tbl-TypeUser');
                                    btn.removeClass('disabled');
                                    $('#frm-type-user-acciones').modal('hide');

                                }else{
                                    toastr["error"]("Ocurrió un error!", resp.message);
                                    btn.removeClass('disabled');
                                }
                            },
                        });
                        $('#descripcion-nuevo-perfil').val('');
                        $("#frm-usuario-new-type-user").modal('show');
                    }
                });

                $('#tbl-TypeUser').on('click', '.btnEditTypeUser', function() {
                    tr = $(this).parents("tr")
                    id = $(this).parents("td").data('id')
                    $('#id_type_user').val(id)
                    $('#frm-type-user-acciones h4').html('editar tipo de usuario')
                    $('#frm-type-user-acciones h5').html('Tipo de usuario');
                    $('#frm-type-user-acciones input').show();
                    nom = tr.find('td:eq(0)').text()
                    $('#frm-type-user-acciones').modal('show')
                    $("#btnUpdatePerfil").show() 
                    $("#btnSaveNewPerfil").hide() 
                    $("#btnDelPerfil").hide()  
                    $('#descripcion-nuevo-perfil').val(nom)
                });

                $('#btnUpdatePerfil').click(function() {
                    btn = $(this);
                    btn.addClass('disabled');
                    id = $('#id_type_user').val();
                    data = { id: id, nombre: sinDiacriticos($('#descripcion-nuevo-perfil').val()) };
                    if(data.nombre.length < 3){
                        error('descripcion-nuevo-perfil', 'Debe ingresar un nombre de mas de tres caracteres')
                        btn.removeClass('disabled');
                    }else{
                        $.ajax({
                            url: apiUrl+'usuario/updateTypeUser/'+id,
                            type: 'put',
                            data: data,
                            dataType: "json",
                            success: function (resp) {
                                if (resp.response) {
                                    row = $("[data-id='"+id+"']").parent();
                                    row.remove();  
                                    $('#frm-type-user-acciones').modal('hide');
                                    table = $('#tbl-TypeUser').DataTable();
                                    table.row( row ).remove().draw();
                                    step1('#tbl-TypeUser');
                                    addTypeUserRow(data, resp.result);
                                    step2('#tbl-TypeUser');
                                    $('#frm-type-user').modal('show')
                                    btn.removeClass('disabled');
                                } else {
                                    toastr["error"]("Ocurrió un error!", resp.message);
                                    btn.removeClass('disabled');
                                }
                            },
                        }); 
                    }
                });

                $('#tbl-TypeUser').on('click', '.btnPermTypeUser', function(){
                    tr = $(this).parents("tr");
                    id = $(this).parents("td").data('id');
                    nom = tr.find('td:eq(0)').text();
                    $('#perm_user_id').val(id);
                    $('.checkPermTypeUser').removeAttr('checked');
                    $.ajax({
                        url: apiUrl+'usuario/getPermisosPerfil/'+id,
                        type: 'get',
                        dataType: "json",
                        success: function (resp) {
                            if (resp.response) {
                                $.each(resp.result, function (index1, valTU1) {
                                    $.each(valTU1, function (index, valTU) {
                                        if (index == 'seg_accion_id') {
                                            $('#chkpermTypeUser-' + valTU).attr('checked', 'checked');
                                        }
                                    });
                                });
                            } 
                            $('#frm-permisos-type-user span').html(' permisos para usuario tipo "'+nom+'"');
                            $('#frm-permisos-type-user').modal('show');
                        },
                    });
                });

                $('.checkPermTypeUser').click(function() {
                    accion = $(this).val();
                    user = $('#perm_user_id').val();
                    agrega = $(this).is(':checked');
                    data = {
                        usuario_tipo_id : user,
                        seg_accion_id : accion,
                        agrega    : agrega
                    };
                    $.ajax({
                        url: apiUrl+'usuario/updatePermitTypeUser',
                        type: 'post',
                        data: data,
                        dataType: "json",
                        success: function (resp) {
                        },
                    });
                });

                $('#frm-type-user').on('click', '.btnDelTypeUser', function(){
                    tr = $(this).parents("tr");
                    id = $(this).parents("td").data('id');
                    nom = tr.find('td:eq(0)').text();
                    $('#id_type_user').val(id);
                    $('#frm-type-user-acciones h4').html('Inactivar Tipo de Usuario');
                    $('#frm-type-user-acciones input').hide();
                    $('#frm-type-user-acciones label').removeClass('col-sm-3');
                    $('#frm-type-user-acciones h5').html('¿Estas seguro de inactivar el tipo de usuario <strong>'+nom+'</strong>?');
                    $('#frm-type-user-acciones').modal('show');
                    $("#btnDelPerfil").show();
                    $("#btnSaveNewPerfil").hide();   
                    $("#btnUpdatePerfil").hide();   
                });

                $('#btnDelPerfil').click(function(){
                    btn = $(this);
                    btn.addClass('disabled');
                    id = $('#id_type_user').val();
                    data = { status : 0}
                    $.ajax({
                        url: apiUrl+'usuario/delTypeUser/'+id,
                        type: 'put',
                        data: data,
                        dataType: "json",
                        success: function (resp) {
                            if (resp.response) {
                                row = $("[data-id='"+id+"']").parent();
                                row.remove();  
                                $('#frm-type-user-acciones').modal('hide');
                                table = $('#tbl-TypeUser').DataTable();
                                table.row( row ).remove().draw();
                                btn.removeClass('disabled');
                            } else {
                                toastr["error"]("Ocurrió un error!", 'No se ha inactivado el tipo de usuario, intenta mas tarde!');
                                btn.removeClass('disabled');
                            }
                        },
                    });     
                });
            <?php endif; ?>
            
            <?php if(in_array(MOD_EDIT, $permisos)) :  ?>
                $('#tbl-usuarios').on('click', '.btnEdit', function(e){
                    e.preventDefault()
                    $.blockUI()
                    clear('edit')
                    id = $(this).data('id');
                    $.get(apiUrl+'usuario/get/'+id, function(resp){
                        $.each(resp.result, function(index, item){
                            $('#user-'+index).val(item)
                        })
                        $('#user-contrasena').attr("placeholder", "Dejar en blanco para no modificar")
                        $('#user_id').val(resp.result.id)             
                        getTypeUser(resp.result.usuario_tipo_id)
                    },'json')
                    $('#frm-usuario h4').html('editar usuario');
                    $('#user-id').val(id);
                    $('#frm-usuario').modal('show');
                    $.unblockUI()
                });
            <?php endif; ?>

            $('#btnClose').click(function() {
                $('#frm-type-user').modal('hide');
            });

            $('#btnSave').on('click', function(){
                $.blockUI()
                btn = $(this);
                btn.addClass('disabled');
                id = $('#user_id').val()
                data = {};
                $.each($('#frm-usuario input, #frm-usuario select'), function(index, item){
                    ide = $(item).attr('id').replace('user-','')
                    data[ide] = $.trim($(item).val())
                })
                data['celular'] = data['celular'].replace('(','').replace(')','').replace(' ','').replace('-','')

                if(data.usuario_tipo_id == 0 || data.usuario_tipo_id == null){
                    error('user-usuario_tipo_id', 'Seleccione el tipo de usuario')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(data.nombre.length == 0 || data.nombre.length < 3){
                    error('user-nombre', 'El nombre debe contener al menos 3 caracteres')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(data.apellidos.length == 0 || data.apellidos.length < 3){
                    error('user-apellidos', 'Este campo debe contener al menos 3 caracteres')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(data.email.length == 0 || data.email.length < 4){
                    error('user-email', 'Debe ingresar un correo electrónico válido.')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(id == 0 && (data.celular.length == 0 || data.celular.length < 10)){
                    error('user-celular', 'Debe ingresar un número de celular.')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(data.username.length == 0 || data.username.length < 3){
                    error('user-username', 'Este campo debe contener al menos 3 caracteres, es el username con el que ingresará al sistema.')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else if(id == 0 && (data.contrasena.length == 0 || data.contrasena.length < 7)){
                    error('user-contraseña', 'Debe ingresar una contraseña de al menos 7 carácteres.')
                    btn.removeClass('disabled');
                    $.unblockUI()
                }else{
                    btn.addClass('disabled');
                    if(id == 0){
                        $.post(apiUrl+'usuario/add/1', data, function(resp){
                            if(resp.response){
                                toastr["success"]("¡Listo!", "Se agregó al usuario.")
                                $('#frm-usuario').modal('hide')
                                getItems('tbl-usuarios')
                            }else if(resp.error == 23000){
                                toastr["warning"]("¡Verifique la información!", resp.message)
                            }else{
                                toastr["error"]("¡Ocurrió un problema!", "No pudimos agregar al usuario.")
                            }
                            $.unblockUI()
                        },'json');
                    }else{
                        $.post(apiUrl+'usuario/edit/1/'+id, data, function(resp){
                            if(resp.response){
                                toastr["success"]("Listo!", 'Datos de usuario actualizados.');
                                $('#frm-usuario').modal('hide');
                                getItems('tbl-usuarios');
                            }else{
                                if(resp == 'Debe seleccionar un tipo de usuario'){ toastr["warning"]("Verifique el tipo de usuario!", resp); }
                                else{ toastr["info"]("No hay cambios!", resp); }
                            }
                            $.unblockUI()
                        },'json');
                    }
                    btn.removeClass('disabled');
                }
            });
            
            <?php if(in_array(MOD_AD, $permisos)) :  ?>
                $('#tbl-usuarios').on('click', '.btnDesactivar', function(e){
                    e.preventDefault();
                    id = $(this).data('id');
                    name = $(this).data('name')

                    $('#frm-del-user strong').html(name);
                    $('#id_user_del').val(id);
                    $('#observaciones_baja').val('');
                    $('#frm-del-user').modal('show');
                });
                
                $('#btnInactivar').on('click', function(){
                    btn = $(this);
                    btn.addClass('disabled');
                    if($('#observaciones_baja').val()==''){
                        error('observaciones_baja', 'Agregue las observaciones de la baja del usuario.')
                        btn.removeClass('disabled');
                    }else{
                        id = $('#id_user_del').val();
                        data = {
                            status: 0,
                            observaciones: sinDiacriticos($('#observaciones_baja').val())
                        }

                        $.post(apiUrl+'usuario/estatusUser/'+id, data, function(resp){
                            if(resp.response){
                                toastr["success"]("Listo!", 'Usuario dado de baja');
                                btn.removeClass('disabled');
                                $('#frm-del-user').modal('hide');
                                getItems('tbl-usuarios');
                            }else{
                                toastr["error"]("Ocurrió un error!", 'No se dio de baja al usuario');
                                btn.removeClass('disabled');
                            }
                        },'json')
                    }
                });

                $('#tbl-usuarios').on('click', '.btnActivar', function(e){
                    e.preventDefault();
                    id = $(this).data('id');
                    name = $(this).data('name')

                    $('#frm-activar-user strong').html(name);
                    $('#id_user_activar').val(id);
                    $('#frm-activar-user').modal('show');
                });

                $('#btnActivar').on('click', function(){
                    btn = $(this);
                    btn.addClass('disabled');

                    id = $('#id_user_activar').val();
                    data = { status: 1}
                
                    $.post(apiUrl+'usuario/estatusUser/'+id, data, function(resp){
                        if(resp.response){
                            toastr["success"]("Listo!", 'Usuario activado');
                            btn.removeClass('disabled');
                            $('#frm-activar-user').modal('hide');
                            getItems('tbl-usuarios');
                        }else{
                            toastr["error"]("Ocurrió un error!", 'No se activó al usuario');
                        }
                    },'json')
                    btn.removeClass('disabled');
                });
            <?php endif; ?>

            <?php if(in_array(MOD_VER, $permisos)) :  ?>
                $('#tbl-usuarios').on('click', '.btnPermisos', function(){
                    id = $(this).data('id');
                    $('#perm_user_id').val(id);
                    $('.checkPermiso').removeAttr('checked');
                    $.ajax({
                        url: apiUrl+'usuario/getUserPermisos/'+id,
                        type: 'GET',
                        dataType: "json",
                        success: function(resp) {
                            $.each(resp, function(index, val) {
                                $('#chkperm-'+val['seg_accion_id']).attr('checked', 'checked');
                            });
                        }  
                    });
                    $('#frm-permisos').modal('show');
                });

                $('#frm-permisos input:checkbox').change(function() {
                    user = $('#perm_user_id').val();
                    accion = $(this).val();
                    chk = $(this);
                    if($(this).is(':checked')) {
                        $.post(apiUrl+'seg_permiso/add/', {usuario_id: user, seg_accion_id: accion}, function(resp) {
                            if(!resp.response) {
                                chk.prop('checked', false)
                            }
                        },'json');
                    }else{
                        $.ajax({
                            url: apiUrl+'seg_permiso/del/'+user+'/'+accion,
                            type: 'DELETE',
                            dataType: 'json',
                            success: function(resp) {
                                if(!resp.response) {
                                    chk.prop('checked', true)
                                }
                            }
                        });
                    }
                });
            <?php endif; ?>
            
            <?php if(in_array(MOD_ADD, $permisos) || in_array(MOD_EDIT, $permisos) ) :  ?>
                $('#tbl-usuarios').on('click', '.btnFoto', function(){
                    $.blockUI()
                    id = $(this).data('id');
                    name = $(this).data('name');
                    $('#frm-user-foto h4').html(name);
                    $('#user-id-img').val(id);
                    $('#usuario-foto').prop('src', '<?= URL_DATA ?>empleado/profile.png');
                    $.get(apiUrl+'usuario/getFoto/'+id, function(data) {
                        if(data){
                            urlf = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                            $('#usuario-foto').prop('src', urlf);
                        }
                    });
                    $('#frm-user-foto').modal('show');
                    $.unblockUI()
                });

                $('#btnFoto').click(function(event) { $('#imagen').trigger('click'); });
                $('#imagen').change(function(event) {
                    var fd = new FormData();
                    var files = $('#imagen')[0].files[0];
                    var id = $('#user-id-img').val();
                    var urlf = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                    fd.append('imagen', files);
                    fd.append('usuario_id',id);
                    $('#resUP').addClass('hide').text('');
                    if(files.type != 'image/jpeg'){
                        $('#resUP').removeClass('alert-info').removeClass('alert-success')
                                    .addClass('alert-danger').removeClass('hide').text('Solo se permiten imagenes JPG');
                    }else{
                        $.ajax({
                            url: apiUrl+'usuario/addFoto',
                            type: 'post',
                            data: fd,
                            contentType: false,
                            processData: false,
                            success: function(resp){
                                if(resp.response){
                                    $('#usuario-foto').prop('src', urlf);
                                }else{
                                    $('#resUP').removeClass('alert-info').removeClass('alert-success')
                                    .addClass('alert-danger').text('No se pudo subir la foto. Intente nuevamente más tarde.');
                                }
                                $('#resUP').addClass('hide').text('');
                                $('#imagen').val(null);
                                getItems('tbl-usuarios');
                            },
                        });
                    }
                });
            <?php endif; ?>

            function getItems(tbl){
                cleanTable(tbl);
                $('#'+tbl+' tbody').empty();
                createTable(tbl);
            }
            
            function cleanTable(tbl) {
                if($.fn.dataTable.isDataTable('#'+tbl)) {
                    table = $('#'+tbl).DataTable();
                    table.destroy();
                }
            }

            function clear(accion='add'){
                $.each($('#frm-usuario input, #frm-usuario select'), function(index, item){
                    ide = $(item).attr('id')
                    if(ide != 'user-sucursal_id') $('#'+ide).val('')
                })
                if(accion != 'add') $('#user-contrasena').attr("placeholder", "Dejar en blanco para no modificar")
                else $('#user-contrasena').attr("placeholder", "")
                $('#user-id').val(0);
            }

            function addTypeUserRow(info) {
                console.log(info)
                tr = $('<tr></tr>');
                tda = $('<td data-id="'+info.id+'" data-fe="' + info.nombre + '"></td>');
                tda.append('<button type="button" class="btn btn-outline-new-info btn-sm btnEditTypeUser" data-toggle="tooltip" title="Editar">'+feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+'</button> ');
                tda.append('<button type="button" class="btn btn-outline-dark btn-sm btnPermTypeUser" data-toggle="tooltip" title="Permisos">'+feather.icons['lock'].toSvg({ class: 'font-small-4 me-20' })+'</button> ');
                if(info.id != 1){
                    tda.append('<button type="button" class="btn btn-outline-danger btn-sm btnDelTypeUser" data-toggle="tooltip" title="Desactivar">'+feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+'</button>');
                }
                tr.append('<td>' + info.nombre + '</td>');
                tr.append(tda); 
                $('#tbl-TypeUser').append(tr);
            }

            function getTypeUser(val=0){
                $('#user-usuario_tipo_id').attr('disabled','disabled').empty();
                $.get(apiUrl+'usuario/getTypeUser', function(resp){
                    if(resp.result.length > 0){
                        $('#user-usuario_tipo_id').append('<option value="0" selected disabled>Seleccione una opción</option>');
                        $.each(resp.result, function(index, item) {
                            $('#user-usuario_tipo_id').append('<option value="'+item.id+'">'+item.nombre+'</option>');
                        })
                    }else{
                        error('user-usuario_tipo_id', 'Agregue al menos un tipo de usuario desde "Tipos de Usuarios".')
                        $('#user-usuario_tipo_id').append('<option value="" selected disabled>No hay registros</option>');
                    }
                    $('#user-usuario_tipo_id').val(val).removeAttr('disabled')
                },'json')
            }
            
            function createTable(){
                if (dtUserTable.length) {
                    dtUserTable.DataTable({
                        ajax: {
                            url: apiUrl+'usuario/getAllDataTable',
                            type: 'GET',
                        },
                        columns: [
                        { data: 'id' },
                        { data: 'nombre' },
                        { data: 'apellidos' },
                        { data: 'type_user' },
                        { data: 'type_user' },
                        { data: 'celular' },
                        { data: 'status' },
                        { data: '' }
                        ],
                        columnDefs: [
                            {
                                targets: 1,
                                responsivePriority: 4,
                                render: function (data, type, full, meta) {
                                    var nombre = full['nombre'],
                                    apellidos = full['apellidos'],
                                    id = full['data_id'];
                                    if(full['foto']){
                                        image = '<?= URL_DATA ?>empleado/foto'+id+'.jpg';
                                    }else{
                                        image = '';
                                    }
                                    if (image != '') {
                                        var output =
                                            '<img src="' + image + '" alt="Avatar" height="40" width="40">';
                                    } else {
                                        var stateNum = Math.floor(Math.random() * 6) + 1;
                                        var states = ['success', 'danger', 'warning', 'info', 'dark', 'primary', 'secondary'];
                                        iniNom = full['nombre'].charAt(0);
                                        iniApe = full['apellidos'].charAt(0);
                                        var state = states[stateNum];
                                        initials = (iniNom + iniApe).toUpperCase();
                                        output = '<span class="avatar-content">' + initials + '</span>';
                                    }
                                    var colorClass = image === '' ? ' bg-light-' + state + ' ' : '';
                                    var salida =
                                        '<div class="d-flex justify-content-left align-items-center">' +
                                            '<div class="avatar-wrapper">' +
                                                '<span class="avatar btnFoto' +
                                                    colorClass +
                                                    ' me-1" data-id="'+id+'" data-name="'+nombre+' '+apellidos+'">' +
                                                    output +
                                                '</span>' +
                                            '</div>' +
                                            '<div class="d-flex flex-column">' +
                                                nombre +
                                            '</div>' +
                                        '</div>';
                                    return salida;
                                }
                            },
                            {
                                targets: 3,
                                render: function (data, type, full, meta) {
                                var salida =
                                    '<div class="d-flex flex-column">' +
                                        '<span >' +
                                            full['type_user'] +
                                        '</span>' +
                                        '<small class="emp_post text-muted">' +
                                        full['email'] +
                                        '</small>' +
                                    '</div>';
                                return salida;
                                }
                            },
                            {
                                // acciones
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['data_id'];
                                    name = full['nombre']+' '+full['apellidos'];
                                    type_user = full['id_type_user'];
                                    status = full['status'];
                                    logeado = id != <?= $_SESSION['usuario_id']?> ? '' : 'hidden';
                                    colorStatus = status == 'Activo' ? 'danger' : 'success';
                                    claseStatus = status == 'Activo' ? 'btnDesactivar' : 'btnActivar';
                                    classHide = status == 'Inactivo' ? ' classHide' : '';
                                    textStatus = status == 'Activo' ? 'Desactivar' : 'Activar';
                                    return (
                                        '<div class="text-center">' +
                                            <?php if(in_array(MOD_EDIT, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-new-info btn-sm btnEdit" data-id="'+id+'" data-toggle="tooltip" title="Editar" style="margin-right:4px;">'+
                                                    feather.icons['edit'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            <?php if(in_array(MOD_ASIGP, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-dark btn-sm btnPermisos" data-id="'+id+'" data-toggle="tooltip" title="Permisos" style="margin-right:4px;">'+
                                                    feather.icons['lock'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            <?php if(in_array(MOD_AD, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-'+colorStatus+' btn-sm '+claseStatus+' '+logeado+'" data-id="'+id+'" data-name="'+name+'" data-type="'+type_user+'" data-toggle="tooltip" title="'+textStatus+'" style="margin-right:4px;">'+
                                                    feather.icons['trash'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                        '</div>' 
                                    );
                                }
                            },
                            {
                                visible: false, targets: [4]
                            }
                        ],
                        order: [[3, 'asc'],[1, 'asc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'<?= URL_ROOT ?>/spanish.json'
                        },
                        initComplete: function () {
                            var label = $('<label for="cuantos">Mostrar</label>').appendTo('#tbl-usuarios_length');
                            var selectCount = $('<select id="cuantos" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>')
                                .appendTo('#tbl-usuarios_length').on('change', function () {
                                    tipo = $('#tipoU').val();
                                    status = $('#statusU').val();
                                    dtUserTable.DataTable().page.len( $(this).val() ).draw();
                                    $('#statusU').val(status).trigger('change');
                                    $('#tipoU').val(tipo).trigger('change');
                                });

                            this.api()
                                .columns(4)
                                .every(function () {
                                var column = this;
                                
                                var select = $(
                                    '<select id="tipoU" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"><option value=""> Todos </option></select>'
                                    )
                                    .prependTo('#tbl-usuarios_length')
                                    .on('change', function () {
                                        dtUserTable.DataTable().column(4).search(
                                            $('#tipoU').val()
                                        ).draw();
                                    });
                                var label = $('<label class="labelTypeU" class="form-label" for="tipoU">Tipo Usuario</label>').prependTo('#tbl-usuarios_length');
                                            
                                column
                                    .data()
                                    .unique()
                                    .sort()
                                    .each(function (d, j) {
                                        select.append('<option value="' + d + '" class="text-capitalize">' + d + '</option>');
                                    });
                                });

                            this.api()
                                .columns(6)
                                .every(function () {
                                    var column = this;
                                    if($('#statusU').length == 0){
                                        var select = $(
                                            '<select id="statusU" class="form-select text-capitalize mb-md-0 mb-2 select-dentro-datatable"></select>'
                                            )
                                            .prependTo('#tbl-usuarios_length').on('change', function () {
                                                var val = $.fn.dataTable.util.escapeRegex($(this).val());
                                                column.search(val ? '^' + val + '$' : '', true, false).draw();                                 
                                            })
                                        var label = $('<label for="statusU">Status</label>').prependTo('#tbl-usuarios_length');
                                        
                                        column
                                            .data()
                                            .unique()
                                            .sort()
                                            .each(function (d, j) {
                                                $("#statusU").append('<option value="' + d + '" class="text-capitalize">' + d + '</option>'); 
                                        });
                                    }
                                });
                            
                            $("#statusU option[value='Activo']").attr("selected", true);
                            $("#statusU").change();

                            $('#tbl-usuarios_length label:eq(2)').addClass('hidden');
                        }
                    });
                }
            }

            function step1($tableS1){
                if ( $.fn.dataTable.isDataTable( $tableS1 ) ) {
                    table = $($tableS1).DataTable();
                    table.destroy();
                }
                $("#nodata").remove();
            }

            function step2($tableS2){
                $($tableS2).dataTable( {    
                    scrollY: '600px',
                    scrollX: true,
                    paging:  false,
                    languaje: '<?= URL_ROOT ?>/spanish.json',
                    dom:     'Rlfrtip',
                    "columnDefs": [{"width": "350px", "orderable": false, "targets": [0] }],
                    "oColReorder": { "iFixedColumns": 1 },
                    "scrollCollapse": true
                });
                $($tableS2+"_filter label").hide();
            }

        });
    </script>
</html>