<?php 
	include 'header.phtml';
    define('MOD_VENTAS_DIA',  35);
    define('MOD_REABRIR',	  36);

    if(!in_array(MOD_VENTAS_DIA, $permisos)) {
		header('Location: '.URL_ROOT.'/403');
		exit;
	} 
?>
    <link rel="stylesheet" type="text/css" href="<?= URL_ROOT ?>/app-assets/plugin/sweetalert/sweetalert.css">

<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-fluid p-0">
            <div class="content-body">
                <section>
                    <div class="card">
                        <div class="card-body border-bottom">
                            <div class="card-body border-bottom alignRight">
                                <div class="dt-buttons btn-group">
                                    <input type="date" id="fecha" class="form-control" data-toggle="tooltip" title="Fecha" value="<?= date('Y-m-d')?>">
                                </div>
                                <button type="button "id="btnExportar" class="btn btn-success buttonModal">
                                    <i class="fas fa-file-excel"></i>&nbsp;&nbsp;<span>Cambios</span>
                                </button>
                            </div>
                            <div class="card-datatable table-responsive pt-0">
                                <table id="tbl-ventas" class="table">
                                    <thead class="table-light">
                                        <tr class="text-center">
                                            <th>Fecha</th>
                                            <th>Folio</th>
                                            <th>Usuario</th>
                                            <th>Cliente</th>
                                            <th>Total</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>

                            <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="frm-addpago">
                                <div class="modal-dialog">
                                    <form class="modal-content pt-0">
                                        <div class="modal-header mb-1">
                                            <h4 class="modal-title text-uppercase">agregar pago</h4>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body flex-grow-1 form-horizontal">
                                            <div class="mb-1 form-group row">
                                                <div class="w-100 mb-1">
                                                    <label class="form-label fw-bolder fs-5" for="monto">Monto</label>
                                                    <input type="number" class="form-control" id="monto" min="1">
                                                </div>
                                                <div class="w-100 mb-2">
                                                    <label class="form-label fw-bolder fs-5" for="forma_pago">Método de Pago</label>
                                                    <select class="form-control" id="forma_pago">
                                                        <option value="0" disabled>Seleccione una opción</option>
                                                        <option value="1">Efectivo</option>
                                                        <option value="2" class="hidden">Saldo a favor</option>
                                                        <option value="3">Tarjeta</option>
                                                        <option value="4">Transferencia</option>
                                                    </select>
                                                </div>
                                                <div class="w-100">
                                                    <div id="texto" class="alert alert-danger hidden" role="alert"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="buttonsEnd">
                                                <button type="reset" class="btn btn-outline-secondary mb-1" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-success mb-1" id="btnSave">Guardar</button>
                                                <input type="hidden" id="venta_id" value="0">
                                                <input type="hidden" id="saldo_favor" value="0">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script src="<?= URL_ROOT ?>/app-assets/plugin/sweetalert/sweetalert.min.js"></script>
    <?php include 'footer.phtml'; ?>

    <script>
        $(function(){
            var apiUrl = '<?= URL_ROOT ?>/',
                id_cliente = 0,
                actual = $('#fecha').val();

            getItems('tbl-ventas', actual)
                
            $('#fecha').change(function(){
                getItems('tbl-ventas', $(this).val())
            })

            $('#btnExportar').click(function(e){
                fecha = $('#fecha').val()
                e.preventDefault
                window.open(apiUrl+'venta/exportar/cambios/'+fecha, '_blank')
            })

            $('#tbl-ventas').on('click', '.btnDevolucion', function(){
                id = $(this).data('id')
                id_cliente = $(this).data('cliente')
                swal({
					title: "Devolución total",
					text: "¿Seguro que deseas realizar la devolución total de esta venta?",
					type: "warning",
					showCancelButton: true,
					cancelButtonText: "Cancelar",
					confirmButtonColor: "#DD6B55",
					confirmButtonText: "¡Devolver!",
					closeOnConfirm: false 
				},function(){
                    $.post(apiUrl+'venta/devolucion/'+id, function(resp){
                        if(resp.response){
							swal("¡Hecho!",	"Se realizó la devolución de los productos. Debes devolver al cliente $"+resp.devolucion+" pesos.", "success");
							getItems('tbl-ventas', actual)
						}else{
                            swal("¡Ocurrió un problema!", "No pudimos realizar la devolución de la venta", "error")
						}
                    },'json')
				});
            })

            $('#tbl-ventas').on('click', '.btnDevParcial', function(){
                id = $(this).data('id')
                venta = $.md5(id.toString())
                window.location.href = '<?= URL_ROOT ?>/venta/cambio/'+venta;              
            })

            $('#tbl-ventas').on('click', '.btnDesbloquear', function(){
                id = $(this).data('id')
                $.post(apiUrl+'venta/desbloquear/'+id, function(resp){
                    if(resp.response){
                        toastr['success']('¡Hecho!', 'Venta desbloqueada, ya puede utilizarla otro usuario')
                        getItems('tbl-ventas', actual)
                    }else{
                        toastr['danger']('¡Ocurrió algo extraño!', 'No pudimos desbloquear la venta')
                    }
                },'json')
            })

            $('#tbl-ventas').on('click', '.btnTicket', function(){
                id = $(this).data('id')    
                var mywindow = window.open('<?= URL_ROOT ?>/ticket/'+$.md5(id.toString()));
                var is_chrome = Boolean(mywindow.chrome);
                var mywindow2 = window.open('<?= URL_ROOT ?>/ticket/'+$.md5(id.toString()));
                var is_chrome2 = Boolean(mywindow2.chrome);
        
                if (is_chrome) {
                    setTimeout(function() {
                        mywindow.document.close();
                        mywindow.focus();
                        mywindow.print();
                        mywindow.close();
                    }, 250);
                } else {
                    mywindow.document.close();
                    mywindow.focus();
                    mywindow.print();
                    mywindow.close();
                }
                if (is_chrome2) {
                    setTimeout(function() {
                        mywindow2.document.close();
                        mywindow2.focus();
                        mywindow2.print();
                        mywindow2.close();
                    }, 250);
                } else {
                    mywindow2.document.close();
                    mywindow2.focus();
                    mywindow2.print();
                    mywindow2.close();
                }
            })

            function getItems(tbl, fecha){
                cleanTable(tbl)
                $('#'+tbl+' tbody').empty()
                createTable(tbl, fecha)
            }

            function cleanTable(tbl){
                if($.fn.dataTable.isDataTable('#'+tbl)){
                    table = $('#'+tbl).DataTable()
                    table.destroy()
                }
            }

            function createTable(tbl, fecha){
                if($('#'+tbl).length){
                    $('#'+tbl).DataTable({
                        ajax:{
                            url: apiUrl+'venta/getAllByDay/'+fecha,
                            type: 'GET',
                        },
                        columns: [
                            {data: 'fecha'},
                            {data: 'folio'},
                            {data: 'usuario'},
                            {data: 'cliente'},
                            {data: 'total'},
                            {data: ''}
                        ],
                        columnDefs: [
                            {
                                targets: -1,
                                title: 'Acciones',
                                orderable: false,
                                render: function (data, type, full, meta) {
                                    id = full['id']; saldo = full['saldo']; cliente_id = full['cliente_id'];
                                    mostrar = full['fecha'] == '<?= date('d-m-Y') ?>' ? '' : 'hidden'
                                    unlock = full['en_uso'] == 1 ? '' : 'hidden'
                                    return (
                                        '<div class="text-center">'+
                                            <?php if(in_array(MOD_REABRIR, $permisos)) : ?>
                                                '<button type="button" class="btn btn-outline-new-info btn-sm btnDevParcial" data-id="'+id+'" data-toggle="tooltip" title="Cambio" style="margin-right:4px;">'+
                                                    feather.icons['rotate-ccw'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                                '<button type="button" class="btn btn-outline-danger btn-sm btnDevolucion '+mostrar+'" data-id="'+id+'" data-cliente="'+cliente_id+'" data-toggle="tooltip" title="Devolución" style="margin-right:4px;">'+
                                                    feather.icons['refresh-ccw'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                                '<button type="button" class="btn btn-outline-warning btn-sm btnDesbloquear '+unlock+'" data-id="'+id+'" data-toggle="tooltip" title="Desbloquear" style="margin-right:4px;">'+
                                                    feather.icons['unlock'].toSvg({ class: 'font-small-4 me-20' })+
                                                '</button>'+
                                            <?php endif; ?>
                                            '<button type="button" class="btn btn-outline-dark btn-sm btnTicket" data-id="'+id+'" data-toggle="tooltip" title="Imprimir ticket" style="margin-right:4px;">'+
                                                feather.icons['file-text'].toSvg({ class: 'font-small-4 me-20' })+
                                            '</button>'+
                                        '</div>'
                                    );
                                }
                            },  
                            {
                                targets: 0,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column">' +
                                            '<span >' +
                                                full['fecha'] +
                                            '</span>' +
                                            '<small class="emp_post text-muted">' +
                                            full['hora'] +
                                            '</small>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                            {
                                targets: 4,
                                render: function (data, type, full, meta) {
                                    var salida =
                                        '<div class="d-flex flex-column text-end">' +
                                            '<span > $' +
                                                full['total'] +
                                            '</span>' +
                                        '</div>';
                                    return salida;
                                }
                            },                          
                        ],
                        order: [[1, 'desc']], 
                        dom:
                            '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75"' +
                            '<"col-sm-12 col-lg-2 d-flex justify-content-center justify-content-lg-start" f>' +
                            '<"col-sm-12 col-lg-10 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"l>>>' +
                            '>t' +
                            '<"d-flex justify-content-between mx-2 row mb-1"' +
                            '<"col-sm-12 col-md-6"i>' +
                            '<"col-sm-12 col-md-6"p>' +
                            '>',
                        language: {
                            url:'../spanish.json'
                        },
                    });
                }
            }

        });
    </script>
</html>