INSERT INTO `sat_regimenfiscal` (`id`, `clave`, `descripcion`) VALUES
(1, '601', 'General de Ley Personas Morales'),
(2, '603', 'Personas Morales con Fines no Lucrativos'),
(3, '605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'),
(4, '606', 'Arrendamiento'),
(5, '608', 'Demás ingresos'),
(6, '609', 'Consolidación'),
(7, '610', 'Residentes en el Extranjero sin Establecimiento Permanente en México'),
(8, '611', 'Ingresos por Dividendos (socios y accionistas)'),
(9, '612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
(10, '614', 'Ingresos por intereses'),
(11, '616', 'Sin obligaciones fiscales'),
(12, '620', 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'),
(13, '621', 'Incorporación Fiscal'),
(14, '622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
(15, '623', 'Opcional para Grupos de Sociedades'),
(16, '624', 'Coordinados'),
(17, '628', 'Hidrocarburos'),
(18, '607', 'Régimen de Enajenación o Adquisición de Bienes'),
(19, '629', 'De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales'),
(20, '630', 'Enajenación de acciones en bolsa de valores'),
(21, '615', 'Régimen de los ingresos por obtención de premios'),
(22, '626', 'Régimen Simplificado de Confianza'),
(23, '625', 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas');